visgl/luma.gl

src/program.js, src/scene.js
@philogb Can you test this with what you're working on? Let me know if it breaks something/doesn't work and I'll hop right back on it.
@ibgreen
=> add program.unsetBuffer function

package.json, src/webgl.js, test/unit/testwebgl.js
=> Better handling of headless environments.

examples/lessons/13/index.js
=> fix lesson 13

docs/scene.md
=> update scene docs

docs/event.md, src/event.js
=> update event docs

docs/camera.md
=> update camera docs

docs/math.md
@ibgreen @mikolalysenko 
Vast majority of these get rid of the LumaGL.* syntax in favor of accessing the naked classes.
Couple of minor wording improvements and removed PhiloGL release notes.
=> update math docs

docs/o3d.md
@ibgreen @mikolalysenko 
Changes similar to those made in the math docs - namespace removal, PhiloGL release note removal, minor edits.
=> update o3d docs

docs/camera.md, docs/event.md, docs/scene.md
@ibgreen here's some edits based on your comments from previous PRs.
=> respond to comments

examples/cubemap/index.html, examples/cubemap/index.js, examples/custom-picking/index.html, examples/custom-picking/index.js, examples/examples.css, examples/examples.js, examples/instancing/index.html, examples/multicontext/index.html, examples/persistence/index.html, examples/picking/index.html
@ibgreen Adds an example browsing framework very similar to what we have for the lessons.
https://github.com/uber-common/luma.gl/issues/27
=> add example browsing framework

travis.yml
This PR adds a travis.yml file for setting up Travis CI.  CC @ibgreen
=> Add travis.yml for travis-ci

.eslintignore, .jsdocrc, examples/core/picking/index.js, package.json, src/model.js, src/probe/README.md, src/probe/src/env.js, src/probe/src/error-utils.js, src/probe/src/index.js, src/probe/src/probe.js, src/probe/test/index.js, src/probe/test/probe-spec.js, src/scenegraph/pick.js, src/utils/log.js, src/webgl/buffer.js, src/webgl/context.js, src/webgl/program.js, src/webgl/shader.js, src/webgl/vertex-attributes.js, src/webgl/webgl-types.js
- No longer set debug by default (perf issue)
- Do not generate log strings when not actually logging (perf issue)
- Initial cut of new logging library (not used)
=> Debug cleanup

src/core/model.js, src/utils/index.js, src/utils/log.js, src/webgl/context.js, src/webgl/program.js, src/webgl/uniforms.js, src/webgl/vertex-attributes.js
@gnavvy @JasonPMoran
Fixes #94
Added missing call to getAttribLocation in program.js, which is the one line fix for the issue.
Also overhauled attribute and uniform logging which helped nail down the issue.
=> Linux fixes

src/bundle.js, src/core/model.js, src/headless.js, src/index.js, src/luma.js, src/utils/globals.js, src/utils/index.js, src/utils/is-browser.js, src/utils/log.js, src/webgl/context.js
luma global object wasn't reliably initialized, causing problems for deck.gl initialization, as well as for debugging in the browser.
@gnavvy
=> Ensure luma global object is accessible and correctly initialized.

_docs/test/webgl/draw-spec.js, _docs/test/webgl/fbo-spec.js, _docs/test/webgl/program-spec.js, _docs/test/webgl/vertex-array-object-spec.js, src/webgl/framebuffer.js
Fixed a bug that prevents the Framebuffer class from generating depth buffer
Fixed the path to the shaderlib folder in the test sources
=> Fix depth buffer generation bug of the Framebuffer class

src/webgl/context.js, src/webgl/draw.js
@ibgreen wasn't sure whether there was a better way to capture if we're working with a webgl 2 context. I'm working on webgl2 and had to patch luma this way to be able to work with it.
=> Fix instancing to work with webgl2 context

src/webgl/program.js, src/webgl/shader.js
As discussed this afternoon. @ibgreen @Pessimistress
=> Check compilation and linking status only when debug WebGL context is used

src/index.js, src/webgl/context-limits.js, src/webgl/context-state.js, test/webgl/context-limits.spec.js, test/webgl/context-state.spec.js, test/webgl/index.js
Initial GL context and limit management.
Documentation started in 
* [context](https://github.com/uber/luma.gl/blob/state-management/docs/webgl/context.md)
* [extensions](https://github.com/uber/luma.gl/blob/state-management/docs/webgl/extensions.md)
* [limits](https://github.com/uber/luma.gl/blob/state-management/docs/webgl/limits.md)
=> GL state and limit management

examples/core/instancing/app.js, examples/core/instancing/package.json, examples/core/instancing/yarn.lock, examples/core/shadowmap/src/app.js, examples/webpack.config.local.js, package.json, src/core/model.js, src/webgl/buffer.js, src/webgl/program.js, test/webgl/buffer.spec.js, test/webgl/program.spec.js
* Mainly fixes related to Buffer target type.
* Fixed a small WebGL2 porting issue in Program. 
* Updated the instancing example to make sure we have working test case.
=> Fix rendering. Buffer and Program updates

src/index.js
=> Fix FBO export

CHANGELOG.md, _docs/shaderlib/index.js, demo/index.html, demo/src/stylesheets/_icon.scss, examples/core/cubemap/app.js, examples/core/custom-picking/app.js, examples/core/instancing/app.js, experimental.js, src/addons/render-stats.js, src/geometry/test.js, src/index.js, src/webgl/context.js, src/webgl/framebuffer.js, src/webgl/program.js, test/browser.js
Updates a lot of dated examples towards the refactored v4 API, plus some other house keeping.
Will rebase this later when #146 lands, no need to review until then.
=> Fix examples - phase 1

docs/webgl/buffer.md, src/webgl/buffer.js
Improves WebGL2 support and documentation.
=> Buffer refactor

docs/webgl/program.md, docs/webgl/shader.md, docs/webgl/texture-2d-array.md, docs/webgl/transform-feedback.md, src/webgl/program.js, src/webgl/transform-feedback.js
=> Transform feedback improvements

src/webgl/context-state.js
=> Remove null parameters given to Float32Array constructor

CHANGELOG.md, docs/api-reference/webgl/uniform-buffer-layout.md, docs/user-guide/webgl2.md, docs/whats-new.md, src/index.js, src/webgl/uniform-buffer-layout.js, test/webgl/index.js, test/webgl/uniform-buffer-layout.spec.js
Basic support for `std140` uniform buffer layouts.
=> UniformBufferLayout class

src/webgl/context-state.js, src/webgl/index.js
Some leftovers from my previous fix... again... @ibgreen
=> Export fix

demo/contents/pages.js, examples/lessons/06/app.js, examples/lessons/07/app.js
- Lesson 6: Add WebGL example link.
- Lesson 7: 
Remove unnecessary texture code (probably copied over from lesson-6)
Remove dependency on Scene object , use shaders for lighting.
=> Fix lesson-7 example.

demo/contents/demos.js, demo/contents/pages.js, examples/lessons/08/app.js
-Remove dependency on Scene object and add custom VS and PS.
-Fix cube rotation to match with WebGL example.
=> Fix lesson-08

demo/contents/demos.js, demo/contents/pages.js, examples/lessons/09/app.js, examples/lessons/09/star.js
- Fix lesson 09 and enable it.
=> Lesson09: fixes

demo/contents/demos.js, demo/contents/pages.js, examples/lessons/16/app.js, src/core/model.js, src/webgl/index.js
- Re write lesson 16 to support "render to texture" and "point lighting".
- All of the features work similar to the corresponding webgl example except , specular highlights on moon and cube. Added 'TODO' comments that help debug this issue.
=> Re-write lesson 16.

src/webgl-utils/parameters.js, src/webgl-utils/track-context.js, test/webgl-utils/index.js, test/webgl-utils/parameters.spec.js, test/webgl-utils/track-context.spec.js
Unit tests, fixes and cleanup.
=> State management : Unit tests, fixes and cleanup.

data/webgl-api-json/webgl.json, src/webgl-utils/constants.js, test/webgl/context-state.spec.js
- Add a unit test for withParameters to test push/pop context with stack size > 1.
- Fix a typo in GL constants, FUNC_SUBSTRACT -> FUNC_SUBTRACT.
=> Add withParameters unit test + fix typo in GL constants

src/webgl/uniform-buffer-layout.js, src/webgl/uniforms.js
Also simplify the uniforms setter table
=> Support webgl2 uniforms

docs/api-reference/webgl/context-caps.md, src/webgl-utils/polyfill-context.js, src/webgl/context-features.js, test/webgl/context-features.spec.js
Mainly final renaming the capability constants and cleaning up the code/docs.
=> Finalize v4 capability management, code, test, docs

src/webgl/texture.js, test/webgl/texture.spec.js
=> Convert any v3 texture parameters to v4

src/core/animation-loop.js, src/core/pick-models.js, src/index.js, src/webgl-utils/README.md, src/webgl-utils/create-canvas.js, src/webgl-utils/create-context.js, src/webgl-utils/index.js, src/webgl/context.js, src/webgl/index.js, website/contents/pages.js, website/src/actions/app-actions.js, website/src/components/demo-runner.js, website/src/components/home.js, website/src/components/info-panel.js, website/src/components/page.js, website/src/reducers/viewport.js, website/src/static/images/icon-high-precision.svg, website/src/stylesheets/_home.scss
A round of cleanup of the canvas drawing buffer/animation loop/website code.
=> canvas and drawing buffer size fixes

src/core/pick-models.js, src/webgl/framebuffer.js, test/webgl/framebuffer.spec.js
- Fix readPixels in picking module.
- Add FrameBuffer unit tests for readPixels.
=> Fix picking module & add FB unit tests.

examples/core/instancing/app.js
Current encoding is going beyond max value 255, and resulting in wrong picking color. Fix the encoding. (Thanks to @ibgreen ).
=> Fix picking color encoding.

docs/api-reference/math/matrix4.md
Initial round of math doc updates.
=> Matrix docs

docs/README.md, docs/upgrade-guide.md, docs/whats-new.md
Some polishing around the documentations. Will merge before code review.
=> Polishing README.md, upgrade-guide.md and whats-new.md

src/webgl/texture.js
- Rename `subImage` to `setSubImageData` (inline with existing `setImageData`).
- Add `parameters` for `setSubImageData` and `setImageData`, these are applied temporarily before performing `textImageData` and `texSubImageData`, can be used for pixel store settings.
- Fix `ArrayBufferView` to use correct gl API.
- Update docs.
NOTE: Above rename (`subImage` to `setSubImageData`) is a breaking change, but I have not seen this is used anywhere in deck.gl or luma.gl, if any one else (any custom deck.gl layers) using it, we have to fix those.
Tested with : test-browser, examples and wind demo (that uses this new API).
=> Refine and Fix Texture's *ImageData API

docs/api-reference/primitives/cone.md, docs/api-reference/primitives/cube.md, docs/api-reference/webgl/query.md, docs/api-reference/webgl/renderbuffer.md, docs/api-reference/webgl/shader.md, docs/api-reference/webgl/texture-2d.md, docs/api-reference/webgl/texture-3d.md, docs/api-reference/webgl/texture-cube.md, docs/api-reference/webgl/texture.md, docs/api-reference/webgl/transform-feedback.md, docs/api-reference/webgl/vertex-array.md, src/webgl/texture.js, src/webgl/transform-feedback.js
* No functional changes.
CC: @shaojingli @gnavvy @Pessimistress
=> More documentation fixes

docs/README.md, docs/api-reference/core/README.md, docs/api-reference/core/model.md, src/index.js, website/contents/pages.js
Remove Object3D and Group from documentation.
@1chandu @Pessimistress
=> Fixing website

docs/api-reference/advanced/vertex-attributes.md, docs/api-reference/core/README.md, docs/api-reference/core/geometry.md, docs/api-reference/core/model.md, docs/api-reference/events/event.md, docs/api-reference/primitives/cone.md, docs/api-reference/primitives/cube.md, docs/api-reference/primitives/cylinder.md, docs/api-reference/primitives/ico-sphere.md, docs/api-reference/primitives/plane.md, docs/api-reference/primitives/sphere.md, docs/api-reference/webgl/buffer.md, docs/api-reference/webgl/context-limits.md, docs/api-reference/webgl/context-state.md, docs/api-reference/webgl/context.md, docs/api-reference/webgl/program.md, docs/api-reference/webgl/resource.md, docs/api-reference/webgl/sampler.md, docs/api-reference/webgl/texture-2d-array.md, docs/api-reference/webgl/texture-2d.md, docs/api-reference/webgl/texture-3d.md, docs/api-reference/webgl/texture-cube.md, docs/api-reference/webgl/texture.md, docs/api-reference/webgl/vertex-array.md
CC: @shaojingli @Pessimistress
=> Fix styling in documentation

examples/core/cubemap/app.js, website/src/components/header.js, website/src/components/info-panel.js, website/src/stylesheets/_gallery.scss, website/src/stylesheets/main.scss
For 4.0-release
- Use consistent header style as other frameworks
- Remove controls from cubemap example
=> Website styling

examples/core/cubemap/package.json, examples/core/cubemap/webpack.config.js, examples/core/fragment/package.json, examples/core/fragment/webpack.config.js, examples/core/instancing/package.json, examples/core/instancing/webpack.config.js, examples/core/mandelbrot/package.json, examples/core/mandelbrot/webpack.config.js, examples/core/picking/package.json, examples/core/picking/webpack.config.js, examples/core/shadowmap/webpack.config.js, examples/core/transform-feedback/package.json, examples/core/transform-feedback/webpack.config.js, examples/lessons/01/webpack.config.js, examples/lessons/02/webpack.config.js, examples/lessons/03/webpack.config.js, examples/lessons/04/webpack.config.js, examples/lessons/05/webpack.config.js, examples/lessons/06/webpack.config.js, examples/lessons/07/webpack.config.js, examples/lessons/08/webpack.config.js, examples/lessons/09/webpack.config.js, examples/lessons/16/webpack.config.js
CC @shaojingli @Pessimistress  
This should be ported to `4.0-release` branch.
=> Fix Webpack config to make examples run standalone.

CHANGELOG.md, package.json, src/core/model.js, src/utils/log.js, src/webgl/uniforms.js
=> Debug functionality polish

examples/lessons/11/app.js
There is no UI controls in website, need use default value
=> Fix website rendering issue for example "lesson 11"

package.json, src/shadertools/modules/fp64/test/fp64-shader.spec.js, src/shadertools/modules/fp64/test/webpack.config.js
=> Fix fp64 test

src/io/browser-load.js, src/io/load-files.js, src/webgl/shader.js, test/webgl/context-state.spec.js
Fixes for #259 #273 #300 
Verified with test-browser, examples.
=> Miscellaneous fixes: GLSL error reporting, BlendMinMax test, 'cross origin' image load

src/webgl/framebuffer.js, test/webgl/framebuffer.spec.js
=> Fix Framebuffer.clear

src/core/model.js
Attribute and uniform log flooding the console.
=> Fix model log bug

CHANGELOG.md, src/core/model.js
https://github.com/uber/deck.gl/blob/master/src/core/lib/layer.js#L452
=> Add `moduleSettings` to `Model.draw` arguments

src/core/animation-loop.js
Fix for #350 
Tested with test-browser and examples.
=> Fix AnimationLoop stop method

src/init.js, src/webgl/context.js
Doing a lot of startup logging right now and while the luma.gl logs are too valuable to remove, feel it is best to minimize noise.
=> Minimize console logs during startup

docs/api-reference/core/model.md, docs/api-reference/webgl/transform-feedback.md, docs/whats-new.md, examples/core/transform-feedback-instanced/app.css, examples/core/transform-feedback-instanced/app.js, examples/core/transform-feedback-instanced/index.html, examples/core/transform-feedback-instanced/package.json, examples/core/transform-feedback-instanced/webpack.config.js, src/core/model.js, src/webgl/program.js, src/webgl/transform-feedback.js, test/webgl/program.spec.js, test/webgl/transform-feedback.spec.js
- Add support for varyingMap, so TF buffers can be bound using varying name.
- Add new example for more TF api coverage.
- Update documentation and unit test coverage.
=> TransformFeedback:  Add varyingMap support + new TF instancing example.

package.json, src/debug/seer-integration.js, yarn.lock
=> Bump seer version safeguarding against window

src/core/animation-loop.js
=> Set preserveDrawingBuffer to true by default

docs/api-reference/core/animation-loop.md, docs/api-reference/core/model.md, docs/api-reference/webgl/buffer.md, docs/api-reference/webgl/program.md, docs/api-reference/webgl/transform-feedback.md, docs/whats-new.md, examples/core/transform-feedback-instanced/app.js
- Update documentation.
- Fix color in TF demo.
Verified running TF demo.
=> 5.1 Audit comments

docs/api-reference/core/experimental/transform.md, src/core/experimental/transform.js, src/index.js, src/webgl/buffer.js, test/core/experimental/transform.spec.js, test/core/index.js, test/webgl/buffer.spec.js
- Adding new class, `Transform` easy interface to perform TransformFeedback iterations.
- Add unit tests and update TF examples to use new API.
- Add Documentation with use cases.
Verified with TF examples and Wind Demo (deck.gl).
=> Add Transform class.

src/webgl/uniforms.js, test/webgl/uniforms.spec.js
https://github.com/uber/luma.gl/issues/421
=> Fix array uniform setting

src/debug/seer-integration.js
=> Fix a crash: model.geometry is optional

docs/roadmap.md
=> Add the right blog link in roadmap.md

src/deprecated/headless.js
=> Fixed crash caused by wrong utils folder path

examples/core/transform-feedback-instanced/app.js
For #401 
- Update TF demo to use new Transform class
Verified with updated example.
=> Update TF demo to use new Transform class

package.json, src/core/model.js, src/utils/index.js, src/utils/log.js, src/utils/old-log.js, src/webgl/uniforms.js, test/bench/index.js, webpack.config.js, yarn.lock
For #437
- Remove current logging util
- Import Log class from probe.gl
=> Use probe.gl for logging

debug.js, docs/get-started/debugging.md, docs/upgrade-guide.md, docs/whats-new.md, package.json, src/debug.js, src/webgl/context-debug.js
For #234 
- Optional bundling of `webgl-debug` module
- Update what's new and upgrade guide
=> webgl-debug: conditional bundling

examples/lessons/08/app.js, examples/lessons/08/index.html
Added controls to allow user to control the blending and lighting
- examples/lessons/08
=> fix example 08 with controls

.babelrc, CHANGELOG.md, package.json, src/webgl-utils/headless-gl.js
For #
babel-minify still has some issues, disable until we have time to fix them.
-
=> Disable babel minification (temporarily)

package.json, test/scripts/collect-metrics.sh, test/webpack.config.js
=> Add metrics collection

aliases.js, package.json, test/scripts/collect-metrics.sh, test/size/import-nothing.js, test/webpack.config.js, yarn.lock
For #
- Metrics collection code from deck.gl
=> Collect metrics

src/webgl/buffer.js, test/src/webgl/buffer.spec.js
For #476 
Found this issue while working on GPU Aggregation.
- Fix typo : ` indexed` to `indexed` (no space at beginning)
- Program `index` when provided.
- Add unit test
- Fix Uniform Buffer binding
=> Fix Uniform Buffer binding

src/core/animation-loop.js, src/index.js, src/init.js, src/utils/index.js, src/utils/is-browser.js, src/utils/is-electron.js, src/webgl-utils/debug-context.js, src/webgl-utils/set-parameters.js, src/webgl-utils/track-context-state.js, src/webgl/context.js, test/src/webgl/index.js
For #477 
- Fixes to electron and debug mode in AnimationLoop
-
=> Fixes to electron support and AnimationLoop debug mode

docs/api-reference/webgl/program.md, src/webgl/program.js, src/webgl/uniform-buffer-layout.js, test/src/webgl/uniform-buffer-layout.spec.js
For #484
- Add UBO related query methods for `Program` class.
- Fix offset calculation in `UniformBufferLayout`
- Add unit tests to verify offsets and full render path of UBO setting using new `Transform` class.
-  UniformBufferLayout: Fix offset calculation, add unit tests.
=> UniformBufferLayout: Fix offset calculation, add unit tests.

src/init.js, src/utils/index.js, src/utils/is-browser.js, src/utils/is-electron.js, src/webgl-utils/track-context-state.js
For #477 
- Add electron detection
- Detect when running in electron, treat as browser
- Automatically start tracking context when calling `pushContextState`
=> Electron support fixes

examples/lessons/14/webpack.config.js, examples/lessons/15/webpack.config.js
fix webpack file for example 14 and 15
=> fix webpack file for example 14 and 15

examples/lessons/08/app.js, examples/lessons/08/index.html, examples/lessons/14/app.js, examples/lessons/14/index.html, examples/lessons/15/app.js, examples/lessons/15/index.html, website/contents/demos.js, website/package-lock.json, website/package.json
For #
- Expose lessons14 and lessons15 to website demo
- Fix control elements
-
=> fix examples and controls

website/src/static/markdown/examples.md
For #
expose links for lesson 14 and lesson 15 in markdown index file
-
=> fix markdown file for webgl-lessons

CHANGELOG.md, package.json
- Prepare to publish new version
- Update CHANGELOG, package.json main version and dependencies:
=> Updates on master for 5.2.0-beta.2

README.md, docs/README.md, docs/developer-guide/building-apps.md, docs/get-started/examples.md, docs/get-started/installation.md, docs/roadmap.md
Fixes #503
- Explain to use release branch for examples
- Explain to use release branch for examples
- Removes outdated instructions in root README.md
- Various minor doc cleanup
=> Update docs for running examples

docs/api-reference/webgl/vertex-array.md, src/webgl/vertex-array.js, test/src/webgl/vertex-array.spec.js
For #496 
- Docs are outdated
- Remove the major inaccuracies from doc
- Cleanup
=> VertexArray docs, initial cleanup round

.markdownlintrc, docs/api-reference/advanced/vertex-attributes.md, docs/api-reference/advanced/webgl-bindings.md, docs/api-reference/webgl/transform-feedback.md, docs/api-reference/webgl/uniform-buffer-layout.md, docs/developer-guide/building-apps.md, docs/developer-guide/debugging.md, docs/get-started/README.md, docs/get-started/installation.md, docs/get-started/using-with-node.md, docs/upgrade-guide.md, docs/whats-new.md, package.json, scripts/lint-markdown.sh, yarn.lock
- Match new markdown linter setup in deck.gl
- Add markdown linter
- Start addressing linter warnings
=> Add markdown lint. Start adressing warnings

examples/core/cubemap/app.js, examples/core/instancing/app.js, examples/core/picking/app.js, examples/core/shadowmap/app.js, examples/core/transform-feedback/app.js, examples/core/transform/app.js, examples/lessons/01/app.js, examples/lessons/02/app.js, examples/lessons/03/app.js, examples/lessons/04/app.js, examples/lessons/05/app.js, examples/lessons/06/app.js, examples/lessons/07/app.js, examples/lessons/08/app.js, examples/lessons/10/app.js, examples/lessons/11/app.js, examples/lessons/12/app.js, examples/lessons/13/app.js, examples/lessons/14/app.js, examples/lessons/15/app.js, examples/lessons/16/app.js
For #504 
- Polish the website examples
- Fix all examples when running under website.
- Improve control panels for many examples.
=> Example polish

docs/README.md, docs/api-reference/README.md, docs/api-reference/core/animation-loop.md, docs/api-reference/webgl/shader.md
Hello, just fixing a couple of typos :)
=> Fix some docs typos

src/shadertools/modules/fp64/fp64.js
- Expose fp64ify, fp64LowPart, fp64ifyMatrix4 utils
=> Export fp64 util functions

docs/api-reference/shadertools/shadertools-picking.md
Inconsistent document vs. actual code
- one line change in the picking shader module
=> minor doc fix for the new picking shader module

docs/get-started/using-with-node.md, src/webgl-context/create-headless-context.js, src/webgl-utils/webgl-types.js
https://github.com/uber/deck.gl/issues/1888
- Remove unnecessary console.warn in webgl-types
- Add clarifying message to missing `gl` dependency
- Since most node.js use cases are testing cases, add `--save-dev` flag to `npm install gl`.
=> Clarify error message

dev-docs/RFCs/README.md, dev-docs/RFCs/v6.1/reduce-distribution-size-rfc.md
- Update RFC catalog based on latest planning iteration
=> Update RFC catalog

src/webgl-context/polyfill-vertex-array-object.js, test/src/core/experimental/transform.spec.js
=> Fix unit tests

docs/api-reference/webgl/buffer.md, docs/api-reference/webgl/fence-sync.md, docs/api-reference/webgl/framebuffer.md, docs/api-reference/webgl/program.md, docs/api-reference/webgl/query.md, docs/api-reference/webgl/transform-feedback.md, docs/api-reference/webgl/uniform-buffer-layout.md, docs/api-reference/webgl/vertex-array.md, docs/developer-guide/attributes.md, docs/developer-guide/buffers.md, docs/developer-guide/programs-and-shaders.md
- Cleanup work on API reference
- Some placeholder material for Developers Guide
=> Doc Improvements

docs/api-reference/core/attribute.md, docs/api-reference/core/shader-cache.md, docs/api-reference/core/transform.md, docs/upgrade-guide.md, docs/whats-new.md, examples/core/transform/app.js, package.json, src/index.js, test/src/core/attribute.spec.js, test/src/core/shader-cache.spec.js, test/src/core/transform.spec.js, test/src/webgl/uniform-buffer-layout.spec.js, yarn.lock
- src, examples, tests, docs, whats new.
=> Adopt new underscore convention for experimental exports

docs/README.md, docs/api-reference/core/model.md, docs/api-reference/core/transform.md, docs/api-reference/shadertools/glsl-reference.md, docs/api-reference/webgl/program.md, docs/api-reference/webgl/transform-feedback.md, docs/api-reference/webgl/vertex-array.md, docs/developer-guide/advanced/program-configuration.md, docs/developer-guide/attributes.md, docs/developer-guide/buffers.md, docs/developer-guide/building-apps.md, docs/developer-guide/configuring.md, docs/developer-guide/transform-feedback.md, docs/roadmap.md, docs/upgrade-guide.md, docs/whats-new.md
=> Doc refresh for 6.0 (partial)

dev-docs/RFCs/v6.1/reduce-distribution-size-rfc.md, dev-docs/RFCs/v6.1/shadertools-improvements-rfc.md, docs/upgrade-guide.md, examples/core/cubemap/app.js, examples/core/fragment/concentrics-demo.js, src/webgl/framebuffer.js, src/webgl/index.js, src/webgl/sampler.js, test/index-webgl-dependent-tests.js
- Cleanup to reduce main PR size
=> Minor cleanup for 6.0

src/core/model.js, src/webgl/buffer.js
- Model `vertexCount` and `drawMode` handling.
- temporarily restore `Buffer.data()`
=> Fixes for deck.gl integration.

docs/api-reference/core/model.md, examples/core/cubemap/app.js, examples/core/fragment/concentrics-demo.js, examples/core/fragment/index.html, examples/core/instancing/app.js, src/core/model.js, src/core/pick-models.js
- Adds support for function valued uniforms
- Add support to model class
- Update a few examples to use the feature
=> Uniform animation (experimental)

examples/core/instancing/app.js, examples/core/transform-feedback/app.js, src/core/model.js, src/webgl/vertex-array.js, test/src/core/index.js, test/src/core/model.spec.js
Address various issues after the VertexArray refactor
- Model: fix `_feedbackBuffers` prop not applied bug
- Model: fix generated attributes not deleted bug
- VertexArray: fix error when calling `bind(null)`
- Update instancing example to test generic attribute
- Update transform-feedback example to test transform feedback (currently broken)
- Add tests for Model class
=> Various bug fixes

examples/core/instancing/webpack.config.js, examples/core/transform-feedback/app.js, src/core/model.js, src/webgl/resource.js, src/webgl/transform-feedback.js, src/webgl/vertex-array.js
=> VertexArray.unbindBuffers(). Constant attribute logging,

docs/api-reference/core/transform.md, examples/core/transform/app.js, src/core/transform.js, src/webgl-utils/index.js, src/webgl-utils/shader-utils.js, test/src/core/transform.spec.js, test/src/webgl-utils/index.js, test/src/webgl-utils/shader-utils.spec.js
For #576 
Adding changes to make `Transform` class ready for release.
- Deduce varyings when not provided.
- Add utility method to get version from shader string, use it in `Transform`
- Update docs.
=> Transform updates

src/webgl/buffer.js
For #318
-  Buffer: Remove reference to data
=> Buffer: Remove reference to data

examples/core/instancing/app.js, src/core/attribute.js, src/core/model.js, src/webgl/uniforms.js, src/webgl/vertex-array.js
For #589 
Fix for instancing example, pushing changes from @ibgreen.
Use `constant` instead of `isGeneric` for `attribute` prop.
- Fix Instancing demo.
=> Fix Instancing demo.

docs/whats-new.md
For #591 #576 
- Update whats-new doc
=> Update whats-new doc

src/webgl/transform-feedback.js
For #598 
-  TranformFeedback: fix bug surfaced due to Chrome change
=> TranformFeedback: fix bug surfaced due to Chrome change

website/contents/pages.js
For #
Update URLs to point to 6.0-release branch
=> Update URLs to point to 6.0-release branch

src/webgl/vertex-array.js
=> Fix: set constant attributes every time VertexArray is bound

website/contents/pages.js
For #568 
Fix code link, also verified links for all other demos.
- Fix Transform demo link
=> Fix Transform demo link

src/webgl/texture.js
=> Fix NPOT warnings

docs/README.md, docs/developer-guide/attributes.md, src/index.js
Fixes #496
- attribute docs were a mess
- attribute docs
- whats new
- export Accessor as experiemetal
=> Update attribute docs

docs/api-reference/core/transform.md, docs/developer-guide/transform-feedback.md, docs/upgrade-guide.md, examples/core/transform/app.js, modules/core/src/index.js, test/modules/core/core/transform.spec.js, test/modules/core/shadertools/fp64/fp64-test-utils-transform.js, test/modules/core/webgl/uniform-buffer-layout.spec.js
For #623
- Rename export: _Transform to Transform
=> Rename export: _Transform to Transform

dev-docs/roadmaps/gpgpu-roadmap.md
For #
Update GPGPU roadmap doc
- Update GPGPU roadmap doc
=> Update GPGPU roadmap doc

dev-docs/RFCs/v6.1/transform-webgl1-support.md
For #
- RFC: WebGL1 support for Transform
=> RFC: WebGL1 support for Transform

modules/core/src/shadertools/src/lib/shader-module-registry.js, modules/core/src/shadertools/test/lib/assemble-shaders.spec.js
https://github.com/uber/luma.gl/issues/638
=> Fix: re-register shader module if ignoreMultipleRegistrations = true

modules/imageprocessing/src/modules/pack.js, test/modules/core/shadertools/index.js, test/modules/core/shadertools/pack.spec.js
For #
- Verifying precession of pack module conversion of float to RGBA U8 to float.
- Add unit tests using Transform.
-  Pack: Add unit tests
=> Pack: Add unit tests

dev-docs/RFCs/v6.1/transform-webgl1-support.md
For #640 
Update RFC with more specific implementation details and sample code.
This API also provides a way to perform `Offline Rendering` with least WebGL setup.
- RFC update: WebGL1 support for Transform
=> RFC update: WebGL1 support for Transform

docs/api-reference/webgl/accessor.md, docs/developer-guide/accessors.md, docs/developer-guide/buffers.md, modules/core/src/webgl/accessor.js, modules/core/src/webgl/buffer.js, modules/core/src/webgl/program-configuration.js, modules/core/src/webgl/vertex-array-object.js, modules/core/src/webgl/vertex-array.js, test/modules/core/webgl/accessor.spec.js, test/modules/core/webgl/vertex-array.spec.js, website/contents/pages.js
=> Accessor cleanup

modules/core/src/core/attribute.js, test/modules/core/core/attribute.spec.js
=> Attribute fixes

docs/api-reference/webgl/vertex-array.md, examples/core/instancing/app.js, modules/babel-plugin-inline-gl-constants/src/inline-gl-constants.js, modules/core/src/core/model.js, modules/core/src/webgl-debug/debug-program-configuration.js, modules/core/src/webgl-debug/debug-vertex-array.js, modules/core/src/webgl/program-configuration.js, modules/core/src/webgl/vertex-array-object.js, modules/core/src/webgl/vertex-array.js, modules/core/src/webgl1/index.js, modules/core/src/webgl1/polyfill-context.js, test/modules/core/core/model.spec.js, website/contents/demos.js, website/package.json
=> Misc Vertex Array fixes.

docs/api-reference/webgl/accessor.md, docs/api-reference/webgl/buffer.md, modules/core/src/utils/array-utils-flat.js, modules/core/src/webgl/buffer.js, test/modules/core/webgl/buffer.spec.js, test/modules/core/webgl/index.js, test/modules/core/webgl/vertex-array-object.spec.js
- Buffer class cleanup/improvements
- Enable VertexArrayObject tests
- as above
=> Buffer Cleanup

modules/core/src/utils/array-utils-flat.js, modules/core/src/webgl/buffer.js, modules/core/src/webgl/vertex-array-object.js, test/modules/core/webgl/vertex-array-object.spec.js
For #612 
- Implement allocation and filling of constant buffers for attribute 0
- Clean up `Buffer` class and docs
- as above
=> Implement allocation of constant buffers

modules/core/package.json, modules/core/src/webgl/program.js, modules/core/src/webgl/vertex-array-object.js, modules/core/src/webgl/vertex-array.js, test/modules/core/webgl/vertex-array-object.spec.js, test/modules/core/webgl/vertex-array.spec.js, yarn.lock
- Implement fallback to constant buffer
- Upgrade probe.gl
- Detect browser
- Handle cases where attribute 0 must be set using buffer
=> Handle attribute 0

docs/developer-guide/shadertools/writing-glsl-shaders.md, modules/core/src/shadertools/src/lib/transpile-shader.js, modules/core/src/shadertools/test/lib/transpile-shader.spec.js
For #648 
- Fix shader transpiler for texture sample instructions
=> Fix shader transpile in handling texture sample instructions

dev-docs/RFCs/v6.2/transform_floatTextures.md
For #671
- RFC: Transform - Float textures support.
=> RFC: Transform - Float textures support.

docs/FAQ.md, docs/api-reference/core/geometry.md, modules/core/src/webgl-utils/webgl-types.js, website/src/mdRoutes.js
- Tone down info message
- FAQ
=> Tone down headless-gl info message. Add FAQ entry.  

test/modules/core/webgl/program-configuration.spec.js
For #
- Fix unit test
- Fix unit test
=> Fix unit test

modules/core/src/core/attribute.js, test/modules/core/core/attribute.spec.js, website/src/mdRoutes.js
For #
- Fix Attribute update method when using buffer props, add unit tests.
- Fix website build.
- Fix Attribute update method when using buffer props.
=> Attribute: fix update for buffer case.

website/src/mdRoutes.js, website/src/styles/_variables.scss, website/src/styles/index.scss
This PR brings typography using the ocular web site closer to the existing site by using clan web pro.
It also fixes a TOC issue as the route file had a typo which caused a crash on a certain page.
=> fix typography

docs/whats-new.md
=> Update whats new

docs/api-reference/webgl/framebuffer.md, docs/api-reference/webgl/texture-2d.md, modules/core/src/webgl-utils/format-utils.js, modules/core/src/webgl/texture.js, test/modules/core/webgl/framebuffer.spec.js, test/modules/core/webgl/texture.spec.js
For #671 
Update texture format table with float formats.
Update utility methods.
Add and update `Texture` and `Framebuffer` unit tests.
Add comments for formats that are failing under.
- Add float textures support, update unit tests
=> Add float textures support, update unit tests

dev-docs/roadmaps/effects-lighting-materials-roadmap.md, docs/api-reference/multipass/clear-pass.md, docs/api-reference/multipass/composite-pass.md, docs/api-reference/multipass/copy-pass.md, docs/api-reference/multipass/pass.md, docs/api-reference/multipass/picking-pass.md, docs/api-reference/multipass/render-pass.md, docs/developer-guide/multipass/README.md, modules/core/src/multipass/clear-mask-pass.js, modules/core/src/multipass/clear-pass.js, modules/core/src/multipass/composite-pass.js, modules/core/src/multipass/copy-pass.js, modules/core/src/multipass/mask-pass.js, modules/core/src/multipass/multi-pass-renderer.js, modules/core/src/multipass/pass.js, modules/core/src/multipass/picking-pass.js, modules/core/src/multipass/render-pass.js, modules/core/src/multipass/render-state.js, modules/core/src/multipass/stencil-pass.js, modules/core/src/multipass/texture-pass.js
=> Multipass docs

modules/core/package.json, modules/core/src/webgl/program.js, modules/core/src/webgl/vertex-array.js, yarn.lock
For #688 
- Fix constant buffer generation
=> Safari fixes

website/src/mdRoutes.js, website/src/react-demos-require.js
For #688 
- Add Transform demo link to website.
=> Add Transform demo link to Website demos

modules/core/package.json
=> Disable `sideEffects` field to fix minified builds

modules/loaders.gl/src/glb-loader/glb-parser.js, modules/loaders.gl/src/gltf-loader/gltf-config-luma.js, modules/loaders.gl/src/gltf-loader/gltf-config.js, modules/loaders.gl/src/gltf-loader/gltf-loader.js, modules/loaders.gl/src/gltf-loader/gltf-parser.js, modules/loaders.gl/src/index.js, test/modules/loaders.gl/gltf-loader/gltf-loader.spec.js, test/modules/loaders.gl/index.js
For #702 
- Add basic `GLTFParser` class with simple index resolution support
- Add test infrastructure and plumb in test data
=> Initial GLTFParser

docs/FAQ.md, docs/api-reference/core/model.md, website-old/contents/pages.js, website-old/src/utils/page-path-utils.js
For #688 
Add links to FAQ and loader docs to `website-old` (non-ocular) contents.
- Add loader, FAQ doc links to website-old.
=> Add loader, Faq links to website-old

docs/api-reference/multipass/canvas.md, docs/api-reference/multipass/shader-module-pass.md, docs/developer-guide/multipass/README.md, docs/whats-new.md, modules/core/src/core/animation-loop.js, modules/core/src/index.js, modules/core/src/multipass/canvas.js, modules/core/src/multipass/multi-pass-renderer.js, modules/core/src/multipass/pass.js, modules/core/src/multipass/shader-module-pass.js, modules/core/src/shadertools/src/lib/filters/normalize-module.js, modules/core/src/shadertools/src/lib/filters/prop-types.js, modules/core/src/shadertools/src/lib/filters/shader-pass.js, modules/core/src/webgl-context/create-canvas.js, modules/core/src/webgl-context/index.js, modules/core/src/webgl/framebuffer.js, modules/script/.babelrc, modules/script/README.md, modules/script/package.json, modules/script/src/index.js, modules/script/test/index.html, modules/script/test/index.js, modules/script/webpack.config.js, test/modules/core/webgl/texture-2d.spec.js, yarn.lock
- Add `ShaderModulePass` class
- Add `Canvas` class
-
=> ShaderModulePass

modules/core/src/webgl-context/context.js
- Choose different variable name (not `gl`) to avoid inlining.
=> Fix isWebGL2 (defeat GL constant inlining)

.gitignore, lerna.json, modules/core/package.json, modules/loaders.gl/package.json, package.json, scripts/bootstrap.sh, yarn.lock
- Maintain one copy of dev dependencies and dev scripts
- Use lerna to manage internal dependencies
- Set up lerna for core and loader.gl modules
- Remove unused scripts
=> Set up lerna

examples/wip/debugger/app.js, examples/wip/debugger/package.json, examples/wip/debugger/webpack.config.js, modules/debug/src/index.js
- Showcase debug on top of the core/cubemap example. Code changes are noted inline.
=> Add debug example

test/browser.js
For #
Fix `run test browser`, so it will complete when test is done.
- Fix browser script
=> Fix browser script

modules/core/src/shadertools/src/index.js, modules/core/src/shadertools/src/lib/inject-shader.js, modules/core/src/shadertools/src/utils/shader-utils.js, modules/core/src/shadertools/test/index.js, modules/core/src/shadertools/test/lib/inject-shader.spec.js, modules/core/src/shadertools/test/utils/shader-utils.spec.js, modules/core/src/webgl-utils/index.js, modules/core/src/webgl-utils/texture-utils.js, modules/core/src/webgl/framebuffer.js, test/modules/core/webgl-utils/index.js, test/modules/core/webgl-utils/texture-utils.spec.js
For #671
Set of shader/texture utility methods needed for Transform texture support.
- Part-1: Transform texture support: add shader and texture utility methods
=> Part-1: Transform texture support: add shader and texture utility methods

dev-docs/RFCs/README.md, examples/glfx/index.html, examples/glfx/package.json, examples/pbr/controls.js, examples/pbr/index.html, examples/pbr/main.js, examples/pbr/mesh.js, examples/pbr/package.json, examples/pbr/scene.js, examples/pbr/style.css, modules/core/package.json, modules/core/src/debug.js, modules/core/src/index.js, modules/core/src/shadertools/src/modules/pbr/README.md, modules/core/src/shadertools/src/modules/pbr/pbr-fragment.glsl.js, modules/core/src/shadertools/src/modules/pbr/pbr-vertex.glsl.js, modules/core/src/shadertools/src/modules/pbr/pbr.js, modules/core/src/shadertools/src/modules/project2/README.md, modules/core/src/shadertools/src/modules/project2/project2.js, modules/core/src/shadertools/src/modules/project2/project2.vertex.glsl.js, modules/core/src/webgl/texture.js, modules/gpgpu/diff-images.js, modules/gpgpu/index.js, modules/script/.babelrc, modules/script/package.json, modules/script/src/index.js, package.json, yarn.lock
For #702 
- Port Khronos PBR reference example to luma.gl
- New example
=> Port of Khronos PBR reference example

docs/api-reference/core/transform.md, modules/core/src/core/transform-shader-utils.js, modules/core/src/core/transform.js, modules/core/src/shadertools/src/index.js, modules/core/src/shadertools/src/modules/transform/transform.js, test/modules/core/core/transform.spec.js
For #671 
Add source and destination texture support for Transform.
Update the docs with new features and use cases, marked as experimental for now.
Add unit tests.
- Part- 2 Transform: Texture support: add source destination texture support
=> Part- 2 Transform: Texture support: add source destination texture support

modules/core/src/core/transform.js
For #671
Fix an earlier TODO item, use parameters for viewport setting.
Pass all options of Transform.run() to Model.draw() method.
- Transform: use parameters for viewport
=> Transform: use parameters for viewport

docs/api-reference/webgl/buffer.md, docs/whats-new.md, modules/core/src/core/transform.js, test/modules/core/core/transform.spec.js
For #671
- Add whats new section for Transform Texture support.
- Bug fixes found while updating wind-demo to use this API.
- Add unit tests for `offline rendering` use case.
- Transform: Add whats new and some fixes.
=> Transform: Add whats new and some fixes.

examples/core/transform-feedback/app.js, examples/core/transform/app.js, website/src/react-demo-runner.js
For #743
For WebGL2 only demos: (Transform and Transform-feedback examples)
Remove `webgl1: false` to avoid app crash.
When running on webstie: add message to canvas
Standalone app: Add a useful log to console.
- Add helpful string on canvas, for WebGL2 only demos
=> Add helpful string on canvas, for WebGL2 only demos

modules/core/src/webgl/vertex-array-object.js
For #745 
- Apply attribute-0 WA to mobile browsers
=> Apply attribute-0 WA to mobile browsers

docs/whats-new.md
For #710 
Add gifs for whats-new.
-
=> Add gifs for 6.2 whats-new

website/src/components/demo-runner.js
For #743 
Port #744 to non ocular website code.
- Port PR#744 from ocular website version
=> Port PR#744  from ocular website version

modules/core/src/webgl/program.js, website/webpack.config.js
=> Perf: only set changed uniforms

README.md
For # README.md
- Fixed link for kepler.gl in README.md
=> Fixed link for kepler.gl

examples/glfx/package.json, examples/glfx/webpack.config.js, modules/script/package.json, modules/script/src/index.js
Clean up some dependencies and wrong config
- Clean up dependencies and configs
=> Polish dependencies

examples/core/instancing/app.js, examples/core/picking/app.js
For #780 
- Fix: mouse position variable
=> Fix: mouse position variable

modules/core/src/webgl/program.js, modules/core/src/webgl/uniforms.js
For #775 
When caching Array type uniform, create a copy, otherwise cache copy is updated by the application.
- Cache copy of uniform
=> Cache copy of uniform

modules/core/package.json
=> Fix inline version in published builds

aliases.js, babel.config.js, dev-modules/babel-plugin-remove-glsl-comments/index.js, dev-modules/babel-plugin-remove-glsl-comments/package.json, test/dev-modules/babel-plugin-remove-glsl-comments.spec.js, test/dev-modules/index.js, test/index-webgl-independent-tests.js
- Add babel-plugin-remove-glsl-comments dev module
- Tests
=> Add plugin to strip GLSL comments

modules/core/src/webgl/uniforms.js, test/modules/core/webgl/uniforms.spec.js
For #795
- add shortcut when parsing uniforms
=> add shortcut for uniform parse

examples/wip/texture-display/app.js, examples/wip/texture-display/package.json, examples/wip/texture-display/webpack.config.js, modules/core/src/index.js, modules/core/src/utils/histo-pyramid.js, test/modules/core/utils/histo-pyramid.spec.js, test/modules/core/utils/index.js
For #800 
- Add utility methods for Histopyramid generation based on Transform
- Add unit tests
- Add test app to display a texture (for now in wip, we can either remove or move it later, needed to visualize histopyramid textures)
- Add utility methods for building Histopyramids, test app
=> Add utility methods for Histopyramid generation based on Transform

modules/core/src/utils/histo-pyramid.js
For #800 
Add reference to Histopyramid paper
- Add reference to Histopyramid paper
=> Add reference to Histopyramid paper

modules/core/src/core/transform.js, test/modules/core/core/transform.spec.js
For #813 
- Transform: fix Inject option
=> Transform: fix Inject option

babel.config.js, dev-modules/babel-plugin-inline-gl-constants/README.md, dev-modules/babel-plugin-inline-gl-constants/package.json, dev-modules/babel-plugin-remove-glsl-comments/README.md, dev-modules/babel-plugin-remove-glsl-comments/index.js, dev-modules/babel-plugin-remove-glsl-comments/package.json
- Initial version number
- License/repo fields
- Add README for babel-plugin-remove-glsl-comments
=> Prepare dev modules for publish

modules/core/src/core/animation-loop.js, modules/core/src/index.js, modules/core/src/webgl-context/context.js, modules/debug/src/index.js, modules/debug/src/webgl-api-tracing/webgl-debug-context.js, modules/debug/src/webgl-api-tracing/webgl-debugger.js
For #727 
- Continues the work in #818 
- Move `makeDebugContext`
- Export utils from luma.gl "core".
=> Move makeDebugContext to `@luma.gl/debug`

modules/core/src/webgl-context/context.js
For #
Fix a crash
- Fix a crash
=> Fix a crash

examples/core/instancing/app.js, examples/wip/postprocessing/app.js, website/contents/demos.js, website/src/main.js
For #
Fix website build
- Fix website build
=> Fix website build

docs/api-reference/core/transform.md, docs/api-reference/webgl/transform-feedback.md, modules/core/src/core/transform.js, modules/core/src/webgl/transform-feedback.js, test/modules/core/core/transform.spec.js, test/modules/core/webgl/transform-feedback.spec.js
For #833 
- TransformFeedback: Add offset based unit test
- TransformFeedback: Add offset/size support
- Transform: Add feebackbuffer offset/size offset
=> Transform: Add offset/size support for feedback buffers.

dev-docs/RFCs/v7.0/framebuffer-texture-api-rfc.md, docs/api-reference/webgl/copy-and-blit.md, docs/api-reference/webgl/framebuffer.md, docs/api-reference/webgl/texture.md, docs/upgrade-guide.md, modules/core/src/core/pick-models.js, modules/core/src/core/transform.js, modules/core/src/index.js, modules/core/src/webgl/copy-and-blit.js, modules/core/src/webgl/framebuffer.js, modules/core/src/webgl/texture.js, modules/gpgpu/src/histopyramid/histopyramid.js, test/modules/core/webgl/copy-and-blit.spec.js, test/modules/core/webgl/framebuffer.spec.js, test/modules/core/webgl/texture.spec.js
For #815 
NOTE: breaking API change, corresponding deck.gl changes: https://github.com/uber/deck.gl/pull/2528
- Update copy and blit function and parameter names as per API Audit
- Update upgrade-guide with detailed mapping of old to new parameters for all changed funcitons.
- Update copy-blit funciton names, unify parameter naming in all methods
=> Update copy-blit funciton names, unify parameter naming in all methods.

babel.config.js
For #837
- update babel config file
=> restrict scope of glsl comment remove plugin

aliases.js, modules/core/constants.js, modules/core/headless.js, package.json, test/index-webgl-independent-tests.js, test/modules/constants/constants.spec.js, test/modules/constants/index.js, yarn.lock
For #724
- As much as possible, we want to avoid breaking the old way of importing constants.
- Add test cases for new and deprecated constant import
- Forward constants export to fix test case
=> Fix deprecated constant export

docs/api-reference/core/transform.md, docs/api-reference/webgl/transform-feedback.md, docs/whats-new.md, modules/core/src/webgl/transform-feedback.js, test/modules/core/core/transform.spec.js, test/modules/core/webgl/transform-feedback.spec.js
For #842 
-  Transform: rename buffer params
=> Transform: rename buffer params

dev-modules/babel-plugin-remove-glsl-comments/README.md, dev-modules/babel-plugin-remove-glsl-comments/index.js, test/dev-modules/babel-plugin-inline-gl-constants.spec.js, test/dev-modules/babel-plugin-remove-glsl-comments.spec.js, test/dev-modules/index.js, test/index-webgl-independent-tests.js, test/start.js
For #837 
- Fix glsl-remove-comments plugin when using template literals
- Add tests for dev-modules
=> Add tests for dev-modules; fix glsl-remove-comments bug

docs/api-reference/lighting/ambient-light.md, docs/api-reference/lighting/directional-light.md, docs/api-reference/lighting/point-light.md, docs/api-reference/material/phong-material.md, modules/core/src/lighting/light-source.js, modules/core/src/materials/phong-material.js
For #835
- Docs for new lighting and material classes
=> lighting docs

modules/core/src/io/index.js, modules/core/src/io/load-files.js
- Fix missing export warning
- Fix loadTexture
=> Fix loadTexture util

dev-docs/RFCs/README.md, modules/core/src/webgl-context/debug-context.js, modules/core/src/webgl/accessor.js, modules/core/src/webgl/framebuffer.js, modules/core/src/webgl/texture-formats.js, modules/core/src/webgl/texture.js, modules/debug/src/webgl-api-tracing/webgl-debug-context.js, test/browser.js, test/modules/core/webgl/copy-and-blit.spec.js, test/modules/core/webgl/framebuffer.spec.js
=> Code cleanup, prep for async textures

docs/api-reference/io/README.md, docs/api-reference/webgl/texture-cube.md, docs/api-reference/webgl/texture.md, docs/developer-guide/loading-data.md, docs/upgrade-guide.md, modules/core/src/index.js, modules/core/src/io/browser-load.js, modules/core/src/io/index.js, modules/core/src/webgl/texture-2d.js, modules/main/src/index.js, test/modules/core/webgl/index.js, test/modules/core/webgl/texture.spec.js
- Remove deprecated loader functions that are replaced with loaders.gl
=> Remove deprecated loader functions

docs/README.md, examples/lessons/14/app.js, examples/lessons/15/app.js, modules/core/src/utils/globals.js, modules/core/src/webgl/classes/buffer.js, modules/core/src/webgl/classes/renderbuffer.js, modules/core/src/webgl/classes/texture-cube.js, modules/core/src/webgl/utils/format-utils.js, modules/shadertools/src/index.js, website/ocular-config.js, website/package.json, website/src/components/example-list.jsx, website/src/components/example-runner.jsx
=> Round of website fixes

examples/lessons/13/app.js, modules/core/src/webgl-context/index.js, modules/core/src/webgl/classes/shader.js
Hello there. I was reviewing your project and I found some [alerts on LGTM.com](https://lgtm.com/projects/g/uber/luma.gl/alerts/?mode=tree). I decided to fix a few of them, but I definitely encourage you to check out the remaining alerts.
I know this may not be the type of contribution you normally receive, but I figured I could help clean up the codebase.
(Full disclosure: I'm part of the team behind LGTM.com)
Let me know if you have any questions.
=> Fixed some LGTM alerts

modules/script/src/index.js, modules/shadertools/src/index.js
=> fix pbr module import/export

docs/api-reference/core/animation-loop.md, modules/core/src/core/animation-loop.js, test/modules/core/core/animation-loop.spec.js
=> Add synchronous redraw API to AnimationLoop

modules/shadertools/src/modules/picking/picking.js
For #799 
changes are made at user's request(comments in #799)
- replace blended alpha with object alpha in blending
=> modify blending of highlight color and object color

examples/gltf/app.js, modules/core/src/scenegraph/gltf-instantiator/gltf-instantiator.js, modules/core/src/scenegraph/gltf-instantiator/gltf-material.js, modules/shadertools/src/modules/pbr/pbr-fragment.glsl.js
=> glTF: Add PBR debug options and ability to drag-and-drop GLB files

examples/gltf/app.js, modules/core/src/scenegraph/gltf-instantiator/gltf-material.js, modules/shadertools/src/lib/transpile-shader.js, modules/shadertools/src/modules/pbr/pbr-fragment.glsl.js, test/modules/shadertools/lib/transpile-shader.spec.js
=> glTF: Make PBR work with GLSL 3.0 (WebGL 2.0)

examples/core/instancing/app.js, modules/test-utils/src/index.js, modules/test-utils/src/performance-test-runner.js, package.json, test/perf/index.js, test/perf/performance-test-cases.js, test/render/index.js, test/webpack.config.js
- Add `PerformanceTestRunner` class
Test does not pass in headless mode because software rendering perf is vastly different.
=> [test-utils] Add performance test

docs/api-reference/core/animation-loop.md, docs/upgrade-guide.md, modules/core/src/core/animation-loop.js
A possible solution to easily capturing canvas contents without preserving the drawing buffer.
=> Capturing canvas contents

modules/core/src/materials/phong-material.js
Change default material parameters for new lighting effects
- new material parameters
=> add new default material parameters

docs/api-reference/core/animation-loop-proxy.md, docs/api-reference/core/animation-loop.md, modules/core/src/core/animation-loop-proxy.js, modules/core/src/core/animation-loop.js, modules/core/test/core/animation-loop.spec.js
@rolyatmax - adding async/await seems to just have been a matter of updating the eslint config. Making the resulting code pretty was harder. Feel free to take over this PR if you think you can improve on this.
For #
=> Add firstFrame() method to AnimationLoop

examples/webpack.config.local.js
=> Fix start-local in examples

modules/test-utils/src/performance-test-runner.js
=> Fix perf test

modules/test-utils/src/snapshot-test-runner.js
- Make sure only one `captureAndDiffScreen` operation is going on at any time.
=> Fix bug in SnapshotTestRunner

modules/core/src/core/animation-loop.js
=> Add needsRedraw reasons to waitForRender and toDataURL

dev-docs/RFCs/README.md, dev-docs/RFCs/vNext/dynamic-shader-regeneration-rfc.md, dev-docs/RFCs/vNext/glsl-function-replacement-rfc.md
Mapping the ideas from the binary support RFCs in deck.gl into basic shadertools features
For #
-
=> Shadertools RFCs

.eslintrc, examples/core/3d-texture/app.js, examples/core/dof/app.js, examples/core/instancing/app.js, examples/core/mandelbrot/app.js, modules/core/package.json, package.json, yarn.lock
- Bump probe.gl version
- Update examples to use latest StatsWidget API
- Some eslint fixes
=> New StatsWidget API for examples

modules/shadertools/src/modules/phong-lighting/phong-lighting.glsl.js
=> Remove duplicated lighting uniforms

docs/FAQ.md, docs/api-reference/core/geometries/cone-geometry.md, docs/api-reference/core/geometries/cube-geometry.md, docs/api-reference/core/geometries/cylinder-geometry.md, docs/api-reference/core/geometries/ico-sphere-geometry.md, docs/api-reference/core/geometries/plane-geometry.md, docs/api-reference/core/geometries/sphere-geometry.md, docs/api-reference/core/scenegraph/geometries/cone.md, docs/api-reference/core/scenegraph/geometries/cube.md, docs/api-reference/core/scenegraph/geometries/cylinder.md, docs/api-reference/core/scenegraph/geometries/ico-sphere.md, docs/api-reference/core/scenegraph/geometries/plane.md, docs/api-reference/core/scenegraph/geometries/sphere.md, docs/api-reference/core/transform.md, docs/developer-guide/transform-feedback.md, docs/table-of-contents.json, docs/upgrade-guide.md, docs/whats-new.md, examples/core/transform-feedback/app.js, examples/core/transform/app.js, examples/lessons/02/app.js, modules/webgl/src/classes/shader.js, test/apps/wip/picking/app.js, website/ocular-config.js
=> Doc and example fixes

modules/addons/test/add-events.spec.js, modules/addons/test/index.js, modules/constants/test/constants.spec.js, test/webgl-dependent-tests.js, test/webgl-independent-tests.js
=> WIP: Add some test plumbing for coverage

website/src/components/example-list.jsx
=> Fix transform feedback example

docs/api-reference/core/materials/phong-material.md, modules/core/src/materials/phong-material.js
reduce phong material specular color based on feedback
- lower specular color
=> reduce default phong material specular color

modules/addons/package.json, modules/debug/package.json, modules/effects/package.json, modules/glfx/package.json, modules/gpgpu/package.json, modules/test-utils/package.json
=> Fix overly strict peer dependencies

docs/upgrade-guide.md, docs/whats-new.md
=> A pass on "whats new"

modules/addons/src/webvr/display-animation-loop.js, modules/addons/src/webvr/display.js, modules/addons/src/webvr/vr-display.js, modules/core/src/lib/animation-loop.js
For #
- Prep for making AnimationLoop handle display
-
=> WIP: Make DisplayAnimationLoop smaller

modules/core/src/geometry/geometry.js
=> Vertex count for constant attribute geos with no indices

website/ocular-config.js, website/package.json
For #
- Bump to include ocular fix
=> Fix website

modules/addons/package.json, modules/addons/src/bundle.js, modules/constants/package.json, modules/constants/src/bundle.js, modules/core/package.json, modules/core/src/bundle.js, modules/debug/package.json, modules/debug/src/bundle.js, modules/effects/package.json, modules/effects/src/bundle.js, modules/glfx/package.json, modules/glfx/src/bundle.js, modules/gpgpu/package.json, modules/gpgpu/src/bundle.js, modules/main/src/bundle.js, modules/shadertools/package.json, modules/shadertools/src/bundle.js, modules/test-utils/package.json, modules/test-utils/src/bundle.js, modules/webgl-state-tracker/package.json, modules/webgl-state-tracker/src/bundle.js, modules/webgl/package.json, modules/webgl/src/bundle.js, modules/webgl2-polyfill/package.json, modules/webgl2-polyfill/src/bundle.js, package.json, scripts/bundle.config.js, scripts/metrics.sh, yarn.lock
For #
Allows us to measure code content in each module, pre treeshaking:
```
26K modules/gpgpu/dist/dist.min.js
10K modules/test-utils/dist/dist.min.js
285K modules/core/dist/dist.min.js
16K modules/constants/dist/dist.min.js
96K modules/shadertools/dist/dist.min.js
1.6M modules/addons/dist/dist.min.js
137K modules/webgl/dist/dist.min.js
20K modules/glfx/dist/dist.min.js
30K modules/webgl-state-tracker/dist/dist.min.js
27K modules/effects/dist/dist.min.js
21K modules/webgl2-polyfill/dist/dist.min.js
196K modules/debug/dist/dist.min.js
```
- modules: add src/bundle.js, update module package.json with pre-build targets
- scripts: add bundle config and metrics script
=> Build scripts and add metrics

modules/addons/src/gltf/gltf-scenegraph-loader.js
https://github.com/uber-web/loaders.gl/blob/master/modules/gltf/src/gltf/gltf-loader.js#L15
=> Fix gltf loader

examples/core/texture-3d/app.js, examples/core/transform/app.js, modules/webgl/src/classes/texture.js
For #976
- Fix Safari specific crashes in `Texture 3D` and `GLTF` demos.
- Website: demo fixes
=> Website: demo fixes (Safari)

examples/core/dof/app.js, examples/core/gltf/app.js, examples/core/texture-3d/app.js, examples/core/transform-feedback/app.js, examples/core/transform/app.js, website/src/stylesheets/main.scss
- IE fix for gallery layout
- Fix webgl 2 unsupported text
- Fix gltf controls
=> Website fixes

docs/whats-new.md
For #976 
* Add gifs for gltf and pbr
* Add missing links
* Polish text and formatting
=> Polish Whats New in 7.0 documentation

dev-docs/tech-docs-wip/README-WEBGL.md, docs/api-reference/README.md, docs/api-reference/webgl/texture-2d.md, docs/api-reference/webgl/texture.md, docs/get-started/README.md, docs/upgrade-guide.md, docs/whats-new.md, website/contents/pages.js
For #976 
Website: fix links, remove references to Sampler and Texture2DArray
- Website: fix links, remove references to Sampler and Texture2DArray
=> Website: fix links, remove references to Sampler and Texture2DArray

website/webpack.config.js
=> Webpack rule to transpile draco3d

dev-docs/RFCs/v7.1/animation-timeline-rfc.md
RFC for a timeline management system
=> Animation timeline RFC

modules/addons/src/webvr/vr-display.js
=> Check for navigator before accessing

README.md
Migrate build badge from travis-ci.org to travis-ci.com
Replace broken starveller badge with coveralls badge
=> Migrate from travis-ci.org to travis-ci.com

dev-docs/RFCs/v7.1/animation-timeline-rfc.md, dev-docs/RFCs/v7.1/shader-module-injection-rfc.md
=> Shader Module Injection RFC

dev-docs/RFCs/v7.1/effects-module-rfc.md
#1105
For better effect modules organization and management, here is the RFC for a new effects lib
- RFC
=> effects module RFC

docs/table-of-contents.json
Remove out of date entries and cleanup formatting in table of contents config for ocular-gatsby site.
=> Fix table of contents for ocular-gatsby site

modules/core/src/lib/transform.js, modules/core/test/lib/model.spec.js
For #
Use `accessor` prop to specify `size` when creating `Buffer`.
- Fix deprecated Buffer API usage
=> Fix deprecated Buffer API usage

website-gatsby/package.json, website-gatsby/src/components/animation-loop-runner.jsx, website-gatsby/templates/core/example-cubemap.jsx, website-gatsby/templates/core/example-dof.jsx, website-gatsby/templates/core/example-fragment.jsx, website-gatsby/templates/core/example-gltf.jsx, website-gatsby/templates/core/example-instancing.jsx, website-gatsby/templates/core/example-mandelbrot.jsx, website-gatsby/templates/core/example-persistence.jsx, website-gatsby/templates/core/example-quasicrystals.jsx, website-gatsby/templates/core/example-shadowmap.jsx, website-gatsby/templates/core/example-texture-3d.jsx, website-gatsby/templates/core/example-transform-feedback.jsx, website-gatsby/templates/core/example-transform.jsx, website-gatsby/templates/lessons/example-01.jsx, website-gatsby/templates/lessons/example-02.jsx, website-gatsby/templates/lessons/example-03.jsx, website-gatsby/templates/lessons/example-04.jsx, website-gatsby/templates/lessons/example-05.jsx, website-gatsby/templates/lessons/example-06.jsx, website-gatsby/templates/lessons/example-07.jsx, website-gatsby/templates/lessons/example-08.jsx, website-gatsby/templates/lessons/example-09.jsx, website-gatsby/templates/lessons/example-10.jsx, website-gatsby/templates/lessons/example-11.jsx, website-gatsby/templates/lessons/example-12.jsx, website-gatsby/templates/lessons/example-13.jsx, website-gatsby/templates/lessons/example-14.jsx, website-gatsby/templates/lessons/example-15.jsx, website-gatsby/templates/lessons/example-16.jsx
=> Fix image loading paths in gatsby website examples

CHANGELOG.md, docs/api-reference/addons/animation/key-frames.md, docs/api-reference/shadertools/assemble-shaders.md, docs/whats-new.md, modules/core/src/lib/animation-loop.js
=> Documentation for v7.1

modules/effects/test/adjust-filters/brightnesscontrast.spec.js, modules/effects/test/adjust-filters/denoise.spec.js, modules/effects/test/adjust-filters/huesaturation.spec.js, modules/effects/test/adjust-filters/index.js, modules/effects/test/adjust-filters/noise.spec.js, modules/effects/test/adjust-filters/sepia.spec.js, modules/effects/test/adjust-filters/vibrance.spec.js, modules/effects/test/adjust-filters/vignette.spec.js, modules/effects/test/blur-filters/index.js, modules/effects/test/blur-filters/tiltshift.spec.js, modules/effects/test/blur-filters/triangleblur.spec.js, modules/effects/test/blur-filters/zoomblur.spec.js, modules/effects/test/fun-filters/colorhalftone.spec.js, modules/effects/test/fun-filters/dotscreen.spec.js, modules/effects/test/fun-filters/edgework.spec.js, modules/effects/test/fun-filters/hexagonalpixelate.spec.js, modules/effects/test/fun-filters/index.js, modules/effects/test/fun-filters/ink.spec.js, modules/effects/test/index.js, modules/effects/test/utils/index.js, modules/effects/test/utils/random.spec.js, modules/effects/test/warp-filters/bulgepinch.spec.js, modules/effects/test/warp-filters/index.js, modules/effects/test/warp-filters/swirl.spec.js, modules/effects/test/warp-filters/warp.spec.js
=> unit tests for @luma.gl/effects

docs/whats-new.md
=> Pare down what's new

examples/core/gltf/app.js
Safari doesn't support `onpointerdown`/`onpointermove`
=> Fix mouse controls for gltf example on safari

docs/api-reference/webgl/context/get-features.md, docs/api-reference/webgl/context/has-features.md, website/contents/pages.js
For #1136
- fix several missing pages
- fix doc bad link warnings
=> 7.1-release website fix

examples/core/transform/app.js, examples/lessons/16/app.js, modules/webgl/src/classes/vertex-array.js
For #1136 
- Fix deprecated API usage.
- Fix texture setup in lesson 16.
- Fix deprecation and texture in lesson 16
=> Fix deprecation and texture in lesson 16

docs/whats-new.md
Fix what's new typos and links.
=> What's new fixes

modules/webgl/src/webgl-utils/webgl-types.js, yarn.lock
Ugly but non-breaking fix to the issue brought up in #1094
Temporary fix until 8.0 when we can make a breaking change and remove headless context creation.
=> Ugly hack to fix headless.gl depency issue without breakages

.nycrc, package.json, yarn.lock
=> Upgrade ocular-dev-tools

modules/shadertools/src/lib/assemble-shaders.js, modules/shadertools/src/lib/inject-shader.js, modules/shadertools/test/lib/inject-shader.spec.js
Ensure that declarations are injected before module functions. Fixes #1151
=> Fix injected declarations

dev-docs/RFCs/v5.2/enhanced-transform-feedback-api-rfc.md, dev-docs/RFCs/v6.2/transform-float-textures-rfc.md
For #
Update status of implemented RFC
-
=> Update status of implemented RFC

dev-modules/babel-plugin-inline-webgl-constants/index.js, dev-modules/babel-plugin-remove-glsl-comments/index.js, dev-modules/eslint-plugin-luma-gl-custom-rules/check-log-call.js, dev-modules/eslint-plugin-luma-gl-custom-rules/index.js, test/dev-modules.js, test/dev-modules/babel-plugin-inline-gl-constants.spec.js, test/dev-modules/babel-plugin-remove-glsl-comments.spec.js, test/dev-modules/eslint-plugin-luma-gl-custom-rules.spec.js, test/dev-modules/index.js
- Prevent babel plugin tests from picking up root config
- Add tests for custom lint rule
- Add fixer to custom lint rule
=> Improve dev-modules test coverage

modules/core/src/lib/model.js, modules/core/src/scenegraph/nodes/group-node.js, modules/core/src/scenegraph/nodes/scenegraph-node.js, modules/core/test/scenegraph/index.js, modules/core/test/scenegraph/nodes/camera-node.spec.js, modules/core/test/scenegraph/nodes/group-node.spec.js, modules/core/test/scenegraph/nodes/model-node.spec.js, modules/core/test/scenegraph/nodes/scenegraph-node.spec.js, modules/core/test/webgl-independent-tests.js, modules/webgl/test/utils/format-value.spec.js, modules/webgl/test/utils/index.js
For #
Improve coverage for Core Module:
Add unit tests for:
- 'GroupNode`
- `SceneGraphNode`
- `CameraNode`
- `ModelNode`
- `format-value` utility methods.
.. in the process found and fixed following issues:
- `Model`: Fix a crash, use default `props` object
- `GroupNode` : Fix child node check, to make sure all children are `ScenegraphNode` instances
- `SceneGraphNode` : Fix a crash, use default `props` object
- `SceneGraphNode` : Comment out un-used code
- `SceneGraphNode` : Fix `setRotation` method.
-
=> Add unit tests for all Scenegraph classes

modules/core/src/multipass/clear-pass.js, modules/core/src/multipass/composite-pass.js, modules/core/src/multipass/mask-pass.js, modules/core/src/multipass/multi-pass-renderer.js, modules/core/src/multipass/pass.js, modules/core/src/multipass/shader-module-pass.js, modules/core/src/multipass/stencil-pass.js, modules/core/test/lib/index.js, modules/core/test/lib/transform-shader-utils.spec.js, modules/core/test/multipass/clear-mask-pass.spec.js, modules/core/test/multipass/clear-pass.spec.js, modules/core/test/multipass/composite-pass.spec.js, modules/core/test/multipass/copy-pass.spec.js, modules/core/test/multipass/index.js, modules/core/test/multipass/mask-pass.spec.js, modules/core/test/multipass/multi-pass-render.spec.js, modules/core/test/multipass/pass.spec.js, modules/core/test/multipass/render-pass.spec.js, modules/core/test/multipass/shader-module-pass.spec.js, modules/core/test/multipass/stencil-pass.spec.js, modules/core/test/multipass/texture-pass.spec.js, modules/core/test/webgl-dependent-tests.js, modules/effects/src/shader-modules/fun-filters/edgework.js
For #
Increase unit test coverage for `core` module, make minor fixes and created a tracker [issue](https://github.com/uber/luma.gl/issues/1175) for further investigation.
- Core: Add unit tests (transfrom utils and multipass)
=> Core: Add unit tests (transfromutils and multipass)

website/src/components/home.js
For #1178 
Was touring the site and showing luma.gl to my teammates and found a broken link on the main page
- Fixed "Get Started" broken link
=> Fixed Broken Link

docs/api-reference/core/transform.md, modules/core/src/lib/transform.js, modules/core/test/lib/transform.spec.js, test/apps/wip/texture-display/app.js, test/apps/wip/texture-display/webpack.config.js
Fixes #1181
- Add support for custom Fragment shader to Transform. (Experimental API)
- Fix a bug in clear path.
- Transform : Texture API Changes (custom FS and fix clear)
=> Transform : Texture API Changes (custom FS and fix clear)

modules/core/src/lib/animation-loop.js, modules/core/test/lib/animation-loop.spec.js
- Fix crash when `gl.canvas` is undefined
=> Allow animation loop to run with headless gl

modules/core/src/lib/base-model.js, modules/core/src/lib/model-utils.js, modules/core/src/lib/model.js, modules/core/test/lib/model.spec.js
- Remove duplicate code between `BaseModel` and `Model` classes
- Clean up unreachable code
- Unit tests
=> Clean up model classes

modules/core/src/lib/transform.js, modules/core/test/lib/transform.spec.js
For #
- Fix a `Texture2D` resource leak, found while working on [issue](https://github.com/uber/deck.gl/issues/2)
- Add unit tests
- Transform: fix resource leak
=> Transform: fix resource leak

modules/core/package.json, modules/webgl-state-tracker/package.json, modules/webgl/package.json, modules/webgl/src/index.js
The only package that is not side-effect free is `webgl2-polyfill`.
=> Add sideEffects fields to package.json

examples/core/animation/package.json, examples/core/cubemap/package.json, examples/core/dof/package.json, examples/core/fragment/package.json, examples/core/gltf/package.json, examples/core/instancing/package.json, examples/core/mandelbrot/package.json, examples/core/persistence/package.json, examples/core/quasicrystals/package.json, examples/core/shadowmap/package.json, examples/core/texture-3d/package.json, examples/core/transform-feedback/package.json, examples/core/transform/package.json, examples/lessons/01/package.json, examples/lessons/02/package.json, examples/lessons/03/package.json, examples/lessons/04/package.json, examples/lessons/05/package.json, examples/lessons/06/package.json, examples/lessons/07/package.json, examples/lessons/08/package.json, examples/lessons/09/package.json, examples/lessons/10/package.json, examples/lessons/11/package.json, examples/lessons/12/package.json, examples/lessons/13/package.json, examples/lessons/14/package.json, examples/lessons/15/package.json, examples/lessons/16/package.json
For #1190
Bump luma version in all examples.
-  Bump luma version in examples
=> Bump version in examples

docs/README.md
For #1190 
- Docs: update release badges
=> Docs: update release badges

docs/README.md, docs/get-started/examples.md, docs/whats-new.md, website/contents/pages.js
For #1190 
Doc: update urls to point to 7.2-release branch
- Doc: update urls to point to 7.2-release branch
=> Doc: update urls to point to 7.2-release branch

modules/core/src/multipass/composite-pass.js, modules/core/src/multipass/copy-pass.js, modules/core/src/multipass/multi-pass-renderer.js, modules/core/src/multipass/pass.js, modules/core/src/multipass/render-state.js, modules/core/src/multipass/texture-pass.js, modules/core/test/multipass/copy-pass.spec.js, modules/core/test/multipass/multi-pass-render.spec.js, modules/core/test/multipass/texture-pass.spec.js, modules/webgl/src/classes/framebuffer.js, test/setup/index.js, test/setup/resource-tracker.js
Fixes #1201 
- Fix resource leaks in `Frameubffer` class
- Fix resource leaks in `multipass` classes
- Fix resource leaks in Framebuffer and multipass classes
=> Fix resource leaks in Framebuffer and multipass classes

docs/api-reference/core/resource-management/program-manager.md, modules/core/src/lib/base-model.js, modules/core/src/resource-management/program-manager.js
Simpler to do it in `BaseModel`
=> Remove program diffing from program manager

dev-docs/RFCs/v7.3/transform-refactor-rfc.md
For #1193
Adding RFC for `Transform` class refactor.
- RFC: Transform Refactor
=> RFC: Transform Refactor

modules/core/src/lib/base-model.js, modules/core/src/resource-management/program-manager.js, modules/core/test/lib/model.spec.js, modules/core/test/lib/program-manager.spec.js, modules/shadertools/src/index.js, modules/shadertools/src/lib/assemble-shaders.js, modules/shadertools/test/lib/assemble-shaders.spec.js
- BaseModel: avoid program manager hash checks when not necessary
- Default program manager
=> Program manager updates

package.json
=> Updated examples link in npm start command

modules/webgl/src/classes/vertex-array-object.js, modules/webgl/src/classes/vertex-array.js, modules/webgl/test/classes/vertex-array.spec.js
Address remaining details in #1238 and add unit tests.
=> Cleanup VAO fix and test

docs/upgrade-guide.md, docs/whats-new.md
=> What's new and upgrade guide

modules/core/package.json, modules/test-utils/package.json, modules/webgl/package.json, yarn.lock
=> Bump probe.gl version

modules/core/test/lib/transform.spec.js
For #
Add a new test case to , read from multiple `Buffer` objects and generate a single 1X1 `Texture`.
-
=> Transform: add test case for Buffer to Texture use case.

website-gatsby/gatsby-ssr.js
For #756  
Fixes layout issue when opening non top-level page.
=> Add missing gatsby_ssr.js config, fixes layout issue

docs/table-of-contents.json
For #
Website: add missing files to gatsby version
-
=> Website: add missing files to gatsby version

modules/core/src/resource-management/program-manager.js, modules/core/test/lib/program-manager.spec.js
Very unlikely we would ever hit this, but better safe than sorry...
=> Fix hashing of injects

examples/core/transform/package.json, modules/core/package.json, modules/test-utils/package.json, modules/webgl/package.json, package.json, website-gatsby/package.json, website/package.json, yarn.lock
Metrics tracking is currently broken
=> Bump to latest probe version

dev-docs/RFCs/v8.0/luma-refactor.md
=> Refactor RFC

modules/webgl/src/classes/framebuffer.js, modules/webgl/src/features/features.js, modules/webgl/src/features/webgl-features-table.js, modules/webgl/test/features/features.spec.js
For #1258 
More details in above issue.
-
=> WebGL Features: add caching

dev-docs/RFCs/v8.0/luma-refactor.md
Based on feedback from audit meeting.
=> Update RFC and change status to approved

CHANGELOG.md, docs/api-reference/engine/program-manager.md, docs/api-reference/shadertools/assemble-shaders.md, docs/developer-guide/shader-modules.md, docs/upgrade-guide.md, examples/api/program-management/app.js, examples/showcase/instancing/app.js, lerna.json, modules/addons/package.json, modules/constants/package.json, modules/core/package.json, modules/debug/package.json, modules/engine/package.json, modules/engine/src/lib/program-manager.js, modules/engine/test/lib/program-manager.spec.js, modules/gltools/package.json, modules/shadertools/package.json, modules/shadertools/src/lib/assemble-shaders.js, modules/shadertools/src/lib/shader-module.js, modules/shadertools/test/lib/assemble-shaders.spec.js, modules/test-utils/package.json, modules/webgl/package.json
Remove `Program.addModuleInjection` method and allow modules to have an `inject` field.
Has to go in after #1299
=> New module injection api

docs/table-of-contents.json, examples/getting-started/hello-instancing-low/app.js, examples/showcase/geospatial/app.js, examples/showcase/transform/app.js, modules/experimental/src/gpgpu/histopyramid/histopyramid.js, website/gatsby-browser.js, website/gatsby-config.js, website/gatsby-node.js, website/gatsby-ssr.js, website/ocular-config.js, website/package.json, website/src/components/animation-loop-example-page.jsx, website/src/components/info-panel.jsx, website/templates/index.jsx
@tsherif this seemed to work well in my testing, but recommend giving it a thorough test as this is the most complicated webpage done with the new theme setup so far.
=> website: Adopt gatsby-theme-ocular. Fix missing ToC entries.

docs/getting-started/external-context.md, docs/getting-started/shader-hooks.md, docs/getting-started/shader-modules-low.md, docs/getting-started/transform-feedback.md, docs/table-of-contents.json, examples/getting-started/external-context/app.js, examples/getting-started/external-context/package.json, examples/getting-started/external-context/webpack.config.js, website/ocular-config.js, website/templates/getting-started/example-external-context.jsx
Tutorial/example of using an externally-created context with luma.gl. Also cleaned up some formatting in the tutorial docs.
=> External context tutorial

docs/api-reference/debug.md, docs/api-reference/engine/animation-loop.md, docs/api-reference/engine/animation/timeline.md, docs/api-reference/engine/geometries.md, docs/api-reference/engine/model.md, docs/api-reference/experimental/scenegraph/group-node.md, docs/api-reference/gltools/context.md, docs/api-reference/gltools/device-pixels.md, docs/api-reference/webgl/context/feature-checking.md, docs/api-reference/webgl/framebuffer.md, docs/api-reference/webgl/program.md, docs/api-reference/webgl/renderbuffer.md, docs/api-reference/webgl/texture-2d.md, docs/api-reference/webgl/texture-3d.md, docs/api-reference/webgl/texture-cube.md, docs/api-reference/webgl/texture.md, docs/api-reference/webgl/transform-feedback.md, docs/api-reference/webgl/uniform-buffer-layout.md, docs/api-reference/webgl/vertex-array-object.md, docs/developer-guide/accessors.md, docs/developer-guide/debugging.md, docs/developer-guide/shader-modules.md, docs/getting-started/hello-instancing-high.md, docs/getting-started/hello-instancing-mid.md, docs/getting-started/hello-triangle.md, docs/getting-started/shader-hooks.md, docs/getting-started/shader-modules.md, docs/upgrade-guide.md, docs/whats-new.md
Fix internal doc links to work with ocular-gatsby.
=> Fix doc links

docs/README.md, docs/getting-started/hello-cube.md, docs/getting-started/whats-next.md, examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/program-management/package.json, examples/api/texture-3d/package.json, examples/getting-started/external-context/package.json, examples/getting-started/hello-cube/package.json, examples/getting-started/hello-instancing-high/package.json, examples/getting-started/hello-instancing-low/package.json, examples/getting-started/hello-instancing-mid/package.json, examples/getting-started/hello-triangle/package.json, examples/getting-started/instanced-transform/package.json, examples/getting-started/lighting/package.json, examples/getting-started/shader-hooks/package.json, examples/getting-started/shader-modules-low/package.json, examples/getting-started/shader-modules/package.json, examples/getting-started/transform-feedback/package.json, examples/performance/stress-test/package.json, examples/showcase/dof/package.json, examples/showcase/geospatial/package.json, examples/showcase/gltf/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, examples/showcase/wandering/package.json, scripts/update-release-branch.sh, website/ocular-config.js, website/src/components/animation-loop-example-page.jsx
=> Update website links to 8.0

website/package.json
=> Fix gltf website deps

examples/api/texture-3d/app.js, examples/getting-started/hello-instancing-low/app.js, examples/getting-started/instanced-transform/app.js, examples/getting-started/transform-feedback/app.js, examples/performance/stress-test/app.js, examples/showcase/dof/app.js, examples/showcase/wandering/app.js, examples/utils/index.js, website/src/components/animation-loop-example-page.jsx
The fact that `AnimationLoop.start` is asynchronous is a headache...
=> Fix not supported messages for examples

examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/program-management/package.json, examples/api/texture-3d/package.json, examples/getting-started/hello-cube/package.json, examples/getting-started/instanced-transform/package.json, examples/getting-started/lighting/package.json, examples/performance/stress-test/package.json, examples/showcase/dof/package.json, examples/showcase/gltf/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, modules/debug/package.json, modules/engine/package.json, modules/experimental/package.json, modules/shadertools/package.json, package.json, website/package.json, yarn.lock
=> Update math.gl, loaders.gl to latest

dev-modules/babel-plugin-inline-webgl-constants/package.json
Update @luma.gl/constants dependency
=> babel-plugin-inline-webgl-constants@1.0.2

modules/engine/src/lib/animation-loop.js
For https://github.com/uber/deck.gl/issues/4174
=> Fix overwriting of page load promise

docs/api-reference/engine/model.md, docs/api-reference/engine/program-manager.md, docs/api-reference/shadertools/assemble-shaders.md, modules/engine/src/lib/model.js, modules/engine/src/lib/program-manager.js, modules/engine/test/lib/model.spec.js, modules/engine/test/lib/program-manager.spec.js, modules/shadertools/src/lib/assemble-shaders.js, modules/shadertools/src/lib/transpile-shader.js, modules/shadertools/test/lib/assemble-shaders.spec.js, modules/shadertools/test/lib/transpile-shader.spec.js
- Make transpilation of attributes more conservative (avoid transforming in/out function args or #defines).
- Change parameter name to `transpileToGLSL100`
- Update docs
=> Fix transpilation

modules/experimental/src/gltf/gltf-material-parser.js
=> Only use texture LOD in GLTF if supported.

modules/webgl/src/classes/buffer.js, modules/webgl/test/classes/buffer.spec.js
=> Allow size and offset to be set when constructing buffer

modules/engine/src/lib/model.js, modules/webgl/src/classes/program.js
=> Fix model and program logging

dev-docs/RFCs/v8.1/gpu-accelerated-polygon-clipping.md
=> RFC: GPU Accelerated Polygon Clipping

CHANGELOG.md, docs/whats-new.md
=> Doc updates

modules/shadertools/src/lib/assemble-shaders.js, modules/shadertools/test/lib/assemble-shaders.spec.js
The system of trying to lift all variables to the top of a shader was brittle and unnecessary. It turns out our use cases only require injected variables to be available to other functions.
=> Limit shader variable hoisting to injected declararions

docs/README.md, examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/program-management/package.json, examples/api/texture-3d/package.json, examples/getting-started/external-context/package.json, examples/getting-started/hello-cube/package.json, examples/getting-started/hello-instancing-high/package.json, examples/getting-started/hello-instancing-low/package.json, examples/getting-started/hello-instancing-mid/package.json, examples/getting-started/hello-triangle/package.json, examples/getting-started/instanced-transform/package.json, examples/getting-started/lighting/package.json, examples/getting-started/shader-hooks/package.json, examples/getting-started/shader-modules-low/package.json, examples/getting-started/shader-modules/package.json, examples/getting-started/transform-feedback/package.json, examples/performance/stress-test/package.json, examples/showcase/dof/package.json, examples/showcase/geospatial/package.json, examples/showcase/gltf/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, examples/showcase/wandering/package.json, website/src/components/animation-loop-example-page.jsx
May have rushed a bit on the last PR...
=> Fix version numbers in dep/doc links

modules/debug/package.json, modules/experimental/package.json, modules/test-utils/package.json
=> Fix peerDependencies

modules/debug/package.json, modules/engine/package.json, modules/experimental/package.json, modules/shadertools/package.json, package.json, yarn.lock
=> Bump math.gl and loaders.gl

docs/getting-started/shader-modules.md
Fixed another minor mistake in code sample
=> typo in shader-modules.md

modules/experimental/src/gltf/gltf-material-parser.js, modules/shadertools/src/modules/pbr/pbr-fragment.glsl.js
Support for PBR material.unlit flag
For #947 
- https://github.com/visgl/deck.gl/issues/3705
- Added new uniform to PBR module
- Updated logic in PBR shader to support unlit materials
=> Support for PBR material.unlit flag

modules/experimental/test/gltf/gltf.spec.js, modules/shadertools/package.json, modules/shadertools/src/lib/platform-defines.js, modules/shadertools/src/modules/pbr/pbr-fragment.glsl.js, modules/shadertools/test/lib/assemble-shaders.spec.js, package.json, yarn.lock
For #
- Shader compilation of PBR was failing as extension directives were not at beginning of shader source
- A shader compilation test was failing due to some varying issue around `position_commonspace`
- Since test framework was using raw webgl no error messages were produced.
- Refactor the extension handling in PBR module
- Add code to extract error logs for the failing test case.
- Comment out broken test case for now.
=> Fix shader compilation test failures

examples/utils/index.js, modules/webgl/src/classes/buffer.js, modules/webgl/src/classes/framebuffer.d.ts, modules/webgl/src/classes/framebuffer.js, modules/webgl/src/classes/program.js, modules/webgl/src/classes/query.js, modules/webgl/src/classes/renderbuffer-formats.js, modules/webgl/src/classes/resource.d.ts, modules/webgl/src/classes/resource.js, modules/webgl/src/classes/shader.js, modules/webgl/src/classes/texture-cube.d.ts, modules/webgl/src/classes/texture-cube.js, modules/webgl/src/classes/texture.js, modules/webgl/src/classes/transform-feedback.js, modules/webgl/src/classes/uniform-buffer-layout.js, modules/webgl/src/classes/vertex-array-object.d.ts, modules/webgl/src/classes/vertex-array-object.js, modules/webgl/src/classes/vertex-array.d.ts, modules/webgl/src/classes/vertex-array.js, modules/webgl/src/debug/debug-vertex-array.js, modules/webgl/src/glsl-utils/format-glsl-error.js, modules/webgl/src/index.d.ts, modules/webgl/src/types.d.ts, tsconfig.json
=> feat(webgl): typings

modules/engine/src/lib/animation-loop.js
For https://github.com/visgl/deck.gl/issues/5375
Broken by #1433
- Remove unused `_onSetupFrame`
=> Fix AnimationLoop drawing buffer resize

docs/whats-new.md
=> 8.4 what's new

website/gatsby-config.js
The current get started link on the home page link redirects to nothing
- Update the get started link url
=> Update get started link

.nycrc, docs/upgrade-guide.md, modules/constants/package.json, modules/core/package.json, modules/debug/package.json, modules/engine/package.json, modules/experimental/package.json, modules/gltools/package.json, modules/shadertools/package.json, modules/test-utils/package.json, modules/webgl/package.json, package.json, scripts/bundle.config.js, test/index.js, yarn.lock
- Upgrade ocular-dev-tools
- Upgrade puppeteer
- Drop ES6 dist entry point
- Upgrade guide
=> Change build targets

docs/api-reference/shadertools/effects-shader-modules.md, modules/shadertools/src/modules/image-fun-filters/magnify.d.ts, modules/shadertools/src/modules/image-fun-filters/magnify.js, modules/shadertools/src/modules/index.d.ts, modules/shadertools/src/modules/index.js
For #
- Add magnify effect
- a simple magnify effect module to increase/decrease the surrounding area of a given position
=> Shadertools: add magnify effect

examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/program-management/package.json, examples/api/texture-3d/package.json, examples/getting-started/hello-cube/package.json, examples/getting-started/instanced-transform/package.json, examples/getting-started/lighting/package.json, examples/performance/stress-test/package.json, examples/showcase/dof/package.json, examples/showcase/gltf/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, modules/debug/package.json, modules/engine/package.json, modules/experimental/package.json, modules/shadertools/package.json
- Bump to official math.gl 3.5 release
=> bump: math.gl@3.5.0

examples/performance/stress-test/package.json, examples/showcase/gltf/package.json, modules/experimental/package.json, modules/test-utils/package.json, package.json, tsconfig.json, website/package.json, yarn.lock
=> chore: bump loaders.gl and probe.gl

lerna.json
For #
- Move ongoing development to alpha track
-
=> chore: bump lerna.json to 8.6.0-alpha.0

modules/webgl/src/classes/framebuffer.ts, modules/webgl/src/classes/renderbuffer-formats.ts, modules/webgl/src/classes/renderbuffer.ts, modules/webgl/src/classes/shader.ts, yarn.lock
=> chore(webgl): improved typings for Framebuffer, Renderbuffer, Shader

modules/engine/src/lib/animation-loop.js
- Minimal fix for unbreaking website
- Track animationFrameId inside the request/cancel animation frame functions to ensure we don't get into an incorrect state.
=> fix(engine): AnimationLoop request/cancel animation frames

.nycrc, docs/whats-new.md, package.json, yarn.lock
=> chore: Add typescript support to .nycrc

modules/gltools/src/state-tracker/track-context-state.ts, modules/gltools/test/state-tracker/state-tracking/track-context-state.spec.js, yarn.lock
For #1509
- Do not cache unreferenced parameters
- Unit test
=> Fix outdated parameter cache

modules/engine/src/lib/model.ts, modules/webgl/src/api/buffer.ts, modules/webgl/src/api/device.ts, modules/webgl/src/api/resource.ts, modules/webgl/src/api/stats-manager.ts, modules/webgl/src/classes/buffer.ts, modules/webgl/src/classes/framebuffer.ts, modules/webgl/src/classes/program.ts, modules/webgl/src/classes/query.ts, modules/webgl/src/classes/renderbuffer.ts, modules/webgl/src/classes/shader.ts, modules/webgl/src/classes/texture-2d.ts, modules/webgl/src/classes/texture-3d.ts, modules/webgl/src/classes/texture.ts, modules/webgl/src/classes/transform-feedback.ts, modules/webgl/src/classes/vertex-array-object.ts, modules/webgl/src/classes/webgl-resource.ts, modules/webgl/src/context/gl-context.ts, modules/webgl/src/index.ts, modules/webgl/src/init.ts, modules/webgl/test/classes/buffer.spec.js, modules/webgl/test/classes/transform-feedback.spec.js, yarn.lock
=> chore(webgl): WEBGLBuffer now inherits from abstract API (Buffer / Resource)

modules/webgl/src/api/shader.ts, modules/webgl/src/api/texture.ts, modules/webgl/src/classes/texture-3d.ts, modules/webgl/src/classes/texture-cube.ts, modules/webgl/src/classes/texture.ts, modules/webgl/src/classes/webgl-shader.ts, modules/webgl/test/classes/texture-3d.spec.js
=> chore(webgl): Texture inherits from API

.gitignore, modules/constants/tsconfig.json, modules/core/tsconfig.json, modules/debug/src/glsl-to-js-compiler/debug-context.ts, modules/debug/tsconfig.json, modules/engine/tsconfig.json, modules/experimental/src/gltf/create-gltf-model.ts, modules/experimental/src/gltf/create-gltf-objects.ts, modules/experimental/src/gltf/gltf-instantiator.ts, modules/experimental/src/gpgpu/histopyramid/histopyramid.ts, modules/experimental/src/gpgpu/point-in-polygon/polygon.ts, modules/experimental/tsconfig.json, modules/gltools/src/lib/state-tracker/webgl-parameter-tables.ts, modules/gltools/tsconfig.json, modules/shadertools/tsconfig.json, modules/test-utils/tsconfig.json, modules/webgl/tsconfig.json, package.json, scripts/add-js-to-imports.sh, tsconfig.build.json, tsconfig.module.json
For #1402 
- Enables build of d.ts files from source
- Enables incremental transpilation via tsc
- New tsconfigs and build targets
=> feat: TypeScript monorepo setup

modules/api/src/index.ts, modules/engine/src/index.ts, modules/webgl/src/classes/texture.ts, modules/webgl/src/index.ts, website/src/components/animation-loop-example-page.jsx
=> chore: website code cleanup

.github/workflows/test.yml, package.json
=> chore: Run CI on Node 16

modules/debug/package.json, modules/experimental/package.json, modules/test-utils/package.json
=> chore: bump to loaders.gl@3.1.0

modules/experimental/src/gltf/gltf-material-parser.ts, modules/webgl/src/classes/copy-and-blit.ts
=> chore(gltf): Minor typescript improvements

modules/api/src/bundle.ts, modules/experimental/test/gltf/gltf.spec.js, modules/webgl/src/classes/program-configuration.ts, modules/webgl/src/helpers/get-program-bindings.ts, modules/webgl/src/helpers/program-bindings.ts, modules/webgl/src/index.ts, modules/webgl/src/types/accessor.d.ts, modules/webgl/test/helpers/get-program-bindings.spec.js, modules/webgl/test/index.js, tsconfig.json
=> feat(webgl): Platform-independent ProgramConfiguration

LICENSE, docs/getting-started/hello-cube.md, modules/api/test/utils/array-utils-flat.spec.js, modules/api/test/utils/format-value.spec.js, modules/experimental/test/gpgpu/histopyramid.spec.js, modules/shadertools/src/modules/fp64/fp64-arithmetic.glsl.ts, modules/shadertools/src/modules/fp64/fp64-functions.glsl.ts, modules/shadertools/test/modules/fp64/fp64-arithmetic-transform.spec.ts, modules/shadertools/test/modules/fp64/fp64-test-utils-transform.ts, modules/shadertools/test/modules/fp64/test/fp64-arithmetic.spec.js, modules/shadertools/test/modules/fp64/test/fp64-functions.spec.js, modules/shadertools/test/modules/fp64/test/fp64-test-utils.js, test/bench/array-copy.bench.js, test/bench/browser.js, test/bench/index.js, test/bench/point-in-polygon.bench.js, test/bench/shaders.bench.js, test/bench/uniforms.bench.js, test/browser.js, website/templates/index.jsx
For #
- Cleanup the mix of different outdated license statements
- Add UCF to top-level license file
- Change to minimal, one-line license statement in each file
- In docs, talk about vis.gl instead of company specific frameworks.
=> chore: Clean up license comments

modules/api/src/index.ts, modules/api/src/types.ts, modules/shadertools/src/lib/shader-assembler/assemble-shaders.ts, modules/webgl/src/classes/vertex-array-object.ts, modules/webgl/src/classes/vertex-array.ts
=> fix: Minor API type fixes

examples/showcase/gltf/package.json, modules/experimental/package.json, package.json, test/apps/pbr/package.json, website/package.json, yarn.lock
=> chore: Bump to loaders.gl@3.1.1

nyc.config.js
=> chore: exclude `modules/webgpu` from coverage until we have a test setup

examples/webgl/external-webgl-context/app.ts, examples/webgl/hello-instancing-webgl/app.ts, examples/webgl/shader-modules-webgl/app.ts, modules/api/src/index.ts, modules/api/src/types.ts, modules/debug/test/webgl-api-tracing/webgl-debug-context.spec.js, modules/engine/src/animation/timeline.ts, modules/engine/src/geometry/geometry.ts, modules/engine/src/lib/model.ts, modules/engine/src/transform/buffer-transform.ts, modules/engine/src/transform/transform-shader-utils.ts, modules/engine/src/transform/transform-types.ts, modules/engine/test/geometry/geometries.spec.ts, modules/engine/test/geometry/geometry.spec.js, modules/engine/test/geometry/index.js, modules/engine/test/geometry/index.ts, modules/engine/test/lib/model.spec.js, modules/engine/test/transform/buffer-transform.spec.js, modules/engine/test/transform/transform.spec.js, modules/webgl/src/classes/vertex-array.ts, tsconfig.json
=> chore: Remove type check exceptions

.eslintrc.js, babel.config.js, modules/api/README.md, modules/api/src/adapter/types/formats.ts, modules/api/src/adapter/utils/decode-vertex-format.ts, modules/api/src/index.ts, modules/api/src/utils/check-props.ts, modules/api/src/utils/load-file.ts, modules/api/src/utils/stats-manager.ts, modules/api/src/utils/stub-methods.ts, modules/api/test/adapter/utils/decode-vertex-format.spec.ts, modules/api/test/index.js, modules/api/test/wip/uniform-buffer-layout.spec.js
=> chore(api): utils cleanup

docs/developer-guide/debugging.md, docs/whats-new.md, modules/api/src/index.ts, modules/api/src/utils/load-file.ts, modules/engine/test/transform/transform.spec.js, modules/webgl/src/adapter/helpers/spector.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/classes/texture.ts
=> feat(webgl): Add Spector.js integration

modules/api/src/adapter/device.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/helpers/get-program-bindings.ts, modules/webgl/test/classes/texture.spec.js, test/modules.js
For #
- WebGLDevice refactor broke the integration
-
=> feat(debug): Restore WebGL debug integration

examples/api/cubemap/app.ts, modules/api/src/adapter/device.ts, modules/api/src/adapter/resources/texture.ts, modules/api/src/index.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/classes/texture-2d.ts, modules/webgl/src/classes/texture-3d.ts, modules/webgl/src/classes/texture-cube.ts, modules/webgl/src/classes/texture.ts, modules/webgl/src/index.ts, modules/webgl/test/classes/texture.spec.js, modules/webgpu/src/adapter/resources/webgpu-framebuffer.ts, modules/webgpu/src/adapter/resources/webgpu-texture.ts, modules/webgpu/src/adapter/webgpu-device.ts
For #1525 
- Prep to support `device.createTexture({dimension: '2d' | 'cube' | '3d'});`
-
=> feat(webgl): Texture class unification

modules/api/docs/api-reference/resources/sampler.md, modules/webgl/src/adapter/converters/device-parameters.ts, modules/webgl/src/adapter/converters/sampler-parameters.ts
For #1525 
- Polish WebGLSampler code
-
=> feat(webgl): Sampler anisotropy and comparison

modules/api/src/adapter/device.ts, modules/api/src/lib/luma.ts, modules/debug/src/webgl-api-tracing/webgl-debug-context.ts, modules/shadertools/src/lib/shader-assembler/platform-defines.ts, modules/webgl/src/_deprecated/context-api.ts, modules/webgl/src/_deprecated/features.ts, modules/webgl/src/adapter/converters/texture-formats.ts, modules/webgl/src/adapter/device-helpers/device-features.ts, modules/webgl/src/adapter/device-helpers/get-device-info.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/classes/framebuffer.ts, modules/webgl/src/classes/query.ts, modules/webgl/test/adapter/device-helpers/device-features.spec.ts, modules/webgpu/src/adapter/webgpu-device.ts
=> feat(api): Clean up DeviceFeature naming

docs/getting-started/external-context.mdx, docs/getting-started/hello-cube.mdx, docs/getting-started/hello-instancing.mdx, docs/getting-started/hello-triangle.mdx, docs/getting-started/instanced-transform.mdx, docs/getting-started/lighting.mdx, docs/getting-started/shader-hooks.mdx, docs/getting-started/shader-modules.mdx, docs/getting-started/transform.mdx, modules/api/src/adapter/device.ts, modules/api/src/lib/luma.ts, modules/webgl/src/adapter/helpers/spector.ts, modules/webgl/src/adapter/resources/webgl-texture.ts, modules/webgl/src/context/context/create-context.ts, website/src/components/animation-loop-example-page.jsx
For #1525 
- Add inline examples that load textures
-
=> feat(docs): Add inline examples with textures

modules/test-utils/src/create-test-device.ts, modules/test-utils/src/index.ts, modules/webgl/src/webgl-utils/constants-to-keys.ts, modules/webgl/test/adapter/device-helpers/device-info.spec.js, modules/webgl/test/adapter/device-helpers/device-limits.spec.ts, modules/webgpu/src/adapter/webgpu-canvas-context.ts
=> feat(test-utils): Return lists of devices for testing

docs/api-guide/device-properties.mdx, docs/api-guide/texture-formats.mdx, modules/api/src/adapter/device.ts, modules/api/src/adapter/resources/resource.ts, modules/api/src/adapter/utils/decode-texture-format.ts, modules/webgl/src/_deprecated/features.ts, modules/webgl/src/adapter/converters/texture-formats.ts, modules/webgl/src/adapter/device-helpers/device-features.ts, modules/webgl/src/adapter/resources/webgl-texture.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/classes/framebuffer.ts, modules/webgl/test/adapter/device-helpers/device-features.spec.ts, modules/webgl/test/adapter/resources/webgl-texture.spec.ts, modules/webgl/test/classes/copy-and-blit.spec.ts, modules/webgl/test/classes/texture.spec.ts, modules/webgpu/src/adapter/webgpu-device.ts
=> chore(webgl): isolate texture format processing

docs/api-reference/resources/external-texture.md, modules/api/src/adapter/device.ts, modules/api/src/adapter/resources/external-texture.ts, modules/api/src/index.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgpu/src/adapter/resources/webgpu-external-texture.ts, modules/webgpu/src/adapter/webgpu-device.ts
For #1525
- Requires special treatment in WebGPU, first pass API is just "passthrough"
-
=> feat(webgpu): external textures

modules/api/src/adapter/canvas-context.ts, modules/api/src/adapter/resources/framebuffer.ts, modules/api/src/adapter/resources/render-pass.ts, modules/api/src/adapter/resources/render-pipeline.ts, modules/api/test/adapter/canvas-context.spec.ts, modules/engine/src/lib/model.ts, modules/engine/src/lib/program-manager.ts, modules/engine/src/transform/transform.ts, modules/webgl/src/adapter/resources/webgl-framebuffer.ts, modules/webgl/src/adapter/resources/webgl-render-pass.ts, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgl/src/adapter/webgl-canvas-context.ts, modules/webgl/src/classes/program.ts, modules/webgl/test/classes/program.spec.js, modules/webgpu/src/adapter/resources/webgpu-framebuffer.ts, modules/webgpu/src/adapter/resources/webgpu-render-pass.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts, modules/webgpu/src/adapter/webgpu-canvas-context.ts, modules/webgpu/src/adapter/webgpu-device.ts
=> chore(webgl): Program inherits from WEBGLRenderPipeline

modules/webgl/src/adapter/objects/webgl-renderbuffer.ts, modules/webgl/src/adapter/objects/webgl-resource.ts, modules/webgl/src/adapter/objects/webgl-vertex-array-object.ts, modules/webgl/src/adapter/objects/webgl-vertex-array.ts, modules/webgl/src/classes/copy-and-blit.ts, modules/webgl/src/classes/query.ts, modules/webgl/src/classes/renderbuffer.ts, modules/webgl/src/classes/transform-feedback.ts, modules/webgl/src/classes/vertex-array-object.ts, modules/webgl/src/classes/vertex-array.ts, nyc.config.js
=> chore(webgl): Split vertex-array, renderbuffer into webgl and legacy classes

docs/README.md, docs/upgrade-guide.md, docs/whats-new.md, lerna.json
For #1525 
- Bump lerna.json
- Some docs changes
=> chore: Move to v9.0.0-alpha releases

modules/api/src/adapter/canvas-context.ts, modules/api/src/utils/load-file.ts, modules/webgpu/src/adapter/webgpu-canvas-context.ts
=> chore(api): CanvasContext cleanup

modules/debug/src/webgl-api-tracing/khronos-webgl-context-loss.ts, modules/debug/src/webgl-api-tracing/khronos-webgl-error.ts, modules/gltools/test/classic/context/context-api.spec.js, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/context/context/context-state.ts, modules/webgl/src/context/debug/webgl-developer-tools.ts, modules/webgl/src/index.ts
For #1525
- Remove wip/unused code as the new proposed API stabilizes
- Make debug contexts cleaner and more robust
-
=> chore(webgl): WebGLDevice cleanup

.github/workflows/website.yml, modules/experimental/src/gltf/gltf-material-parser.js, test/render/example-test-cases.js
=> Cleanup generated textures

.github/workflows/test.yml, modules/constants/src/bundle.js, modules/debug/src/bundle.js, modules/debug/src/index.js, modules/engine/package.json, modules/engine/src/bundle.js, modules/engine/src/lib/animation-loop.js, modules/experimental/src/bundle.js, modules/gltools/package.json, modules/gltools/src/bundle.js, modules/gltools/src/context/context.js, modules/gltools/src/polyfill/polyfill-context.js, modules/gltools/src/polyfill/polyfill-vertex-array-object.js, modules/gltools/src/state-tracker/track-context-state.js, modules/shadertools/src/bundle.js, modules/test-utils/package.json, modules/test-utils/src/context.js, modules/webgl/package.json, modules/webgl/src/bundle.js, modules/webgl/src/classes/texture.js, modules/webgl/src/init.js, modules/webgl/src/utils/is-old-ie.js, modules/webgl/test/classes/uniforms.spec.js, yarn.lock
For [#](https://github.com/visgl/luma.gl/issues/1642)
- Replace all mentions of `global`
=> Replace global from probe.gl/env with globalThis

modules/experimental/src/index.d.ts, modules/experimental/src/index.js
For deck.gl TypeScript conversion
=> [8.5-release] Export GLTFAnimator

docs/README.md
- Current docs are 8.5, link to 8.1-8.4 as well. Similar to https://github.com/visgl/deck.gl/pull/7348
=> [docs] update doc version badges

modules/webgl/src/classes/resource.js
Do allocate/deallocate only once for different contexts
=> fix(resource): allocate/deallocate memory fix

yarn.lock
=> chore: bump to math.gl@v3.6

examples/showcase/gltf/package.json, modules/experimental/package.json, modules/test-utils/src/create-test-device.ts, package.json, website/package.json, yarn.lock
=> chore: bump to loaders.gl@3.2.12

modules/constants/tsconfig.json, modules/shadertools/src/lib/filters/prop-types.ts, modules/shadertools/src/lib/glsl-utils/get-shader-info.ts, modules/shadertools/src/lib/glsl-utils/shader-utils.ts, modules/shadertools/src/lib/shader-assembler/assemble-shaders.ts, modules/shadertools/src/lib/shader-module/shader-module-instance.ts, modules/shadertools/src/modules/image-adjust-filters/brightnesscontrast.ts, modules/shadertools/src/modules/lights/lights.ts, modules/shadertools/src/modules/picking/picking.ts, modules/shadertools/tsconfig.json
=> chore(shadertools): enable "strict" typescript checking

modules/api/src/adapter/device.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/context/context/create-browser-context.ts, modules/webgl/src/context/debug/webgl-developer-tools.ts, modules/webgl/test/adapter/webgl-device.spec.ts, yarn.lock
=> feat(webgl): Implement WebGPU style `lost` promise for WebGLDevice.

modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts
=> chore(webgl): handle added topologies

.github/workflows/test.yml, modules/engine/package.json, modules/experimental/test/gpgpu/histopyramid.spec.js, modules/gltools/test/transform/transform.spec.js, package.json, website/package.json, yarn.lock
=> chore: Fix CI

modules/api/test/lib/uniform-buffer-layout.spec.js, modules/engine/src/lib/animation-loop.ts, modules/engine/src/lib/pipeline-factory.ts, modules/shadertools/src/lib/shader-assembler/platform-defines.ts, modules/shadertools/test/lib/shader-assembler/assemble-shaders.spec.ts, modules/test-utils/package.json, modules/test-utils/src/create-test-device.ts, modules/test-utils/src/performance-test-runner.ts, modules/test-utils/src/utils.ts
=> chore(test-utils): Cleaner types

modules/webgl/src/context/parameters/unified-parameter-api.ts, modules/webgl/src/context/state-tracker/with-parameters.ts
=> chore(webgl): Accept Device in all parameter functions

modules/gltools/src/classic/context-api.ts, modules/gltools/src/classic/renderbuffer.ts
=> chore(gltools): Allow `Device` to be passed to context and renderbuffer APIs

docs/api-reference/engine/render-loop.md, examples/getting-started/hello-triangle/app.ts, examples/showcase/gltf/app.ts, examples/showcase/instancing/app.ts, examples/showcase/persistence/app.ts, examples/showcase/wandering/app.ts, examples/webgpu/hello-triangle/app.ts, examples/webgpu/instanced-cubes/app.ts, examples/webgpu/rotating-cube/app.ts, examples/webgpu/textured-cube/app.ts, examples/webgpu/two-cubes/app.ts, modules/debug/package.json, modules/engine/src/lib/animation-loop.ts, modules/engine/src/lib/render-loop.ts, modules/engine/test/lib/animation-loop.spec.ts, modules/experimental/package.json, modules/test-utils/package.json, modules/test-utils/src/snapshot-test-runner.ts, modules/test-utils/src/test-runner.ts, modules/test-utils/tsconfig.json, modules/webgl/src/adapter/webgl-device.ts, package.json, test/render/example-test-cases.ts, test/render/render.spec.ts, tsconfig.json
=> chore(test-utils): Clean up test utils

modules/debug/package.json, modules/debug/src/webgl-api-tracing/webgl-debug-context.ts, modules/engine/src/geometry/geometry.ts, modules/experimental/package.json, modules/experimental/src/gltf/create-gltf-model.ts, modules/experimental/src/gltf/create-gltf-objects.ts, modules/experimental/src/gltf/gltf-animator.ts, modules/experimental/src/gltf/gltf-environment.ts, modules/experimental/src/gltf/gltf-instantiator.ts, modules/experimental/src/gltf/gltf-material-parser.ts, modules/experimental/src/gpgpu/point-in-polygon/gpu-point-in-polygon.ts, modules/experimental/src/index.ts, modules/experimental/src/scenegraph/group-node.ts, modules/experimental/src/scenegraph/model-node.ts, modules/experimental/src/scenegraph/scenegraph-node.ts, modules/experimental/src/webvr/display.ts, modules/experimental/src/webvr/vr-display.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/context/debug/webgl-developer-tools.ts, modules/webgl/src/context/polyfill/context-data.ts, modules/webgl/src/context/polyfill/polyfill-context.ts, modules/webgl/src/context/polyfill/polyfill-table.ts, modules/webgl/test/context/context/device-pixels.spec.ts, modules/webgl/test/context/state-tracker/context-state.spec.ts
=> chore: More small fixes for deck.gl v9

modules/engine/src/animation-loop/animation-loop.ts, modules/engine/src/geometries/cube-geometry.ts, modules/engine/src/geometries/cylinder-geometry.ts, modules/engine/src/geometries/ico-sphere-geometry.ts, modules/engine/src/geometries/plane-geometry.ts, modules/engine/src/geometries/sphere-geometry.ts, modules/engine/src/geometries/truncated-cone-geometry.ts, modules/engine/src/geometry/geometry-utils.ts, modules/engine/src/geometry/geometry.ts, modules/engine/src/lib/model-utils.ts, modules/engine/src/lib/pipeline-factory.ts, modules/engine/tsconfig.json, modules/test-utils/src/create-test-device.ts, modules/test-utils/src/snapshot-test-runner.ts, modules/test-utils/src/test-runner.ts, modules/test-utils/tsconfig.json, test/render/example-test-cases.ts, test/render/render.spec.ts
=> chore: noImplicitAny

modules/webgl-legacy/src/classic/buffer.ts, modules/webgl-legacy/src/classic/context-api.ts, modules/webgl-legacy/src/classic/framebuffer.ts, modules/webgl-legacy/src/classic/program.ts, modules/webgl-legacy/src/classic/renderbuffer.ts, modules/webgl-legacy/src/classic/texture.ts, modules/webgl-legacy/src/classic/vertex-array-object.ts, modules/webgl-legacy/src/classic/vertex-array.ts, modules/webgl-legacy/src/engine/classic-animation-loop.ts, modules/webgl-legacy/src/engine/classic-model.ts, modules/webgl-legacy/src/engine/program-manager.ts
=> chore(webgl-legacy): Reduce "implicit any" typings

modules/test-utils/src/performance-test-runner.ts, modules/test-utils/src/snapshot-test-runner.ts, modules/test-utils/src/test-runner.ts, test/render/render.spec.ts
=> chore(test-utils): More cleanup

modules/webgl/test/context/state-tracker/context-state.spec.ts, modules/webgl/test/context/state-tracker/set-parameters.spec.ts, modules/webgl/test/context/state-tracker/track-context-state.spec.ts, modules/webgl/test/test-utils/test-devices.ts, tsconfig.json
=> chore: Active more typescript checks

modules/webgl/src/adapter/resources/webgl-buffer.ts, modules/webgl/src/classic/buffer.ts, modules/webgl/src/context/debug/webgl-developer-tools.ts
=> fix(webgl): Fixes for deck.gl integration

examples/api-v8/stress-test/package.json, examples/showcase/wandering/package.json, modules/api/src/utils/log.ts, modules/debug/package.json, modules/engine/package.json, modules/experimental/src/scenegraph/group-node.ts, modules/gltools/package.json, modules/test-utils/package.json, modules/webgl-legacy/package.json, modules/webgl/package.json, modules/webgpu/package.json, package.json, website-gatsby/package.json, yarn.lock
=> chore: Bump to probe.gl@4.0.0-alpha.1

examples/api-v8/stress-test/package.json, examples/showcase/wandering/package.json, modules/debug/package.json, modules/engine/package.json, modules/gltools/package.json, modules/test-utils/package.json, modules/test-utils/src/snapshot-test-runner.ts, modules/webgl-legacy/package.json, modules/webgl/package.json, modules/webgpu/package.json, package.json, website-gatsby/package.json, yarn.lock
=> chore: Bump probe@4.0.0 on v9.0

modules/webgl/src/types/webgl.ts, package.json, yarn.lock
=> chore: Upgrade to typescript v5

modules/api/src/lib/luma.ts, modules/engine/src/index.ts, modules/engine/src/lib/clip-space.ts, modules/experimental/test/gpgpu/point-in-polygon.spec.ts, modules/webgl-legacy/src/classic/program.ts, modules/webgl-legacy/src/engine/classic-animation-loop.ts, modules/webgl-legacy/src/engine/classic-clip-space.ts, modules/webgl-legacy/src/engine/program-manager.ts, modules/webgl/src/adapter/resources/webgl-buffer.ts, modules/webgl/test/adapter/resources/webgl-framebuffer.spec.ts, modules/webgl/test/adapter/resources/webgl-texture.spec.ts, modules/webgpu/src/adapter/resources/webgpu-buffer.ts, modules/webgpu/src/adapter/resources/webgpu-command-encoder.ts, modules/webgpu/src/adapter/resources/webgpu-compute-pass.ts, modules/webgpu/src/adapter/resources/webgpu-compute-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-external-texture.ts, modules/webgpu/src/adapter/resources/webgpu-framebuffer.ts, modules/webgpu/src/adapter/resources/webgpu-query.ts, modules/webgpu/src/adapter/resources/webgpu-render-pass.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-sampler.ts, modules/webgpu/src/adapter/resources/webgpu-shader.ts, modules/webgpu/src/adapter/resources/webgpu-texture.ts, modules/webgpu/src/adapter/webgpu-canvas-context.ts, modules/webgpu/src/adapter/webgpu-device.ts, modules/webgpu/src/index.ts, yarn.lock
=> fix(webgl-legacy): unbreak deck.gl build

examples/api/animation/index.html, examples/getting-started/instanced-transform/index.html, examples/showcase/wandering/index.html, modules/debug/package.json, modules/debug/src/webgl-api-tracing/webgl-debug-context.ts, modules/debug/src/webgl-api-tracing/webgl-debug.js, modules/experimental/src/gpgpu/histopyramid/histopyramid.ts, modules/experimental/test/gpgpu/histopyramid.spec.ts, modules/experimental/test/gpgpu/point-in-polygon.spec.ts, modules/webgl-legacy/src/classic/copy-and-blit.ts, modules/webgl-legacy/src/transform/buffer-transform.ts, modules/webgl-legacy/src/transform/texture-transform.ts, modules/webgl-legacy/src/transform/transform.ts, modules/webgl-legacy/src/webgl-utils/texture-utils.ts, modules/webgl-legacy/test/transform/buffer-transform.spec.ts, modules/webgl-legacy/test/transform/transform.spec.ts, modules/webgpu/src/adapter/helpers/generate-mipmaps.ts, modules/webgpu/src/adapter/resources/webgpu-texture.ts, scripts/postinstall.sh, yarn.lock
=> chore: Use new Framebuffer api in Transform class

docs/api-reference/api/device.md, modules/api/src/index.ts, modules/api/test/index.ts, modules/api/test/lib/format-compiler-log.spec.ts, modules/shadertools/src/index.ts, modules/shadertools/src/lib/shader-assembler/resolve-modules.ts, modules/shadertools/src/lib/shader-generator/generate-shader.ts, modules/shadertools/src/lib/shader-generator/glsl/generate-glsl.ts, modules/shadertools/src/lib/shader-generator/utils/capitalize.ts, modules/shadertools/src/lib/shader-generator/wgsl/generate-wgsl.ts, modules/shadertools/src/lib/shader-module/shader-module-instance.ts, modules/shadertools/src/lib/shader-module/shader-module.ts, modules/shadertools/src/lib/shader-module/shader-pass.ts, modules/shadertools/src/types.ts, modules/shadertools/test/index.ts, modules/shadertools/test/lib/generator/captialize.spec.ts, modules/shadertools/test/lib/generator/generate-shader.spec.ts, modules/shadertools/test/lib/shader-assembler/resolve-modules.spec.ts, modules/shadertools/test/lib/shader-assembler/shader-module.spec.ts, modules/shadertools/test/modules/modules.spec.ts, modules/webgl/src/adapter/converters/texture-formats.ts, modules/webgl/src/adapter/helpers/get-shader-info.ts, modules/webgl/src/adapter/objects/webgl-renderbuffer.ts
=> feat(shadertools): shader generator for uniform buffer compatible declarations

modules/webgl/src/classic/clear.ts, modules/webgl/src/classic/copy-and-blit.ts, modules/webgl/src/classic/format-utils.ts, modules/webgl/src/index.ts
=> chore: Selected legacy webgl exports for deck.gl

modules/api/src/adapter/device.ts, modules/api/src/adapter/resources/render-pass.ts, modules/engine/src/model/model.ts, modules/webgl/src/classic/copy-and-blit.ts, modules/webgl/src/index.ts
=> feat(webgl): Add legacy copyToTexture to unblock deck picking pass

modules/webgl/src/adapter/webgl-canvas-context.ts
=> fix(webgl): Fix WebGLCanvasContext.resize()

modules/engine/src/model/model.ts
=> fix: Indices attribute workaround

modules/core/src/adapter/device.ts, modules/core/src/adapter/resources/buffer.ts, modules/core/src/adapter/resources/command-buffer.ts, modules/core/src/adapter/resources/command-encoder.ts, modules/core/src/adapter/resources/compute-pass.ts, modules/core/src/adapter/resources/compute-pipeline.ts, modules/core/src/adapter/resources/external-texture.ts, modules/core/src/adapter/resources/framebuffer.ts, modules/core/src/adapter/resources/render-pipeline.ts, modules/core/src/adapter/resources/resource.ts, modules/core/src/adapter/resources/sampler.ts, modules/core/src/adapter/resources/shader.ts, modules/core/src/adapter/resources/texture.ts, modules/engine/src/model/model.ts
=> chore(core): default props cleanup

modules/core/src/adapter/device.ts, modules/engine/src/geometry/gpu-geometry.ts, modules/engine/src/lib/pipeline-factory.ts, modules/engine/src/model/model.ts, test/render/example-test-cases.ts
For #
- setTopology didn't take effect
- GPUGeometry crash on unknown attributes
=> fix(engine): More model fixes

modules/core/src/adapter/attribute-utils/get-attribute-from-layouts.ts, modules/core/src/adapter/types/shader-layout.ts, modules/core/src/index.ts, modules/core/test/adapter/attribute-utils/get-attribute-from-layout.spec.ts, modules/core/test/index.ts
=> fix: interleaved stride and buffer/attribute name conflict

modules/shadertools/src/modules/picking/picking.ts
=> Fix picking shader compile error

modules/api-tests/test/adapter/device-helpers/set-device-parameters.spec.ts, modules/shadertools/test/gpu-test-utils.ts, modules/test-utils/src/engine/classic-animation-loop.ts, modules/webgl/src/adapter/converters/device-parameters.ts, modules/webgl/src/adapter/resources/webgl-render-pass.ts, modules/webgl/src/adapter/resources/webgl-texture.ts, modules/webgl/src/classic/clear.ts, modules/webgl/src/classic/copy-and-blit.ts, modules/webgl/src/context/parameters/unified-parameter-api.ts, modules/webgl/src/context/state-tracker/track-context-state.ts, modules/webgl/src/context/state-tracker/with-parameters.ts, modules/webgl/src/index.ts, modules/webgl/test/adapter/device-helpers/set-device-parameters.spec.ts, modules/webgl/test/context/state-tracker/context-state.spec.ts, modules/webgl/test/context/state-tracker/set-parameters.spec.ts, modules/webgl/test/context/state-tracker/track-context-state.spec.ts
=> feat(webgl): Rename parameter setters to emphasize they take WebGL parameters

.github/workflows/test.yml, modules/experimental/src/gltf/create-gltf-model.js
For https://github.com/visgl/deck.gl/issues/8099
- Merge defines when creating node models
=> Fix GLTF model defines

docs/api-reference/core/device.md, modules/core/src/adapter/device.ts
For #
- Based on usage in deck.gl v9
- Add new method
=> feat(core): Add Device.getCanvasContext()

examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/texture-3d/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, examples/tutorials/hello-cube/package.json, examples/tutorials/lighting/package.json, examples/webgpu/computeboids/package.json, examples/webgpu/instanced-cubes/package.json, examples/webgpu/textured-cube/package.json, examples/webgpu/triangle/package.json, examples/webgpu/two-cubes/package.json, modules/engine/package.json, modules/shadertools/package.json, yarn.lock
=> chore: Bump to math.gl@4.0.0

.gitignore, CHANGELOG.md, examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/program-management/package.json, examples/api/texture-3d/package.json, examples/getting-started/hello-cube/package.json, examples/getting-started/instanced-transform/package.json, examples/getting-started/lighting/package.json, examples/performance/stress-test/package.json, examples/showcase/dof/package.json, examples/showcase/gltf/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, examples/showcase/wandering/app.js, examples/showcase/wandering/package.json, lerna.json, modules/debug/package.json, modules/engine/package.json, modules/experimental/package.json, modules/gltools/package.json, modules/shadertools/package.json, modules/test-utils/package.json, modules/webgl/package.json, package.json, website/package.json, yarn.lock
For #
- Dev only branch to support integrqtion on deck.gl 8.10 dev only branch.
- Bump math dependencies
- lerna.json
- gitignore
- ...
=> chore: 8.6-dev branch setup

docs/api-guide/device.md, docs/api-reference-v8/webgl-legacy/README.md, docs/api-reference/core/uniform-buffer-layout.md, docs/api-reference/core/uniform-store.md, docs/api-reference/shadertools/README.md, docs/api-reference/shadertools/modules/fp32.md, docs/api-reference/shadertools/modules/fp64.md, docs/api-reference/shadertools/modules/image-processing.md, docs/api-reference/shadertools/modules/pbr.md, docs/api-reference/shadertools/modules/picking-2.md, docs/api-reference/shadertools/modules/picking.md, docs/api-reference/shadertools/modules/project.md, docs/api-reference/shadertools/shader-modules.md, docs/developer-guide/editing.md, docs/developer-guide/installing.md, docs/sidebar.json, tsconfig.json
=> docs(shadertools): UniformStore docs

modules/engine/src/shadertools/shader-module-uniforms.ts, modules/shadertools/src/lib/shader-module/normalize-shader-module.ts, modules/shadertools/src/lib/shader-module/shader-module-instance.ts, modules/shadertools/src/lib/shader-module/shader-module.ts, modules/shadertools/src/modules-ubo/lighting/lights/lighting-uniforms.ts, modules/shadertools/src/modules-ubo/postprocessing/fxaa/fxaa.ts, modules/shadertools/src/modules-ubo/postprocessing/image-adjust-filters/brightnesscontrast.ts, modules/shadertools/src/modules-ubo/postprocessing/image-adjust-filters/denoise.ts, modules/shadertools/src/modules-ubo/postprocessing/image-adjust-filters/huesaturation.ts, modules/shadertools/src/modules-ubo/postprocessing/image-adjust-filters/noise.ts, modules/shadertools/src/modules-ubo/postprocessing/image-adjust-filters/sepia.ts, modules/shadertools/src/modules-ubo/postprocessing/image-adjust-filters/vibrance.ts, modules/shadertools/src/modules-ubo/postprocessing/image-adjust-filters/vignette.ts, modules/shadertools/src/modules-ubo/postprocessing/image-blur-filters/tiltshift.ts, modules/shadertools/src/modules-ubo/postprocessing/image-blur-filters/triangleblur.ts, modules/shadertools/src/modules-ubo/postprocessing/image-blur-filters/zoomblur.ts, modules/shadertools/src/modules-ubo/postprocessing/image-fun-filters/colorhalftone.ts, modules/shadertools/src/modules-ubo/postprocessing/image-fun-filters/dotscreen.ts, modules/shadertools/src/modules-ubo/postprocessing/image-fun-filters/edgework.ts, modules/shadertools/src/modules-ubo/postprocessing/image-fun-filters/hexagonalpixelate.ts, modules/shadertools/src/modules-ubo/postprocessing/image-fun-filters/ink.ts, modules/shadertools/src/modules-ubo/postprocessing/image-fun-filters/magnify.ts, modules/shadertools/src/modules-ubo/postprocessing/image-warp-filters/bulgepinch.ts, modules/shadertools/src/modules-ubo/postprocessing/image-warp-filters/swirl.ts, modules/shadertools/test/lib/shader-module/shader-module.spec.ts
For #
- Clarify shader module field names.
-
=> chore(shadertools): Rename uniformPropTypes field

docs/tutorials/README.mdx, examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/texture-3d/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, examples/tutorials/hello-cube/package.json, examples/tutorials/hello-gltf/package.json, examples/tutorials/hello-instancing/package.json, examples/tutorials/hello-triangle/package.json, examples/tutorials/lighting/package.json, examples/tutorials/shader-hooks/package.json, examples/tutorials/shader-modules/package.json, examples/webgpu/computeboids/package.json, examples/webgpu/instanced-cubes/package.json, examples/webgpu/rotating-cube/package.json, examples/webgpu/textured-cube/package.json, examples/webgpu/triangle/package.json, examples/webgpu/two-cubes/package.json, package.json, website/package.json, yarn.lock
=> chore: typescript 5.3

docs/tutorials/README.mdx, examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/texture-3d/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, examples/tutorials/hello-cube/package.json, examples/tutorials/hello-gltf/package.json, examples/tutorials/hello-instancing/package.json, examples/tutorials/hello-triangle/package.json, examples/tutorials/lighting/package.json, examples/tutorials/shader-hooks/package.json, examples/tutorials/shader-modules/package.json, examples/webgpu/computeboids/package.json, examples/webgpu/instanced-cubes/package.json, examples/webgpu/rotating-cube/package.json, examples/webgpu/textured-cube/package.json, examples/webgpu/triangle/package.json, examples/webgpu/two-cubes/package.json, yarn.lock
=> chore: vite 5

docs/api-reference/shadertools/modules/goraud.md, docs/api-reference/shadertools/modules/lights.md, docs/api-reference/shadertools/modules/phong.md, examples/tutorials/shader-modules/app.ts, modules/core/src/lib/uniforms/uniform-store.ts, modules/shadertools/test/index.ts, modules/shadertools/test/modules/lighting/gouraud-material.spec.ts
For #
- Fix the shader modules example.
- Add a new uniform buffer creation method to the `UniformStore`.
- Fix example
- Typo
=> fix: shader module example

docs/api-reference/shadertools/modules/picking.md, modules/shadertools/src/modules/engine/picking/picking.ts, modules/shadertools/test/modules/engine/picking.spec.ts
- Implement useNormalizedColors option in picking module
=> Implement picking.useNormalizedColors

.prettierignore, modules/core/src/adapter/device.ts, modules/core/src/adapter/resources/render-pipeline.ts, modules/core/src/adapter/types/shader-layout.ts, modules/core/src/index.ts, modules/engine/src/model/model.ts, modules/webgl/src/adapter/resources/webgl-buffer.ts, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgpu/src/adapter/webgpu-device.ts
Simplifying #1858 review, by applying Prettier to the affected files separately in this PR.
=> Apply Prettier to all files touched by TransformFeedback changes

modules/gltf/src/gltf/create-gltf-objects.ts, modules/gltf/src/gltf/gltf-instantiator.ts
- Correct type for GLTFInstantiator scenes
=> [chore] Correct type for GLTFInstantiator scenes

modules/gltf/src/gltf/gltf-animator.ts
=> [feat] Add name prop to GLTFAnimation class

modules/engine/src/animation-loop/animation-loop.ts
Fix logic errors in `AnimationLoop._cancelAnimationFrame`
=> fix: cancelAnimationFrame

package.json, yarn.lock
For #1501
- Bump ocular-devtools
=> chore: bump ocular-devtools

modules/engine/test/transform/transform.spec.ts, modules/webgl/src/adapter/converters/device-parameters.ts, modules/webgl/test/adapter/device-helpers/set-device-parameters.spec.ts
Extracting part of #1896 into a smaller and easier PR.
=> feat(webgl): Restore blending in setDeviceParameters

modules/shadertools/src/lib/shader-assembly/assemble-shaders.ts
Fixing shader compilation errors encountered testing #1896 against deck.gl. Some deck.gl shaders contain characters `->` (in comments, for example) and so automatically detecting WGSL currently is not safe. I feel it may be best not to infer. This PR also conditions GLSL 100/300 transpilation behind a source/target version check.
=> fix(shadertools): Explicit GLSL version and language

modules/shadertools/src/modules-webgl1/lighting/pbr/pbr-fragment.glsl.ts, modules/shadertools/src/modules-webgl1/lighting/pbr/pbr-vertex.glsl.ts
In the future, will want to update the shader to use UBOs & `ShaderInput`, but this quick fix enables usage in deck.gl
- Update pbr shaders to use glsl300
=> fix(shadertools): Port pbr shader module to glsl300

modules/engine/src/model/model.ts
- Use log.warn rather than console.warn
=> Use log.warn rather than console.warn

examples/showcase/instancing/app.ts, modules/core/src/index.ts, modules/core/src/init.ts, modules/core/test/index.ts, modules/engine/src/debug/debug-shader-layout.ts, modules/engine/src/model/model.ts, modules/engine/src/shader-inputs.ts, modules/engine/test/debug/get-debug-table-from-shader-layout.spec.ts, modules/engine/test/index.ts, modules/webgl/src/context/polyfill/polyfill-context.ts
For #
- Debug shader inputs during draw calls
- Add debug trace code to shader inputs
- Update instancing example to use shader inputs and use to test tracing
- Also fixes some unnecessary warnings during startup to reduce noise.
=> feat: Add shader inputs (uniform buffer) debug trace

docs/developer-guide/debugging.md, modules/core-tests/test/adapter/resources/buffer.spec.ts, modules/core/src/adapter/resources/buffer.ts, modules/core/src/adapter/type-utils/vertex-format-from-attribute.ts, modules/engine/src/model/model.ts, modules/webgl/src/adapter/resources/webgl-buffer.ts, modules/webgpu/src/adapter/resources/webgpu-buffer.ts
=> feat: Add Buffer.debugData

docs/api-reference/engine/animation-loop.md, docs/upgrade-guide/upgrade-v9.md, docs/whats-new.md, modules/engine/src/animation-loop/animation-loop.ts, modules/engine/src/model/model.ts
For #1501
- Update AnimationLoop docs
- Update AnimationLoop docs
- Update AnimationLoop source file
=> docs: Pass on AnimationLoop docs

lerna.json, modules/constants/package.json, modules/core-tests/package.json, modules/core/package.json, modules/engine/package.json, modules/gltf/package.json, modules/shadertools/package.json, modules/test-utils/package.json, modules/webgl/package.json, modules/webgpu/package.json
For #
- https://publint.dev/@luma.gl/core@9.0.0-alpha.54
=> chore: publint + bump lerna.json to beta

examples/showcase/instancing/app.ts, examples/showcase/instancing/index.html, examples/showcase/instancing/package.json, examples/showcase/instancing/vite.config.ts, modules/core/src/adapter/resources/render-pipeline.ts, modules/core/src/adapter/resources/shader.ts, modules/core/src/adapter/resources/vertex-array.ts, modules/core/src/lib/compiler-log/format-compiler-log.ts, modules/core/src/lib/uniforms/uniform-store.ts, modules/engine/src/geometry/geometry-utils.ts, modules/engine/src/model/model.ts, modules/shadertools/src/lib/shader-assembly/assemble-shaders.ts, modules/shadertools/src/modules/lighting/no-material/dirlight.ts, modules/webgpu/src/adapter/helpers/get-bind-group.ts, modules/webgpu/src/adapter/helpers/get-vertex-buffer-layout.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-shader.ts, modules/webgpu/src/adapter/resources/webgpu-vertex-array.ts, yarn.lock
For #
- Make instancing example run on WebGPU
- WGSL shader for instancing example
- Various fixes in webgpu module
=> fix: WebGPU instancing example

website/docusaurus.config.js, website/package.json
- Add `yarn build-staging` command for website
- Allow build to pass by only warning on broken links
=> (website) Add staging website build

modules/core/src/adapter/device.ts, modules/webgl/src/adapter/webgl-device.ts
For #1501 
- Follow-up, also need a wrapper for getGLParameters.
- New `device.getParametersWebGL()`
=> feat(core): Additional WebGL-specific Device methods

.github/workflows/test.yml, .gitignore, docs/api-reference/core/device-features.mdx, docs/api-reference/core/parameters.md, docs/whats-new.md, modules/constants/src/index.ts, modules/constants/src/webgl-constants.ts, modules/constants/src/webgl-types.ts, modules/core/src/adapter/device.ts, modules/core/src/adapter/types/parameters.ts, modules/webgl/src/adapter/converters/device-parameters.ts, modules/webgl/src/adapter/webgl-device.ts
For #
- Add support for Chrome WebGL 2 extensions
- Add provokingVertex parameter, `provoking-vertex-webgl` feature.
=> feat(webgl): RenderParameters.provokingVertex (WEBGL_provoking_vertex)

dev-docs/tech-docs-wip/design-notes.md, docs/api-reference/core/device-features.mdx, docs/api-reference/core/parameters.md, docs/whats-new.md, modules/constants/src/webgl-constants.ts, modules/constants/src/webgl-types.ts, modules/core/src/adapter/device.ts, modules/core/src/adapter/types/parameters.ts, modules/webgl/src/adapter/converters/device-parameters.ts, modules/webgl/src/adapter/device-helpers/webgl-device-features.ts, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgl/src/adapter/resources/webgl-shader.ts, modules/webgl/src/context/parameters/webgl-parameter-tables.ts
For #
- Add 'clip-cull-distance-webgl` feature (expose `WEBGL_clip_cull_distance` extension).
- Updates in necessary places.
=> feat(webgl): clip-cull-distance-webgl feature WEBGL_clip_cull_distance

docs/api-reference/core/device-features.mdx, docs/api-reference/core/parameters.md, docs/whats-new.md, modules/constants/src/webgl-constants.ts, modules/constants/src/webgl-types.ts, modules/core/src/adapter/device.ts, modules/core/src/adapter/types/parameters.ts, modules/webgl/src/adapter/converters/device-parameters.ts, modules/webgl/src/adapter/device-helpers/webgl-device-features.ts, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgl/src/adapter/resources/webgl-shader.ts, modules/webgpu/src/adapter/webgpu-device.ts
For #
- Working through WebGL 2 extensions exposed on Chrome Canary / MacOS
- Add new features / extensions
- Docs
- Types
- Some cleanup
=> feat(webgl): Add shader-noperspective-webgl and shader-conservative-depth features

modules/webgl/src/adapter/resources/webgl-transform-feedback.ts, tsconfig.build.json, tsconfig.module.json
- Add plugins in the correct config file
=> fix: build setup

docs/whats-new.md
For #
- To avoid delaying 9.0 release, let's mark luma.gl WebGPU support as experimental.
- whats-new updates
=> docs: Mark WebGPU support in 9.0 as experimental

docs/tutorials/README.mdx, modules/core/src/adapter/resources/framebuffer.ts, modules/core/src/adapter/resources/texture.ts, modules/engine/src/model/model.ts, modules/webgl/src/adapter/resources/webgl-framebuffer.ts, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgl/src/adapter/resources/webgl-texture.ts, modules/webgl/src/classic/copy-and-blit.ts, modules/webgpu/src/adapter/resources/webgpu-render-pass.ts, modules/webgpu/src/adapter/resources/webgpu-texture.ts
For #
#1860 
- Create default TextureViews for Textures.
- Switch to TextureViews in framebuffers etc.
=> feat(core): Support TextureViews

docs/api-reference/core/resources/compute-pass.md, docs/api-reference/core/resources/compute-pipeline.md, modules/core-tests/test/adapter/resources/compute-pipeline.spec.ts, modules/core-tests/test/index.ts, modules/core/src/adapter/resources/buffer.ts, modules/core/src/adapter/resources/compute-pipeline.ts, modules/core/src/adapter/resources/shader.ts, modules/core/src/adapter/types/shader-layout.ts, modules/core/src/index.ts, modules/engine/src/lib/pipeline-factory.ts, modules/webgpu/src/adapter/helpers/get-bind-group.ts, modules/webgpu/src/adapter/resources/webgpu-buffer.ts, modules/webgpu/src/adapter/resources/webgpu-compute-pass.ts, modules/webgpu/src/adapter/resources/webgpu-compute-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-shader.ts
For #
- Improve ComputePipeline implementation
- add tests
- Support compute pipelines in `PipelineFactory`
=> chore(webgpu): Improve ComputePipeline implementation, add tests

docs/api-reference/core/resources/render-pipeline.md, examples/webgpu/computeboids/app.ts, modules/core/src/adapter/resources/render-pipeline.ts, modules/engine/src/lib/pipeline-factory.ts, modules/engine/src/model/model.ts, modules/engine/test/lib/model.spec.ts, modules/shadertools/src/lib/shader-assembly/select-shaders.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts
For #
- Quick and dirty fix for https://github.com/visgl/luma.gl/issues/1984
- Updates topology correctly but creates additional pipelines (programs).
- Fix the issue by adding topology to pipelinefactory cache
- Add model test cases
- Fixes for WebGPU Models.
=> fix(engine): Add topology to pipeline hash on WebGL

docs/api-guide/gpu/gpu-rendering.md, docs/api-reference/core/resources/render-pipeline.md, docs/api-reference/engine/model.md, modules/core/src/adapter/device.ts, modules/core/src/adapter/resources/buffer.ts, modules/core/src/adapter/resources/render-pipeline.ts, modules/core/src/adapter/resources/texture.ts, modules/engine/src/model/model.ts, modules/engine/test/lib/model.spec.ts, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts
For #
- If resources are not initialized, pipeline will fail to draw.
- Plumb through this error condition as `draw()` return value.
- Offer a `needsRedraw()` mechanism on model.
-
=> feat(engine): Add draw() call success tracking, needsRedraw flag.

modules/core/src/adapter/device.ts, modules/shadertools/src/lib/shader-assembly/platform-info.ts, modules/test-utils/src/null-device/null-device.ts, modules/webgl/src/adapter/device-helpers/webgl-device-features.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgpu/src/adapter/webgpu-device.ts
For #
- For debugging purposes, useful to be able to block extensions and also force initialization of all extensions
- Add DeviceProps.disabledFeatures
- Add DeviceProps.initializeFeatures
- Add `unknown` device type to allow for application defined devices.
- Set `NullDevice` to type `unknown`
=> feat(webgl): Fine-grained extension control

.github/workflows/test.yml, lerna.json, package.json, yarn.lock
For #
- 9.0 is moving to release branch
- Node 20 runs tests faster
- Move lerna.json to 9.1.0-alpha.0 (9.0-release branch cut)
- node@20
- yarn@4.1.1
=> chore: Bump to 9.1-alpha, node@20, yarn@4.1.1

.eslintrc.cjs, CHANGELOG.md, examples/portable/rotating-cube/package.json, examples/script/webgl/transform-feedback/package.json, examples/tutorials/hello-gltf/package.json, examples/webgpu/computeboids/app.ts, modules/core/package.json, modules/engine/package.json, modules/engine/src/debug/copy-texture-to-image.ts, modules/engine/src/index.ts, modules/gltf/package.json, modules/gltf/src/gltf/gltf-instantiator.ts, modules/shadertools/package.json, modules/shadertools/src/modules-webgl1/lighting/dirlight/dirlight.ts, modules/test-utils/package.json, modules/webgl/package.json, modules/webgpu/package.json, package.json, yarn.lock
- Enable the following lint rules:
+ `import/named`
+ `import/no-unresolved`
+ `import/no-extraneous-dependencies`
- Add missing dependencies to submodules
- Remove dev dependencies from submodules
- Fix wrong import paths
=> Audit package dependencies

.eslintignore, modules/constants/package.json, modules/constants/src/bundle.ts, modules/core/bundle.ts, modules/core/package.json, modules/engine/bundle.ts, modules/engine/package.json, modules/gltf/bundle.ts, modules/gltf/package.json, modules/shadertools/bundle.ts, modules/shadertools/package.json, modules/webgl/bundle.ts, modules/webgl/package.json, modules/webgpu/bundle.ts, modules/webgpu/package.json
=> Fix pre-built bundle setup

docs/api-reference/core/resources/render-pipeline.md, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
For #1992
- Address @felixpalmer comments
-
=> chore: Address comments on #1992

modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
=> fix(webgl): Reduce console flood

modules/core/src/adapter-utils/get-attribute-from-layouts.ts, modules/core/src/adapter/device.ts, modules/core/src/adapter/resources/buffer.ts, modules/core/src/adapter/resources/command-encoder.ts, modules/core/src/adapter/resources/compute-pass.ts, modules/core/src/adapter/resources/compute-pipeline.ts, modules/core/src/adapter/resources/query-set.ts, modules/core/src/adapter/resources/render-pass.ts, modules/core/src/adapter/resources/render-pipeline.ts, modules/core/src/adapter/resources/resource.ts, modules/core/src/adapter/resources/shader.ts, modules/core/src/adapter/resources/texture-view.ts, modules/core/src/adapter/resources/texture.ts, modules/core/src/adapter/resources/transform-feedback.ts, modules/core/src/adapter/resources/vertex-array.ts, modules/core/src/adapter/types/parameters.ts, modules/core/src/gpu-type-utils/decode-attribute-type.ts, modules/core/src/portable/uniform-block.ts, modules/core/src/portable/uniform-store.ts, modules/core/tsconfig.json, modules/engine/src/animation-loop/animation-loop.ts, modules/engine/src/computation.ts, modules/engine/src/geometry/geometry.ts, modules/engine/src/lib/pipeline-factory.ts, modules/engine/src/shader-inputs.ts
=> chore(core): strict null checks

modules/engine/src/animation-loop/animation-loop.ts, modules/engine/src/async-texture/async-texture.ts, modules/engine/src/computation.ts, modules/engine/src/debug/copy-texture-to-image.ts, modules/engine/src/debug/debug-framebuffer.ts, modules/engine/src/geometry/geometry.ts, modules/engine/src/geometry/gpu-geometry.ts, modules/engine/src/lib/pipeline-factory.ts, modules/engine/src/model/model.ts, modules/engine/src/scenegraph/model-node.ts, modules/engine/src/scenegraph/scenegraph-node.ts, modules/engine/src/shader-inputs.ts, modules/engine/src/transform/buffer-transform.ts, modules/engine/src/transform/texture-transform.ts, modules/engine/tsconfig.json
=> chore(engine): strict null checks

.eslintrc.cjs, modules/core/src/adapter/canvas-context.ts, modules/core/src/adapter/resources/compute-pipeline.ts, modules/core/src/adapter/resources/external-texture.ts, modules/test-utils/src/null-device/null-canvas-context.ts, modules/webgl/src/adapter/webgl-canvas-context.ts, modules/webgpu/src/adapter/helpers/get-bind-group.ts, modules/webgpu/src/adapter/helpers/get-vertex-buffer-layout.ts, modules/webgpu/src/adapter/helpers/webgpu-parameters.ts, modules/webgpu/src/adapter/resources/webgpu-command-encoder.ts, modules/webgpu/src/adapter/resources/webgpu-compute-pass.ts, modules/webgpu/src/adapter/resources/webgpu-compute-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-external-texture.ts, modules/webgpu/src/adapter/resources/webgpu-render-pass.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-texture.ts, modules/webgpu/src/adapter/resources/webgpu-vertex-array.ts, modules/webgpu/src/adapter/webgpu-canvas-context.ts, modules/webgpu/src/adapter/webgpu-device.ts, modules/webgpu/tsconfig.json
For #
- Chipping away at strict null checks, module by module.
- webgpu module.
=> chore(webgpu): Strict null checks

modules/constants/src/index.ts, modules/constants/src/webgl-types.ts, modules/core/src/adapter/types/parameters.ts, modules/core/src/index.ts, modules/webgl/src/adapter/converters/device-parameters.ts
Changes:
- Add missing blend factors
- Tighten types in device-parameters to catch similar issues
- Fixes #2039
=> feat(core): Add missing blend factors, restrict types in device-parameters

docs/legacy/porting-guide.md
Context: https://github.com/visgl/deck.gl/pull/8677
=> docs(core): Add notes to porting guide about mipmapFilter and lodMaxClamp

modules/shadertools/src/modules-webgl1/project/project.ts
For https://github.com/visgl/deck.gl/issues/8711
- Broken '../..'  import, probably injected by vscode.
- Fix the import
- There seem to be two more cases on the release branch that have already been fixed on master, will make a separate PR for those.
=> fix(shadertools): fix import

modules/webgl/src/adapter/converters/texture-formats.ts, modules/webgl/src/adapter/device-helpers/webgl-device-features.ts, modules/webgl/src/adapter/device-helpers/webgl-device-limits.ts, modules/webgl/src/adapter/resources/webgl-shader.ts, modules/webgl/src/adapter/resources/webgl-texture-view.ts, modules/webgl/src/adapter/resources/webgl-texture.ts, modules/webgl/src/adapter/resources/webgl-vertex-array.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/classic/copy-and-blit.ts, modules/webgl/src/context/debug/webgl-developer-tools.ts, modules/webgl/src/context/parameters/webgl-parameter-tables.ts, modules/webgl/src/context/state-tracker/track-context-state.ts, modules/webgl/test/adapter/resources/webgl-vertex-array.spec.ts, modules/webgl/tsconfig.json
=> chore(webgl): Start fixing strictNullChecks issues.

modules/engine/src/model/model.ts
Missed in #2049
- Disable warning
=> Disable more warnings about updateModuleSettings

modules/shadertools/src/modules/engine/picking/picking.ts
For https://github.com/visgl/deck.gl/issues/8704
=> fix(shadertools) attribute picking regression

package.json
- tsc does not actually rebuild unless *.tsbuildinfo is cleared.
=> fix(build): inlined version off by 1

examples/tutorials/hello-gltf/package.json, modules/gltf/package.json, package.json, yarn.lock
For #
- Bump loaders.gl to 4.2
-
=> chore: Bump to loaders.gl@4.2.0

examples/tutorials/hello-gltf/package.json, modules/gltf/package.json, package.json, yarn.lock
For #
- Bump to loaders.gl@4.2.0 (on 9.0-release)
-
=> chore: Bump to loaders.gl@4.2.0 (on 9.0-release)

modules/engine/src/shader-inputs.ts, modules/engine/test/shader-inputs.spec.ts, modules/shadertools/src/lib/shader-assembly/resolve-modules.ts
=> Revert "shadertools: Resolve dependencies in ShaderInputs"

docs/api-reference/core/luma.md, modules/core/src/adapter/device.ts, modules/core/src/adapter/luma.ts, yarn.lock
For #
- Prep for #2083 
- Trivial changes from next PR
=> chore(core): luma.ts cleanup

modules/core/src/adapter/device.ts, modules/core/src/lib/luma.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/src/context/debug/spector.ts, yarn.lock
- For #2080 
- CDN URL, props initialization, spector initialization order
=> fix(webgl): Fix spector integration (9.0-release)

modules/core/src/adapter/adapter.ts, modules/core/src/adapter/luma.ts, modules/core/test/adapter/luma.spec.ts, modules/test-utils/src/create-test-device.ts, modules/test-utils/src/null-device/null-adapter.ts, modules/webgl/src/adapter/webgl-adapter.ts, modules/webgl/src/context/debug/spector.ts, modules/webgpu/src/adapter/webgpu-adapter.ts
For #
- Prep for #2089 - dynamic loading of backends
- Make adapters async
=> feat(core): Adapters methods now async

modules/shadertools/src/index.ts, modules/shadertools/src/types.ts
=> feat(shadertools) Export Uniform types

CHANGELOG.md, lerna.json, modules/constants/package.json, modules/core/package.json, modules/engine/package.json, modules/gltf/package.json, modules/shadertools/package.json, modules/test-utils/package.json, modules/webgl/package.json, modules/webgpu/package.json
v9.0 PR for https://github.com/visgl/luma.gl/pull/2106
- Include @loaders.gl/core dependency
- Undo lerna changes to allow publish with correct version
=> chore(gltf): Include @loaders.gl/core dependency

modules/shadertools/src/index.ts, modules/shadertools/src/types.ts
=> Revert feat(shadertools) Export Uniform types (#2108)

modules/engine/src/async-texture/async-texture.ts, modules/webgl/src/adapter/resources/webgl-texture.ts
For #
- AsyncTexture cubemaps supply an object with multiple promises, ensure all are resolved.
-
=> fix(engine): AsyncTexture nested promises

modules/engine/src/shader-inputs.ts, modules/engine/test/shader-inputs.spec.ts
Closes https://github.com/visgl/luma.gl/issues/2118
- Resolve dependencies in ShaderInputs
- Test
=> shadertools: Resolve dependencies in ShaderInputs

docs/api-reference/engine/animation-loop-template.md
Just found this when trying to copy-paste some code
=> chore: typo in AnimationLoopTemplate doc

docs/tutorials/README.mdx, examples/api/animation/package.json, examples/api/cubemap/package.json, examples/api/texture-3d/package.json, examples/showcase/instancing/package.json, examples/showcase/persistence/package.json, examples/tutorials/hello-cube/package.json, examples/tutorials/hello-gltf/package.json, examples/tutorials/hello-instanced-cubes/package.json, examples/tutorials/hello-instancing/package.json, examples/tutorials/hello-triangle-geometry/package.json, examples/tutorials/hello-triangle/package.json, examples/tutorials/hello-two-cubes/package.json, examples/tutorials/lighting/package.json, examples/tutorials/shader-hooks/package.json, examples/tutorials/shader-modules/package.json, examples/webgpu/computeboids/package.json, examples/webgpu/textured-cube/package.json, modules/shadertools/src/lib/shader-assembly/assemble-shaders.ts, package.json, website/package.json, website/yarn.lock, yarn.lock
For #
- Upgrade to typescript@5.5
- Add `ts-patch` resolution.
=> chore: Bump to typescript@5.5

examples/api/texture-3d/app.ts, modules/webgl/src/adapter/helpers/webgl-texture-utils.ts, modules/webgl/src/adapter/resources/webgl-framebuffer.ts, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgl/src/adapter/resources/webgl-texture.ts, modules/webgl/src/classic/copy-and-blit.ts, website/content/sidebar-examples.js
For #
- Texture3D example renders under webgl.
- Blending still does not seem to be working.
=> chore: Partially restore texture-3d example

.github/workflows/website.yml
Fix for https://github.com/visgl/luma.gl/issues/2135, see [comment](https://github.com/visgl/luma.gl/issues/2135#issuecomment-2255479321)
- Invoke `yarn install` as we do in the `test` workflow
=> CI: fix website workflow

.ocularrc.js, examples/showcase/instancing/app.ts, lerna.json, package.json, test/render/example-test-cases.ts, tsconfig.json, yarn.lock
For #
- Persistent problems with module resolution even after the big fix
- Need to unbreak the build and publishing for now
- We can restore later if we can fix the issues.
- Update lerna, package.json, ocularrc.js to drop examples
=> fix: Decouple examples from install and build

docs/api-guide/gpu/gpu-textures.mdx, docs/api-reference/core/resources/command-encoder.md, docs/api-reference/core/resources/texture.md, docs/whats-new.md
For #
- Improvement pass on Texture docs.
- Prep for Texture method cleanup
-
=> docs: Texture doc cleanup

examples/tutorials/hello-gltf/app.ts
For #
- Khronos seems to have broken out their glTF assets from their viewer repo into a separate repo.
- Update path
- We might want to check if there are new assets for us to integrate with
=> fix: Update path to Khrnos glTF assets

modules/core/src/adapter/types/shader-layout.ts, modules/engine/src/debug/debug-shader-layout.ts, modules/webgl/src/adapter/helpers/get-shader-layout.ts, modules/webgl/src/deprecated/accessor.ts, modules/webgl/src/deprecated/clear.ts
For #
- Prepare for imminent removal of deprecated code paths by issuing console warnings.
- Add warnings
- Avoid using Accessor internally
=> chore: log warnings in deprecated code paths (accessor, clear)

modules/engine/package.json, modules/gltf/package.json, modules/shadertools/package.json, modules/test-utils/package.json, modules/webgl/package.json, modules/webgpu/package.json, package.json, yarn.lock
For #
- peerExtensions should reference 9.1 alphas on master
-
=> chore: Fix peerExtensions

examples/api/animation/app.ts, examples/showcase/instancing/app.ts, examples/showcase/instancing/index.html, modules/core/src/adapter/canvas-context.ts, modules/webgpu/src/adapter/webgpu-canvas-context.ts
=> fix(examples): Fix resolution and use dirlight module in instancing example

docs/tutorials/lighting.mdx, examples/api/cubemap/index.html, examples/api/texture-3d/index.html, examples/script/webgl/transform-feedback/index.html, examples/tutorials/hello-gltf/index.html, examples/tutorials/hello-instancing/index.html, examples/tutorials/hello-triangle-geometry/index.html, examples/tutorials/lighting/app.ts, examples/tutorials/lighting/index.html, examples/tutorials/shader-hooks/index.html, examples/tutorials/shader-modules/index.html
=> feat(examples): Partial WGSL port of lighting example

modules/core/test/adapter/resources/framebuffer.spec.ts
Follow up of #2161
- Add test case to verify framebuffer resize
=> Add test case for Framebuffer.resize

modules/core/src/adapter/device.ts, modules/core/src/adapter/resources/framebuffer.ts, modules/core/src/adapter/resources/texture.ts, modules/engine/src/async-texture/async-texture.ts, modules/test-utils/src/null-device/null-device.ts, modules/test-utils/src/null-device/resources/null-texture.ts, modules/webgl/src/adapter/resources/webgl-framebuffer.ts, modules/webgl/src/adapter/resources/webgl-texture.ts, modules/webgl/src/adapter/webgl-device.ts, modules/webgl/test/context/state-tracker/webgl-state-tracker.spec.ts, modules/webgpu/src/adapter/resources/webgpu-texture.ts, modules/webgpu/src/adapter/webgpu-canvas-context.ts, modules/webgpu/src/adapter/webgpu-device.ts
=> fix: texture integer coordinates, resize utils

modules/shadertools/test/modules/lighting/gouraud-material.spec.ts, modules/shadertools/test/modules/lighting/phong-material.spec.ts
For https://github.com/visgl/luma.gl/pull/2171
- Add missing tests
=> shadertools: specularColor tests

modules/core/src/adapter/resources/command-encoder.ts, modules/core/src/adapter/resources/framebuffer.ts, modules/core/src/adapter/resources/texture.ts, modules/core/test/adapter/resources/command-encoder.spec.ts, modules/core/test/index.ts, modules/engine/src/async-texture/async-texture.ts, modules/engine/test/compute/texture-transform.spec.ts, modules/webgl/src/adapter/helpers/webgl-texture-utils.ts, modules/webgl/src/adapter/resources/webgl-command-buffer.ts, modules/webgpu/src/adapter/resources/webgpu-command-encoder.ts
For #
- We need to use CommandEncoders for portably reading data and setting textures
-
=> chore(webgl): Consolidate CommandEncoder implementation and tests

modules/core/src/lib/luma.ts
Fix for https://github.com/visgl/luma.gl/pull/2173#discussion_r1721693707
- Declare variables to avoid crash in `'best-available'` branch
=> core: Fix crash when starting example without specified device

docs/api-reference/core/canvas-context.md, docs/api-reference/core/luma.md, modules/core/src/adapter/luma.ts
Fixes #1843
- Sometimes the DOM load event detection is defeated by other code.
- Provide a CreateDeviceProps option
=> feat(core): Option to not wait for page load

modules/webgl/src/context/helpers/create-browser-context.ts
=> fix(webgl): Better error messages when device creation fails

modules/core/test/adapter/resources/texture.spec.ts
Fixes #2115 
- 3d texture creation appears to be fixed in 9.1, this adds a test case.
-
=> test: Add test for texture creation(3d,r32float)

examples/tutorials/hello-gltf/app.ts, modules/gltf/src/gltf/create-gltf-model.ts, modules/gltf/src/pbr/parse-pbr-material.ts, modules/shadertools/src/index.ts, modules/shadertools/src/modules/lighting/pbr-material/pbr-fragment-glsl.ts, modules/shadertools/src/modules/lighting/pbr-material/pbr-material.ts, modules/shadertools/src/modules/lighting/pbr-material/pbr-projection.ts, modules/shadertools/src/modules/lighting/pbr-material/pbr-vertex-glsl.ts, modules/shadertools/src/modules/lighting/phong-material/phong-shaders-glsl.ts, modules/shadertools/test/modules/lighting/pbr-material.spec.ts
Cherrypick of https://github.com/visgl/luma.gl/pull/2173
@ibgreen Current output, have you seen something like this before?:
https://github.com/user-attachments/assets/f1552dd9-9039-495b-99ee-c3ea0f2e44b7
=> WIP shadertools: PBRMaterial UBO

modules/core/test/adapter/resources/framebuffer.spec.ts, modules/gltf/src/gltf/create-gltf-model.ts, website/yarn.lock
=> chore: Test if master is broken

modules/engine/src/compute/texture-transform.ts
- TextureTransform.destroy() should delete created resources
=> fix(engine): TextureTransform.destroy()

.github/workflows/test.yml, package.json
For #
- hard to separate logs 
- run lint after tests to reduce amount of pushes required to see actual test failures
-
=> chore: Separate lint step in CI

docs/api-reference/webgl/README.md, docs/api-reference/webgpu/README.md
- Clean up docs for accessing the underlying WebGPU and WebGL handles
-
=> docs: Clean up webgpu and webgl device docs

modules/engine/test/compute/buffer-transform.spec.ts, modules/engine/test/compute/texture-transform.spec.ts
=> chore(engine): Re-enable transform tests (async)

modules/core/src/adapter/canvas-context.ts, modules/core/src/adapter/device.ts
=> feat(core): CanvasContext tracks visibility and DPR changes

docs/api-reference/core/README.md, docs/api-reference/core/adapter.md, docs/api-reference/shadertools/shader-assembler.md, docs/upgrade-guide.md, docs/whats-new.md
=> docs: Update release notes for 9.1

docs/api-reference/core/resources/render-pipeline.md, docs/upgrade-guide.md, examples/tutorials/hello-gltf/app.ts, examples/tutorials/lighting/app-old.ts, modules/core/src/adapter/resources/render-pipeline.ts, modules/engine/src/model/model.ts, modules/engine/test/lib/model.spec.ts, modules/shadertools/test/modules-webgl1/fp64/fp64-test-utils-transform.ts, modules/test-utils/src/null-device/resources/null-render-pipeline.ts
For #
- Continued removal of WebGL only features
- remove .setUniformsWebGL and moduleSettings
=> chore: remove .setUniformsWebGL and moduleSettings

website/yarn.lock
=> fix: website beta build

modules/core/src/adapter/canvas-context.ts
=> fix(core): Avoid referencing HTMLCanvasElement in node

lerna.json, modules/constants/package.json, modules/core/package.json, modules/core/src/adapter/canvas-context.ts, modules/effects/package.json, modules/engine/package.json, modules/gltf/package.json, modules/shadertools/package.json, modules/test-utils/package.json, modules/webgl/package.json, yarn.lock
=> fix(core): CanvasContext node fixes

modules/core/src/adapter/canvas-context.ts
For #
- Protect references to OffscreenCanvas in Node.js
-
=> chore(core): Protect OffscreenCanvas reference in Node

docs/whats-new.md, modules/core/tsconfig.json, modules/effects/tsconfig.json, modules/gltf/src/gltf/create-gltf-model.ts, modules/gltf/src/gltf/gltf-animator.ts, modules/gltf/src/gltf/gltf-instantiator.ts, modules/gltf/src/pbr/parse-pbr-material.ts, modules/gltf/src/pbr/pbr-environment.ts, modules/gltf/test/gltf/gltf.spec.ts, modules/gltf/test/index.ts, modules/gltf/tsconfig.json, modules/test-utils/src/create-test-device.ts, modules/test-utils/src/snapshot-test-runner.ts, modules/test-utils/src/utils/deep-copy.ts, modules/test-utils/tsconfig.json, modules/webgl/src/adapter/converters/webgl-shadertypes.ts, modules/webgl/src/adapter/helpers/format-utils.ts, modules/webgl/src/adapter/resources/webgl-command-buffer.ts, modules/webgl/src/adapter/resources/webgl-render-pass.ts, modules/webgl/src/context/debug/spector-types.ts, modules/webgl/src/context/debug/webgl-developer-tools.ts, modules/webgl/src/context/helpers/webgl-extensions.ts, modules/webgl/src/context/parameters/unified-parameter-api.ts, modules/webgl/src/context/parameters/webgl-parameter-tables.ts, modules/webgl/src/context/polyfills/polyfill-webgl1-extensions.ts, modules/webgl/src/context/state-tracker/deep-array-equal.ts, modules/webgl/src/context/state-tracker/with-parameters.ts, modules/webgl/tsconfig.json, modules/webgpu/tsconfig.json, tsconfig.json
=> chore: TypeScript enable strict mode / noImplicitAny

modules/core/test/adapter/luma.spec.ts, modules/test-utils/src/index.ts, modules/test-utils/src/null-device/resources/null-render-pass.ts, modules/test-utils/src/register-devices.ts, modules/webgl/test/context/state-tracker/webgl-state-tracker.spec.ts
=> feat(test-utils): Avoid registering devices

modules/arrow/README.md, modules/arrow/package.json, modules/arrow/src/arrow/analyze-arrow-table.ts, modules/arrow/src/arrow/arrow-column-info.ts, modules/arrow/src/arrow/arrow-paths.ts, modules/arrow/src/arrow/arrow-types.ts, modules/arrow/src/index.ts, modules/arrow/test/arrow/analyze-arrow-table.spec.ts, modules/arrow/test/arrow/arrow-paths.spec.ts, modules/arrow/test/arrow/get-arrow-data.spec.ts, modules/arrow/test/data/arrow/make-arrow-tables.ts, modules/arrow/test/index.ts, modules/arrow/tsconfig.json, modules/core/src/index.ts, modules/core/src/shadertypes/utils/decode-data-types.ts, modules/core/src/shadertypes/utils/decode-shader-types.ts, modules/core/src/shadertypes/utils/decode-vertex-format.ts, modules/core/src/types.ts, modules/engine/README.md, test/modules.ts, tsconfig.json, yarn.lock
For #
- Separate module for extracting attribute data from arrow tables
- Goal is to minimize cross-dependencies, keep this module as an optional add-on.
- First in a series of PRs.
-
=> feat(arrow): Experimental module for Apache Arrow attribute data extraction

modules/engine/src/model/model.ts, modules/engine/src/shader-inputs.ts
For #
- Cherry pick #2300 into 9.1-release
-
=> feat(engine): Option to disable warnings in ShaderInputs (v9.1)

.github/workflows/test.yml
=> Downgrade ubuntu on GitHub CI to avoid "No usable sandbox!" error

.github/workflows/test.yml, docs/README.mdx, docs/api-reference/core/canvas-context.md, docs/api-reference/webgl/README.md, docs/api-reference/webgpu/README.md, docs/upgrade-guide.md, docs/whats-new.md, website/content/sidebar-examples.js, website/yarn.lock
=> 9.1 documentation polish

docs/developer-guide/installing.md
For #
Corrected adapter naming and fixed import paths in installing.md.
-Updated webgl2Adapter to webgpuAdapter in example code.
Fixed inconsistent import paths in TypeScript examples.
=> Fix syntax errors in docs/developer-guide/installing.md

.github/workflows/release.yml, .github/workflows/website.yml, modules/engine/src/shader-inputs.ts
Cherry pick from 9.1:
- https://github.com/visgl/luma.gl/pull/2314
- https://github.com/visgl/luma.gl/pull/2313
=> fix(engine): ShaderInputs ignore props with disableWarnings

modules/effects/package.json, modules/engine/package.json, modules/gltf/package.json, modules/shadertools/package.json, modules/test-utils/package.json, modules/webgl/package.json, modules/webgpu/package.json, yarn.lock
- modules/**/package.json peerDependencies
=> fix: peerDependencies should use production versions

docs/whats-new.md, package.json, yarn.lock
=> chore: Upgrade to TypeScript 5.7

examples/showcase/instancing/app.ts, modules/core/src/adapter/resources/render-pipeline.ts, modules/core/src/adapter/resources/vertex-array.ts, modules/webgpu/src/adapter/helpers/get-vertex-buffer-layout.ts, modules/webgpu/src/adapter/helpers/webgpu-parameters.ts, modules/webgpu/src/adapter/resources/webgpu-render-pass.ts
For #
- Mostly cherry-picks https://github.com/visgl/luma.gl/pull/2335
=> fix(webgpu): minor fixes for deck.gl enablement

examples/showcase/instancing/index.html, examples/tutorials/hello-gltf/app.ts, examples/tutorials/shader-hooks/app.ts, examples/tutorials/transform-feedback/app.ts, examples/tutorials/transform/app.ts, modules/core/src/adapter/device.ts, modules/engine/src/animation-loop/animation-loop.ts, modules/engine/src/animation-loop/make-animation-loop.ts, modules/webgl/src/adapter/resources/webgl-render-pipeline.ts, modules/webgl/src/context/debug/webgl-developer-tools.ts, modules/webgpu/src/adapter/resources/webgpu-buffer.ts, modules/webgpu/src/adapter/resources/webgpu-command-encoder.ts, modules/webgpu/src/adapter/resources/webgpu-render-pass.ts, modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts, modules/webgpu/src/adapter/resources/webgpu-shader.ts, modules/webgpu/src/adapter/resources/webgpu-texture-view.ts, modules/webgpu/src/adapter/resources/webgpu-texture.ts, modules/webgpu/src/adapter/webgpu-device.ts
For #
- Improvements to the error scope handling
-
=> chore(webgpu): Improve error handling

modules/engine/src/model/model.ts
For #
- Unblock WebGPU in deck.gl
-
=> fix: Extract shader layout after modules have been resolved

modules/core/src/adapter/device.ts
For #
- Found in https://github.com/visgl/hubble.gl/pull/285#discussion_r1940460265
- Add missing stencil prop
=> fix: add WebGLContextProps.stencil

modules/core/src/adapter/resources/texture.ts, modules/webgl/src/adapter/converters/webgl-texture-table.ts, modules/webgl/src/adapter/resources/webgl-texture.ts
=> fix: compressed texture fixes

modules/engine/src/async-texture/async-texture.ts
=> fix: Resolve AsyncTexture.ready

examples/tutorials/hello-gltf/app.ts, modules/engine/src/geometry/geometry.ts, modules/shadertools/src/lib/wgsl/get-shader-layout-wgsl.ts, modules/webgl/src/adapter/resources/webgl-texture.ts, modules/webgl/src/adapter/webgl-adapter.ts, modules/webgpu/src/adapter/webgpu-adapter.ts, package.json, yarn.lock
=> fix: Minor fixes

modules/experimental/src/index.ts, modules/experimental/src/textures/packed-pixels.ts, modules/experimental/src/textures/rgba-decoder.ts, modules/experimental/test/index.ts, modules/experimental/test/textures/packed-pixels.spec.ts, test/browser.ts, test/modules.ts, yarn.lock
For #
- Isolated experimental support for read/write of packed pixel formats
-
=> feat(experimental): Packed pixel fomat support

modules/core/src/index.ts, modules/core/test/index.ts, modules/engine/src/model/model.ts, modules/engine/src/utils/buffer-layout-helper.ts, modules/engine/src/utils/buffer-layout-order.ts, modules/engine/test/index.ts, modules/engine/test/utils/buffer-layout-order.spec.ts, yarn.lock
For #
- Because the core module should be small
-
-
=> chore(core): Move engine-specifc utils to @luma.gl/engine

examples/tutorials/hello-gltf/app.ts, examples/tutorials/hello-gltf/index.html
We are going to test all gltf features using hello-gltf example.
- Load model list
- Save last model and reload on refresh
=> hello-gltf: Load model list to populate drop down, sticky last model selection

.eslintrc.cjs, modules/engine/src/factories/pipeline-factory.ts, modules/engine/src/factories/shader-factory.ts, modules/engine/src/geometry/geometry.ts, modules/engine/src/model/model.ts, modules/shadertools/src/modules/engine/project/project.ts, modules/shadertools/src/modules/lighting/no-material/dirlight.ts, modules/shadertools/src/modules/lighting/pbr-material/pbr-projection.ts, modules/shadertools/test/index.ts, modules/shadertools/test/lib/shader-transpiler/transpile-shader.spec.ts, modules/shadertools/test/modules/engine/picking.spec.ts, modules/test-utils/src/performance-test-runner.ts, modules/webgl/src/adapter/webgl-device.ts, tsconfig.json, yarn.lock
For #
- Enable even more strict TS options.
-
=> chore: Enable noPropertyAccessFromIndexSignature TS option

modules/gltf/package.json, modules/gltf/src/gltf/create-gltf-objects.ts, modules/gltf/src/gltf/gltf-animator.ts, modules/gltf/src/gltf/gltf-instantiator.ts, modules/gltf/src/pbr/parse-pbr-material.ts, yarn.lock
=> add missing typescript types to modules/gltf

examples/tutorials/hello-gltf/app.ts, examples/tutorials/hello-gltf/index.html
- Fix Model Matrix math
- Add checkbox with option to enable gltf and camera animation
=> [hello-gltf] fix model matrix and enable animator

modules/shadertools/src/modules/lighting/pbr-material/pbr-material-wgsl.ts
For #
This PR brings contains partial fixes to bring the WGSL pbr-material shader in line with its GLSL counterpart. It fixes mismatched uniform names, uses the proper constants, and corrects typos in the pbr_setPositionNormalTangentUV and normal-fetching code. The goal is that both shaders behave equivalently.
-
=> fix(shadertools): pbrMaterial WGSL fixes

modules/gltf/src/gltf/create-scenegraph-from-gltf.ts, modules/gltf/src/index.ts, modules/gltf/src/parsers/parse-gltf-lights.ts, modules/gltf/test/gltf/lights.spec.ts, modules/gltf/test/index.ts, modules/shadertools/src/index.ts
For #
- Just extract luma.gl Lights definitions when parsing.
- 
-
=> feat(gltf): Support KHR_lights_punctual extension

website/src/react-luma/components/device-tabs.tsx, website/src/react-luma/store/device-store.tsx
For #
- Time to go WebGPU first
- Make the WebGPU tab the default tab.
=> webgpu now default in website

modules/effects/package.json, modules/engine/package.json, modules/gltf/package.json, modules/shadertools/package.json, modules/test-utils/package.json, modules/webgl/package.json, modules/webgpu/package.json
For https://github.com/visgl/deck.gl/issues/9793
- Update peer dependencies
=> Fix peer denpendencies for 9.2 release
