package.json

@ibgreen @philogb 
Makes `npm test` execute successfully again. See https://phabricator.babeljs.io/T6850 and https://phabricator.babeljs.io/T6745 for details.

update the test script command

---

examples/shadowmap/.babelrc
examples/shadowmap/index.html
examples/shadowmap/package.json
examples/shadowmap/src/index.js
examples/shadowmap/src/scene.fs
examples/shadowmap/src/scene.vs
examples/shadowmap/src/shadowmap.fs
examples/shadowmap/src/shadowmap.vs

@ibgreen @mikolalysenko
Should address https://github.com/uber-common/luma.gl/issues/22 and https://github.com/uber-common/luma.gl/issues/8

Adds a bare-bones shadowmap example using es6 imports.

---

README.md
docs/_config.yml
docs/_layouts/default.html
index.html
package.json

This PR fixes the static site generation for the docs on the GitHub pages and adds documentation links.
To run the static site generation, you need to install the `jekyll` and `pygments` ruby gems which can be done with the following command:
```sh
gem install jekyll pygments.rb
```
Once that's done, you can rebuild the static site using the following npm script:
```
npm run jekyll
```
This will create a folder called `_site` in the root directory which contains all the static content for the site.  To view the docs locally, you can also run jekyll as a standalone server with the command:
```
jekyll serve --source=docs/
```
CC @ibgreen @wwwtyro

Fix up jekyll site generation

---

src/webgl/texture.js

@ibgreen Fixes https://github.com/uber-common/luma.gl/issues/37

use texture flipY attribute in 2D textures

---

package.json
test/browser.js
test/electron.js
test/unit/index.js

This PR switches the default unit tests to [testron](https://github.com/shama/testron).  The existing browser and node tests are moved to separate test scripts.
With testron, we get full headless unit testing from the command line.  For example, here is what I get from the current test cases when I run them locally:
```sh
$ npm test
> luma.gl@0.0.2 test /Users/mikolalysenko/GitHub/luma.gl
> browserify test/electron.js | testron | faucet
✓ Utils#merge
✓ Utils#splat
✓ Utils#noop
✓ Utils#uid
✓ Math#types
✓ Vec3#members and methods
✓ Mat4#getters and setters
✓ Mat4#id (identity matrix)
✓ Mat4#set
✓ Mat4.add
✓ Mat4.transpose
✓ Mat4.mulMat42
✓ Mat4.rotateAxis
✓ Mat4.rotateXYZ
✓ Mat4.scale
✓ Mat4.translate
✓ Mat4.frustum
✓ Mat4.invert
✓ Mat4.lookAt
✓ Mat4.mulVec3
✓ Mat4.$mulVec3
✓ …
```

Use testron for unit testing

---

.travis.yml
package.json
test/unit/index.js
test/unit/testbuffer.js
test/unit/testmath.js
travis.yml

This PR sets up travis CI to work with luma.gl.  As a proof-of-concept I wrote a simple test case for buffers to show that things are working.
I tried a few times to get testtron working, but kept having weird issues where the test process would hang and not exit for like 20 minutes.  headless-gl works, though I need to fix the prebuilt binaries to work with the correct version of GLIBC on linux.
CC @ibgreen @philogb

Set up travis CI to work with headless-gl.

---

package.json

It appears that we build for distribution, but the package wasn't pointing to the built file.

Switch package main to compiled build

---

package.json
src/model.js
src/shaders/index.js

This patch upgrades glslify-babel to fix a problem with paths and also fixes up the usage of glslify in shaders/index.js.  (The .glsl extensions were missing)

Fix shader paths and upgrade glslify-babel

---

.gitignore
io/browser/browser-fs.js
io/browser/image-io.js
io/browser/index.js
io/index.js
io/io.js
io/load-files.js
io/node/image-io.js
io/node/index.js
package.json
src/webgl/buffer.js
src/webgl/context.js
src/webgl/draw.js
src/webgl/get.js
src/webgl/texture.js
test/browser.js
test/electron.js
test/gpu/index.js
test/gpu/read-texture.js
test/index.js
test/io/index.js
test/io/read-image.js
test/io/read-write-image.js
test/node/index.js
test/node/write-read-image.js

This PR adds a test case for image loading and also finishes the work in progress version on the browser side. 
Right now this PR works fine with browser and electron tests, but currently node is failing.  The reason for this is that I am getting some weird error involving `FileSaver.js`.  Here is a stack trace:
```
/Users/mikolalysenko/GitHub/luma.gl/node_modules/filesaver.js/FileSaver.js:22
doc = view.document
^
TypeError: Cannot read property 'document' of undefined
at /Users/mikolalysenko/GitHub/luma.gl/node_modules/filesaver.js/FileSaver.js:22:15
at Object.<anonymous> (/Users/mikolalysenko/GitHub/luma.gl/node_modules/filesaver.js/FileSaver.js:241:2)
at Module._compile (module.js:413:34)
at Module._extensions..js (module.js:422:10)
at Object.require.extensions.(anonymous function) [as …
```

Implement rest of image loading operations and add test case

---

src/webgl/context.js

gl.POINTS is 0x0000 and causes assert() to fail.

avoid throwing an error when accessing gl.POINTS

---

src/core/camera.js

Add high precision (fp64) projection matrix to Camera class for fp64 layers from deck.gl to function properly @gnavvy @ibgreen

Add the fp64 projection matrix to Camera so that FP64 layers in deck.gl can be enabled.

---

io.js
luma.js
probe.js
src/index.js
src/luma.js

Reduces dependencies for non-io luma.gl apps, and will hopefully mitigate some issues seen when importing luma in Node.js in isomorphic react apps.
io-less import should be made the default import in next major version of luma.gl. Did not want to break backwards compatibility now, so added new entry point.

Added luma.gl/luma import that does not include io

---

CHANGELOG.md
package.json
src/webgl/context.js
src/webgl/helpers/query-manager.js
src/webgl/index.js
src/webgl/timer-query.js
src/webgl2/query.js
src/webgl2/sampler.js
src/webgl2/sync.js
test/headless.js
test/webgl/helpers/query-manager.spec.js
test/webgl/index.js
test/webgl/texture-spec.js
test/webgl/timer-query.spec.js

- Add support for getting GPU timings via the `WebGL EXT_disjoint_timer_query` extension.
- Add a `TimerQuery` class for working with the extension timer objects.
- Add a `QueryManager` singleton that implements a general polling architecture for asynchronous queries.
- Update the WebGL2 `Query` class to also use `QueryManager`.
- Add `poll` function that uses `QueryManager` to update any pending queries.
- Add test case coverage for TimerQuery
@gnavvy @shaojingli

Add TimerQuery and PendingQueryManager classes

---

package.json
src/webgl/shader.js
src/webgl/webgl-format-glsl-error.js

@pessimistress @shaojingli - GLSL compiler errors stopped parsing correctly a while ago. Brought the parsing code into luma and fixed it. It seems that a junk character on the last line caused the empty line detection to fail.

Fix GLSL compiler error parsing. 

---

src/webgl/context.js

Firefox actually doesn't return null for  
```const info = gl.getExtension('WEBGL_debug_renderer_info');```
call even if WEBGL_debug_renderer_info is not supported.

Change the way WEBGL_debug_renderer_info extension is checked

---

src/experimental/event/test/headless/add-events.spec.js
src/experimental/event/test/headless/index.js
test/headless-nowebgl.js

> In addition to manual tests, it would be great with a CI sanity test script that just checked that imports are working and that addEvents is called without crashing.
I'm not sure how valuable this alone is. I can't see a way to add more useful tests without starting to mock whole DOM events - that doesn't seem like a good test. Is this single simple test worth adding?

Very basic test that addEvents doesn't crash.

---

src/webgl/context.js

This is why stuff like offsets on Intel GPU and wobble on Nvidia GPU come back.
@ibgreen @gnavvy @abmai

Fixed the glGetDebugInfo() function by using the correct constants.

---

src/core/model.js

Timer query using EXT_disjoint_timer_query. The implementation uses direct webgl calls instead of the TimerQuery class for simplicity. I'll do a cleanup of the TimerQuery class and migrate the code on top of it in the future.

Performance query using EXT_disjoint_timer_query

---

CHANGELOG.md
src/io/browser-load.js

Current config prevents from loading images from another domain (e.g. S3) as texture to layers like the IconLayer.
ref:
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

add CORS setting for image loading

---

package.json
src/core/model.js
src/debug/seer-integration.js
test/node.js
yarn.lock

Add integration with the soon-to-be born seer.
No performance drawback for production on normal users given the checks over its presence.
Pass the model uniforms and allow to modify some of it. Does not persist across renders given the deck.gl overriding most of it, but can be done if deemed necessary.

feat(dev): seer integration

---

src/webgl/context.js
src/webgl/draw.js

Cache glGetDebugInfo queries results
ATTN: this diff is targeting the 3.0-release branch

Remove assert checks in draw function when non-debug context is used

---

src/webgl/framebuffer.js
src/webgl/texture-cube.js
src/webgl/texture.js

Fix the framebuffer creation issue introduced by #172 
Also turn off default mipmap generation because WebGL has strict requirements on texture type / format / wrapping mode parameter combination for mipmap generation.
This is the root cause of https://github.com/uber/deck.gl/issues/653
@ibgreen @ericsoco

Fix framebuffer creation error introduced in #172

---

src/webgl/framebuffer.js
src/webgl/texture-cube.js
src/webgl/texture.js

Partially revert #177 by turning mipmap on by default
Framebuffer texture needs to have mipmap off due to its non-power-of-2 sizes

Fix the framebuffer creation issue by manually turning mipmap off

---

demo/package.json

Fix 'npm run build' command by removing 'build-static' command.

Fix 'npm run build' command

---

src/webgl/texture.js

https://github.com/uber/deck.gl/issues/683
The API for texture creation has changed between luma.gl v3 and v4. While this PR solves this, we should discuss if we'd like to keep the `pixel` parameter in our v4 release in an API audit later.
@1chandu @ibgreen @rivulet-zhang

Add the pixel parameter back in texture class for compatibility with v3

---

examples/lessons/04/app.js
examples/lessons/05/app.js
examples/lessons/06/app.js
examples/lessons/07/app.js
examples/lessons/08/app.js

All lessons are sharing same canvas hence same GL context. When switching from a lesson that enables blending to another lesson that doesn't causes problem. Disable blending on initialize for all lessons that don't need blending.

Fix blending in lessons

---

docs/api-reference/webgl/context-state.md
examples/lessons/01/app.js
examples/lessons/02/app.js
examples/lessons/03/app.js
examples/lessons/04/app.js
examples/lessons/05/app.js
examples/lessons/06/app.js
examples/lessons/07/app.js
examples/lessons/08/app.js
examples/lessons/09/app.js
src/index.js
src/webgl/context-state.js
test/webgl/context-state.spec.js

Context state management changes:
- 	Add 'resetContext' to set all gl states to default values.
- 	Call either glEnable or glDisable based on the value to be set.
- 	Fix default values for several gl states.

Context state management fixes.

---

src/core/animation-loop.js
src/webgl/uniforms.js

Fixes I found while debugging lesson16.
- animation-loop.json: When merging the appContext (returned from initializer), use the correct merging order so existing props in current context are overwritten by whats in appContext.
- uniforms.js: Fix a typo.

Misc fixes

---

docs/api-reference/webgl/framebuffer.md
docs/api-reference/webgl/texture.md
examples/lessons/03/app.js
examples/lessons/04/app.js
examples/lessons/09/star.js
examples/lessons/16/app.js
src/io/load-files.js
src/utils/utils.js
src/webgl/framebuffer.js
src/webgl/texture.js
test/node.js
test/setup/index.js
test/utils/utils.spec.js
test/webgl/texture.spec.js

- Remove NPOT (non power of two) texture workaround from framebuffer object and add it to texure2d object. Make it applicable for only webgl1 context and when texture is NPOT.
- Fix assert failures in few lessons.
- Note: Merge is pending until deck.gl picking is verified.

Add NPOT workaround for texture2d object.

---

docs/api-reference/webgl/query.md
src/core/model.js
test/webgl/index.js
test/webgl/query.spec.js

- Replace raw gl timer queries with Query object.
- Add more unit tests for Query class.

Enable Query object for model draw timing and add unit tests

---

src/shadertools/lib/shader-modules.js
test/shadertools/lib/index.js
test/shadertools/lib/shader-modules.spec.js

- When parsing module dependency graph, update level only if the existing level is lower.

Fix Shader module dependency ordering

---

src/geometry/geometry.js
test/shadertools/modules.js

- We are correctly checking for drawMode validity in `getDrawMode`.
- Comment out failing unit test case for lighting shader module.
@gnavvy this fixes crash when running wind particle layer.

Remove invalid assert on GL.POINTS

---

src/webgl-utils/create-context.js

This seems to be the issue why our deck.gl example doesn't run on Safari. WebGL context creation is all good but the deregistration of event handler seems to contain a typo. @Pessimistress

Fix the WebGL context creation issue on Safari

---

src/core/model.js

* Now that `project` module is added by default, call `assembleShaders` even when no modules are supplied to `model` object.
* Tested with : test-browser, examples and lessons.

ShaderModule: Call assembleShaders always

---

examples/core/instancing/app.js
examples/core/picking/app.js
src/core/pick-models.js
src/shadertools/modules/picking/picking.js

- Instead of overloading `pickingSelectedColor` with a unique null color value (`pickingNullColor`), use a boolean enum, `pickingValid`. This way it is more clear and within the shader we only do boolean check instead of vec3 compare.
- Do not highlight models when `pickingValid` is false.
- Update picking/instancing apps to listen to `mouseleave` events and set pickPosition to null.
- Tested with picking/instancing core examples.
@shaojingli we need this to be ported to release branch.

Picking shader module: Handle invalid/null picking color

---

src/webgl/buffer.js

Fix for #291 
Tested with deck.gl/website layer examples and deck.gl/example/layer-browser.

bufferData workaround to fix Safari crash.

---

src/webgl/buffer.js

- Cherry picking #292 from master into 4.0-release branch.

bufferData workaround to fix Safari crash. (#292)

---

CHANGELOG.md
docs/api-reference/core/model.md
examples/core/cubemap/webpack.config.js
examples/core/fragment/webpack.config.js
examples/core/instancing/webpack.config.js
examples/core/mandelbrot/webpack.config.js
examples/core/picking/app.js
examples/core/picking/webpack.config.js
examples/core/shadowmap/webpack.config.js
examples/core/transform-feedback/webpack.config.js
examples/lessons/01/webpack.config.js
examples/lessons/02/webpack.config.js
examples/lessons/03/webpack.config.js
examples/lessons/04/webpack.config.js
examples/lessons/05/webpack.config.js
examples/lessons/06/webpack.config.js
examples/lessons/07/webpack.config.js
examples/lessons/08/webpack.config.js
examples/lessons/09/webpack.config.js
examples/lessons/16/webpack.config.js
src/core/model.js

Verified using examples, lessons and test-browser.
Update picking example to verify cache hit.
Update webpack.config files of examples, so `npm run start-local` works.
Fixes #299

Use shaderCache to avoid re-compilaiton of same shader.

---

docs/api-reference/shadertools/README.md
src/shadertools/lib/assemble-shaders.js
test/shadertools/lib/assemble-shaders.spec.js
test/shadertools/lib/index.js

Fixes #304
Tested with test-browser and lesson04 update to use GLSL 3.0 shaders.

Keep version directive at the beginning of the shader during assembly.

---

examples/lessons/10/app.js
examples/lessons/11/app.js
website/package.json
website/webpack.config.js

After cleaning up all the dependencies under examples/lessons/10/node-modules, found the website testing failed for lesson10 because of missing "math.gl", figured out we need add "math.gl" dependency for website project.

Add "math.gl" dependency for website

---

docs/api-reference/webgl/buffer.md
src/webgl/buffer.js
test/webgl/buffer.spec.js

Fix for #314
- Optimize ArrayBufferView allocation when it is not provided.
- Add additional asserts to fire on invalid combination of parameters to `getBufferSubData` (WebGL documentation is very confusing, this should help our users.)
- Update docs for `copyData` and `getData` with simple use cases.

Fix buffer.getData default parameters and target setting.

---

src/core/model.js
src/index.js
src/utils/index.js
src/utils/log.js
src/utils/typed-array-utils.js
src/webgl-utils/polyfill-context.js
src/webgl-utils/polyfill-get-parameter.js
src/webgl-utils/set-parameters.js
src/webgl-utils/track-context-state.js
src/webgl/clear.js
src/webgl/context-state.js
src/webgl/framebuffer.js
src/webgl/program.js
src/webgl/resource.js
src/webgl/shader.js
src/webgl/texture.js
src/webgl/transform-feedback.js
src/webgl/uniforms.js
test/webgl/context-state.spec.js
test/webgl/framebuffer.spec.js

* Prevent `AnimationLoop` from creating unused framebuffer
* Add `defaultFramebuffer` object, allowing the default framebuffer to be manipulated using the `Framebuffer` class methods.
* Add `readDataUrl` and `readImage` methods, read out texture to HTML Image
* Fixes to `blit` and `getAttachmentParameter`

Framebuffer fixes

---

src/webgl/transform-feedback.js
test/webgl/index.js
test/webgl/transform-feedback.spec.js

The returned value (WebGL extension) is consistent with the behavior of other classes' `isSupported` methods, though we really should convert it to `Boolean` for a cleaner interface.

Fix `TransformFeedback.isSupported` bug

---

examples/core/instancing/app.js
src/core/model.js
src/shadertools/modules/picking/README.md
src/shadertools/modules/picking/picking.js

- Copy enhanced picking module from deck.gl to luma.gl
- Fix documentation.
Fix for #890.
Next step:  Remove picking module from deck.gl. (Once this change is published in an alpha release)
Verified with, `test-browser`, `examples`.

Picking module from deck.gl

---

src/webgl/framebuffer.js

- Avoid framebuffer logging when priority is not set.
Verified with `test-browser`, `examples`, framebuffer logging using shadowMap example.

Fix performance in picking path

---

src/utils/log.js

Warning messages were cached, but `log.warn` did not check cache before printing to console.
Fixes https://github.com/uber/luma.gl/issues/340.

Do not issue duplicate warnings

---

src/core/model.js

In deck.gl#1045 PR, all examples are upgraded to use luma.gl `picking` module, but external apps might still be using old custom picking uniforms (which are always set), to avoid un-necessary warning disabling these deprecated warning for now, will re-enable in next major release.

Disable picking uniform warnings

---

src/shadertools/lib/platform-defines.js
src/shadertools/modules/fp32/fp32.js
src/shadertools/modules/fp64/fp64-arithmetic.glsl.js
src/shadertools/modules/fp64/fp64-functions.glsl.js
src/utils/log.js
src/webgl-utils/format-glsl-error.js
src/webgl/context.js
test/webgl-utils/format-glsl-error.spec.js
test/webgl-utils/index.js

Clean up the platform specific macro definitions.
Currently, there are two defs in our 64 bit shader files that always defined together 
#define NVIDIA_FP64_WORKAROUND 1
#define NVIDIA_EQUATION_WORKAROUND 1
this might stem from different versions of 64-bit shaders, so I consolidated them. 
Moreover, the defs on the Intel platform is not effective as "NVIDIA_EQUATION_WORKAROUND" is used there, obviously a careless copy-paste mistake. I fixed it.
I will try to test this change on all platforms available to me tomorrow, before land it.
This fix might be related to https://github.com/uber/deck.gl/issues/1071 and should be cherry-picked to the release branch as well.

Fix the platform define

---

examples/lessons/01/index.html
examples/lessons/02/index.html
examples/lessons/03/index.html
examples/lessons/04/index.html
examples/lessons/05/index.html
examples/lessons/06/index.html
examples/lessons/07/index.html
examples/lessons/08/index.html
examples/lessons/09/index.html
examples/lessons/16/index.html

There was an errant character in many examples causing an annoying page scroll. Fixed with:
`grep -r -l "</head>a" ./ | xargs sed -i 's/head>a/head>/g'`

Remove errant character in examples

---

docs/api-reference/shadertools/shader-cache.md
src/core/model.js
src/shadertools/lib/shader-cache.js
src/utils/log.js
src/webgl/context-debug.js
src/webgl/program.js
test/shadertools/lib/shader-cache.spec.js

Fix for deck.gl issue : https://github.com/uber/deck.gl/issues/1126
Turns out creating and linking Program object for 64 bit shaders take a long time, add caching support for Program object hence, program linking is done only once per a given combination of vertex and fragment shaders.
Verified with `layer-browser`, `examples(website)` and  deck.gl `PolygonLayer` rendering when enabling `fp64` prop.
**Without this fix :**
- toggle to fp64 first time : **659.33** ms
- toggle to fp64 second time : **556.93** ms
**With this fix :**
- toggle to fp64 first time : **590.11** ms
- toggle to fp64 second time : **84.40** ms

ShaderCache: Add support for Program objects

---

src/webgl/program.js

- Rename private methods and move relevant code into them.
- Query attribute/uniform count only once.
Tested with all examples on website.

Program: Enhancements to attribute/uniform locations map setup.

---

examples/core/instancing/app.js
examples/core/picking/app.js
src/index.js
src/shadertools/modules/picking/picking.js

* Remove `PICKING_NULL_COLOR` const and use `null` instead.
* Rename `picking_uSelectedPickingColorValid` -> `picking_uSelectedColorValid`,  `picking_uSelectedPickingColor` -> `picking_uSelectedColor`
* Fix a minor issue with div positioning in `picking` example.
Verified with all examples (including `picking` and `instancing`).

Picking null color

---

examples/core/cubemap/app.js
examples/core/fragment/concentrics-demo.js
examples/core/mandelbrot/app.js
examples/lessons/06/app.js
examples/lessons/07/app.js
examples/lessons/08/app.js
examples/lessons/09/app.js
examples/lessons/09/star.js
examples/lessons/16/app.js
examples/test/tree-shaking/app.js
src/geometry/geometry.js

* Remove deprecated api usage in examples
* Geometry: Fix when to log a attribute deprecation message.
Verified with examples.

Remove deprecated api usage

---

src/shadertools/lib/platform-defines.js

* When GPU/Render info not avilable, apply Intel Tan shader workaround.
Possible fix for https://github.com/uber/deck.gl/issues/1216
Verified with test-browser and examples.

Add Intel Tan Shader WA for default GPU

---

src/webgl/uniforms.js
test/bench/index.js
test/bench/uniforms.bench.js
test/webgl/uniforms.spec.js

The methods accept either a Float32Array or an array of numbers: [uniformMatrix](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniformMatrix), [uniform](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniform)
Node / WebGL1:
| Test | Result |
| ----- | ------ |
| Set vec3 uniform from Float32Array | 870k iterations/s (0.12s) |
| Set vec3 uniform from cloned Float32Array | 467k iterations/s (0.21s) |
| Set vec3 uniform from array | 794k iterations/s (0.13s) |
| Set vec3 uniform from new Float32Array | 505k iterations/s (0.20s) |
| Set mat4 uniform from Float32Array | 422k iterations/s (0.24s) |
| Set mat4 uniform from cloned Float32Array | 311k iterations/s (0.32s) |
| Set mat4 uniform from array | 389k iterations/s (0.26s) |
| Set mat4 …

Improve perf of uniform setters

---

src/utils/log.js
src/webgl/context.js

* We are missing out this crucial GL Context info when our users report issues.
Tested with examples.

Log GL Context info

---

src/shadertools/lib/platform-defines.js

* When GPU/Render info not avilable, apply Intel Tan shader workaround.
* I would also port this to 4.0-release branch.
Possible fix for https://github.com/uber/deck.gl/issues/1216
Verified with test-browser and examples.

Enable Intel Tan shader WA for default GPU

---

src/core/model.js
src/webgl/program.js
src/webgl/vertex-array.js
test/webgl/vertex-array.spec.js

- Fix: `VertexArray.setGeneric`
- New: `isGeneric` flag in attribute definition. If `true`, treat attribute as generic. `attribute.value` must be a typed array of size 1-4 in this case.

Fix generic attribute support

---

docs/api-reference/core/model.md
docs/whats-new.md
src/core/model.js

- `draw` calls `this.render(uniforms, attributes, samplers)` without the `parameters` argument
- `render` never uses `attributes` and `samplers`
- `setProgramState` uses `this.samplers` which is never defined
https://github.com/uber/luma.gl/issues/269
Tested: node, browser, website examples

Fix `model.render` inconsistencies

---

src/core/model.js
src/webgl/uniforms.js
test/webgl/uniforms.spec.js

Default calls to `updateModuleSettings` call `setUniforms` which causes deck.gl to redraw even if no uniform is changed.

Do not mark `needsRedraw` unless something changed

---

src/webgl-utils/create-canvas.js

fixes bug where promise never resolves on pages that are loaded already (https://github.com/uber/deck.gl/issues/1293)
also should potentially fix issues with hot reloading code where this will be re-executed
in the future i would recommend moving off `window.onload` and add some error handling/timeouts for this promise

closes https://github.com/uber/deck.gl/issues/1293

---

docs/api-reference/core/model.md
docs/api-reference/webgl/program.md
docs/api-reference/webgl/transform-feedback.md
src/core/model.js
src/webgl/context-state.js
src/webgl/program.js
src/webgl/transform-feedback.js
test/webgl/context-state.spec.js
test/webgl/program.spec.js
test/webgl/transform-feedback.spec.js

- Add TF support to Model class.
- Move `withParameters` from` Model.draw` to `Program.draw`, so temporary state settings can be applied in both case.
- Return early (no state push/pop) from `withParametes` when `parameters` object is empty.
Verified using test-browser, examples and deck.gl Wind example.

Transform Feedback: Add Support to Model.draw and minor API changes.

---

src/shadertools/lib/platform-defines.js
src/shadertools/modules/fp64/fp64-arithmetic.glsl.js

With intel GPU on macbook, the high bits of our simulated double precision float number in GLSL have overflow which makes mul_fp64, div_fp64 and sqrt_fp64 all fail.

Fix overflow of 64 bits shader on intel GPU

---

examples/core/transform-feedback-instanced/app.js
examples/core/transform-feedback/app.css
src/core/model.js
src/utils/utils.js
src/webgl/context-state.js
src/webgl/program.js
src/webgl/vertex-array.js
website/contents/demos.js
website/contents/pages.js

- Add a method to`VertexArray` to query currently bound attribute locations.
- In `Program`, get bound locations data from `VertexArray` object (custom or default), to generate warnings on unbound locations.
- When clear is requested, we were only clearing internal object but not clearing actual buffer bindings, added a new method to `VertexArray` to do it.
- Do not crash if Model is created without a `Geometry` object.
Tested with examples, test-browser.
Fixes #387

Vertex array api

---

CHANGELOG.md
src/core/animation-loop.js

Parameters must be independently settable. This issue is causing problems for deck.gl auto resize feature. 
This is as small fix for 5.1, will open a more extensive PR for 5.2.

Fix animation loop parameter setting

---

test/webgl/uniforms.spec.js

https://github.com/uber/luma.gl/issues/412
Chrome's shader optimization removed uniforms that do not contribute to the final output (`gl_FragColor`)

Fix browser test

---

src/core/model.js

Fix crash, that happens when a `Model` object is created without a `Geometry` object.
More context:
All of our layers use geometry object, but for GPGPU features I am creating `Model` object without geometry (attributes, and vertex counts are updated after `Model` object is created).
Verified running unit tests.

Fix a crash when Model object created without geometry.

---

src/index.js
src/shadertools/modules/lighting/lighting.js
src/webgl-utils/index.js
src/webgl/index.js

Fixed some invalid exports of undefined modules, add the default export of the lighting shader module.
In addition, `Euler` and `SphericalCoordinates` have been removed from `math.gl`

Fix exports

---

docs/api-reference/core/experimental/transform.md
src/core/experimental/transform.js
test/core/experimental/transform.spec.js

For #401
Add a new method, `updateBuffers` to handle the use cases , where one or more buffer bindings can be updated while keeping the others as is.
Updated unit tests and documentation.
Verified with unit tests, TF examples, and deck.gl attribute transitions.

Transform: Add updateBuffers method

---

src/webgl-utils/set-parameters.js

For #435 
Enums used for reading Framebuffer binding are compatible between WebGL1 and WebGL2 as they have the same value.
```
const GLenum DRAW_FRAMEBUFFER_BINDING = 0x8CA6;
const GLenum FRAMEBUFFER_BINDING            = 0x8CA6;
```
But it is not the same case for enums used in setting the Framebuffer bidning:
```
const GLenum FRAMEBUFFER                    = 0x8D40
const GLenum DRAW_FRAMEBUFFER        = 0x8CA9
```
Use the correct target when updating the framebuffer binding.
-  Fix framebuffer target for WebGL1 context
Verified using existing unit test on Safari(WebGL1) and Chrome(WebGL2).

Fix framebuffer target for WebGL1 context

---

src/webgl/context.js
test/webgl/uniforms.spec.js

For #443
Fix `test-browser` test failures.
Looks like shader compiler is optimizing unused uniform variables, re-adjust the instructions so all uniforms can be tested.
- Fix Math.max call
- Fix uniform tests

Fix uniform unit tests

---

src/webgl/helpers/attribute-utils.js
src/webgl/program.js
test/src/webgl/context-features.spec.js

For #
Fix couple of regressions in `test-browser` tests with latest changes in luma.gl
1. Fix argument for `getPrimitiveDrawMode`
2. Disable crashing unit tests `webgl#caps#canCompileGLGSExtension`, which also causes other tests to fail. (tracked by #457)
-

Fix test-browser regressions

---

docs/api-reference/webgl/framebuffer.md
docs/whats-new.md
src/webgl/framebuffer.js
src/webgl/helpers/format-utils.js
test/src/webgl/framebuffer.spec.js

For #451 
WebGL2 adds new buffer binding point `PIXEL_PACK_BUFFER`, that can be used to read data from `Framebuffer` object into a `Buffer` object without syncing CPU with GPU. This will keep the data in GPU memory and could increase application performance in some cases.
- Add asynchronous mode for `Framebuffer.readPixels` method.

WebGL2 : Add asynchronous mode for readPixels using PBOs.

---

src/shadertools/lib/shader-cache.js
src/webgl/program.js
test/shadertools/lib/shader-cache.spec.js
test/webgl/program.spec.js

* Do not delete Program objects while they are cached.
For # https://github.com/uber/deck.gl/issues/1581
Port #467 to 5.1-release branch.
- Do not delete Program objects when they are cached.

Do not delete Program objects (#467)

---

src/webgl/uniforms.js

For #470
In #460 we changed single uniform value checking from `isFinite()` to more strict `Number.isFinite()`,  this doesn't allow `null` value for uniforms. This is causing deck.gl `render-test` fail since `outline` shader is using null value for `outline_uShadowmap` (default value), but within the shader this uniform is ignored using `outlineEnabled` uniform.
This may be true in other shder modules, until we enforce no 'null' value for all uniforms in all modules we should allow `null` values for uniforms.
- Allow null uniforms

Allow null uniforms

---

.travis.yml
package.json
yarn.lock

Add browser based unit tests to regular npm test which is integrated with "git commit", with this we can have better check to prevent regression.
- Bump probe.gl to 1.0.0-alpha.11 which has some improvements to fix issues in test-browser
- Add test-browser to npm test

Integrate test-browser with "git commit"

---

examples/core/instancing/app.js
src/shadertools/modules/picking/README.md
src/shadertools/modules/picking/picking.js

Add a convenience method in picking module , that can be used when highlighting enabled with no custom filters. 
- PickingModule: Add picking_filterColor method

PickingModule: Add picking_filterColor method

---

.babelrc
src/webgl/framebuffer.js

For #495
- readBuffer API does not return a value.
- Fix to Framebuffer.blit
- Remove debug setting from `.babelrc` to reduce console noise when building.

Fix browser test of Framebuffer.blit

---

src/shadertools/modules/picking/picking.js

For #432
https://github.com/uber/deck.gl/blob/1caf4b2b50fef27c526498e22eea75eb77befb6a/dev-docs/RFCs/v5.3/picking-overlapping-objects-rfc.md
- Add discard when picking color is all zero

Add discard too picking.js fragment shader

---

docs/api-reference/models/cylinder.md
src/geometry/truncated-cone-geometry.js

`CylindarGeometry` and `ConeGeometry` are currently aligned with the y axis and cannot be rotated.
For example, deck.gl's HexagonLayer must manually rotate the cylindar geometry in vertex shader so that vertical is aligned with the z axis.
- Add `verticalAxis` option to `TruncatedConGeometry` constructor
- Update docs

Add verticalAxis opt to TruncatedConeGeometry

---

src/shadertools/modules/fp64/fp64-utils.js
src/shadertools/modules/fp64/fp64.js

The fp64 shader module should be the source of utils that convert a float/matrix4 to compatible 64-bit representations.
- Extend existing `fp64ify` util
- Add `fp64LowPart` and `fp64ifyMatrix4` utils

Port fp64 utils from deck.gl

---

docs/api-reference/core/experimental/transform.md
src/core/experimental/transform.js
src/core/model.js

For https://github.com/uber/deck.gl/issues/1797 - attribute transition to/from generic values
`sourceBuffers` are set as attributes to the model and can be `Buffer`, `Attribute` or a plain descriptor object. `destinationBuffers` are rendered to and must be `Buffer` objects. This PR defers asserting the type of a `sourceBuffer` until it is used as a `destinationBuffer`.
- Relax requirements for `sourceBuffers` in `Transform` class
- Fix bug in `model._createBuffersFromAttributeDescriptors` where `isGeneric` flag is not cleared when applying external buffers

Allow non-buffer supplied to Transform's sourceBuffers

---

src/webgl-context/context-features.js
test/src/webgl-context/context-features.spec.js

For #457 
Sorry for breaking the browser tests!
- Override userAgent check in `isOldIE` method through `opts` parameter.
Before I noticed that @ibgreen introduced the `opts` param to "inject" the user agent into the `isOldIE` method, I had tried another method that is a bit more complicated but has the benefit of localizing the override as well as not requiring us to pass the test options through the call stack. Code looks like the following:
Add helper method to mock userAgent. This is necessary because `window.navigator` is not writable in the browser environment which is why the tests were only failing when running in the browser.
```
// Helper method to allow us to mock the userAgent across node and browser tests.
function mockUserAgent(value) {
if (!window.navigator) { …
```

Fix failing canCompileGLGSExtension browser test

---

docs/api-reference/shadertools/glsl-reference.md

- Building out support for making our shader modules work in both GLSL 3.00 and 1.00.
- Having clear documentation about what the differences are is a first step.
- Most existing sources either describe 1.00 or 3.00 or just provide a brief list of differences.
- Hard to get the full picture, so created this page by combining info from Khronos docs.
- Add GLSL reference page.

Add GLSL 3.00 vs 1.00 reference

---

src/shadertools/src/lib/assemble-shaders.js
src/shadertools/src/lib/platform-defines.js
src/shadertools/src/lib/shader-cache.js
src/shadertools/src/lib/shader-modules.js
src/shadertools/src/utils/assert.js
src/shadertools/src/utils/is-old-ie.js
src/shadertools/src/utils/webgl-info.js
src/shadertools/test/utils/is-old-ie.spec.js
test/index-webgl-dependent-tests.js
test/src/shadertools/index.js

For #531
- Make shadertools independent of luma.gl `assert` and `hasFeatures`
- as above

Preparations to make shadertools independently publishable

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v6.0/offscreen-render-rfc.md
dev-docs/RFCs/v6.0/portable-glsl-300-rfc.md
dev-docs/RFCs/v6.0/vertex-array-attributes-rfc.md

- Two new RFC placeholder drafts (portable GLSL 3.00 shader modules, centralize attribute management in VertexArray).
- Also some edits dev-docs/RFC README.

New RFCs for v6.0

---

src/webgl-context/polyfill-context.js
src/webgl-context/polyfill-vertex-array-object.js
src/webgl-utils/index.js
src/webgl/vertex-array.js
test/src/webgl/vertex-array.spec.js

For #535 (RFC)
- Need `VertexArray` to always work
- Add Khronos client side polyfill for `VertexArrayObject` extension

Add Khronos VertexArrayObject polyfill

---

examples/core/transform/app.js
src/shadertools/src/modules/picking/picking.js

For #537
Update picking module to use 300 syntax, module source will be converted to 100 or 300 by the tranpiler (#542)
Verified with:
- Instancing demo :  Picking shader code is converted from 300 to 100 syntax.
- Transform demo:   Picking shader code is converted from 300 to 300 syntax.
- Update picking module to use GLSL 300 syntax
- Enable picking for Transform demo

Update Picking Module to use GLSL 300 syntax

---

src/core/model.js

Avoid a crash and prints useful debug data, when using external buffers , specifically in GPGPU cases, buffer is created on GPU hence no `data` field available.
- Fix log when using External buffer

Fix log when using External buffer

---

dev-docs/RFCs/v5.2/enhanced-transform-feedback-api-rfc.md
docs/api-reference/core/transform.md
examples/core/transform/app.js
src/core/transform.js
src/webgl/transform-feedback.js
test/index-webgl-dependent-tests.js
test/setup/index.js
test/src/core/transform.spec.js
test/src/io/read-texture.js
test/src/shadertools/index.js
test/src/webgl/draw.spec.js
test/src/webgl/framebuffer.spec.js
test/src/webgl/sampler.spec.js
test/src/webgl/texture-2d-array.spec.js
test/src/webgl/transform-feedback.spec.js

- Replace `varyingMap` with program configuration
- Rename `sourceDestinationMap` to `feedbackMap`
- TransformFeedback setBuffer / bindBuffer distinction.
- Create less contexts during testing

Additional Transform and TransformFeedback cleanup

---

examples/core/cubemap/app.js
examples/core/instancing/app.js
src/core/animation-loop.js
src/core/model.js
src/core/pick-models.js
src/index.js

- Reorganize/Clean up `model.js`
- Rename and make `AnimationLoop.animationProps` available to `Model`
- Move around code in two examples to reduce diff size in coming PR.
- Make `AnimationLoopProxy` into experimental export.

Model, AnimationLoop - Code reorganization

---

docs/api-reference/webgl/vertex-array.md
docs/whats-new.md
src/core/attribute.js
src/webgl/vertex-array.js
website-ocular/TODO.md

For #
- Support specifying separate accessor info in `VertexArray.setAttributes({name: [buffer, accessor]})`
- `Attribute`: Ensure that the original attribute settings are used when setting shared buffers.

Fix buffer reuse

---

docs/api-reference/core/attribute.md
src/core/attribute.js
src/core/model.js
test/src/core/attribute.spec.js
test/src/core/model.spec.js

Once `attribute.buffer` is created, `getValue()` never returns the generic value even if `isGeneric` is updated to `true`.
- Fix `attribute.getValue`
- Add tests

Fix generic attribute bug

---

src/core/model.js
src/shadertools/src/lib/inject-shader.js

- Pass `inject` parameter from model to `assembleShader`
- Make declaration injection work with WebGL1 shaders

Fix shader injection

---

src/core/transform.js
test/src/core/transform.spec.js

For #576 
- Separate out auto feedback buffer creation.
- Seperate out swap buffers setup.
- Initiate swap buffers code on first usage.
- Disable swap buffers when any of the source buffers is not a `Buffer` type.
- Delete auto created buffer when new one is created, instead of accumulating.
- Add more tests cases to cover `Attribute` usage.
- Cleanup swap buffers code, fix swapBuffers flag.

Transfrom: swap buffers cleanup

---

docs/api-reference/webgl/buffer.md
src/core/transform.js
src/webgl/buffer.js
test/src/webgl/buffer.spec.js

For #591 
- Add `getElementCount` method to Buffer class. Element count is determined by `bytes` and `type`.
- Fix an issue where `type` needs to be deduced from `accessor`.
- Update `Transform` to use `accessor` instead of  removed `layout` object.
- Buffer: add getElementCount method.

Buffer: add getElementCount method.

---

src/core/model.js

Breaks deck.gl's `layer.draw` when multiple models share the same draw options.
- Avoid mutating draw options with model specific data

Fix multi-model render bug

---

src/webgl/uniforms.js

For #601
Fixes an issue when `float` uniform is set to a `true` or `false` value.
Related to #594 
Earlier to #594 scalar uniforms wer set using `gl.uniform1f(location, v0)`, this worked when setting `true/false` value ,   but to enable setting scalar array uniforms we replaced `gl.uniform1f` to `gl.uniform1fv`, hence we need to convert boolean value to Number before converting it to an array.
-  Fix: convert boolean uniforms to Numbers

Fix: convert boolean uniforms to Numbers

---

docs/api-reference/webgl/context/get-parameters.md

Corrects a simple typo in the link for the `blendFuncSeparate` GL function in the docs. It was previously pointing to the wrong MDN article, `blendEquationSeparate`.

Correct MDN link for blendFuncSeparate in docs

---

src/shadertools/src/modules/fp64/fp64.js

For #621 
`fp64` shader module uses `ONE` uniform for implementing `LUMA_FP64_CODE_ELIMINATION_WORKAROUND` that is applied to specific Intel and Nvidia GPUs. Move the uniform generation code to module, so users (layers/demos) using this module doesn't have to set it explicitly.
- Shader Module fp64: add const uniforms used in shader WAs

Shader Module fp64: add const uniforms used in shader WAs

---

docs/developer-guide/building-apps.md
modules/core/.babelrc
scripts/collect-metrics.sh
test/size/import-nothing.js
test/webpack.config.js
yarn.lock

- More detailed bundle size metrics, including both prod and dev builds
- `collect-metrics` script
- Developer's Guide docs
- Add `"comments": false` to .babelrc to reduce size of development builds
- increase the amount of code bundled by size test app by importing `Model` and `AnimationLoop`, to give more representative bundle sizes.

Improve bundle size metrics

---

modules/core/package.json
yarn.lock

- Take advantage of new math.gl library that has been tuned for tree-shaking and size reductions.
- Bump version
Before
After

Bump math.gl to 2.1.0-alpha

---

docs/api-reference/core/transform.md
docs/whats-new.md
modules/core/src/core/transform.js
modules/core/src/shadertools/src/modules/fp64/fp64-test-utils.js
modules/core/src/shadertools/test/index.js
test/index-webgl-dependent-tests.js
test/modules/core/shadertools/fp64/fp64-arithmetic-transform.spec.js
test/modules/core/shadertools/fp64/fp64-test-utils-transform.js
test/modules/core/shadertools/index.js

For #630 
- Add support for `modules` for `Transform` class.
- Port old FP64 tests using new `Transform` class.
- Fix error checking when reference value is < 1, do not take relative error as division by a value less than 1 is increasing the error value. In those cases just use the difference between actual and reference value. This was the reason most tests are failing in old script.
- Instead of testing random floats, collect most possible cases and build test cases.
- Add ability to disable tests per glslFunc and per GPU as there are several failures on `Intel` gpu.
- Document error margin for each failing test so these can be debugged later.
- Transform: add modules parameter
- FP64: Add Transform based unit testing

FP64: Unit tests using `Transform`

---

scripts/collect-metrics.sh
test/size/import-nothing.js
test/webpack.config.js

- Backport of #627 to 6.0-release so that we can make apples-to-apples comparisons.
- collect-metrics script.
- increase the amount of code bundled by size test app by importing `Model` and `AnimationLoop`, to give more representative bundle sizes.

v6.0: More comprehensive metrics collection

---

package.json
src/webgl-context/create-headless-context.js
src/webgl-utils/webgl-types.js

Fixes #620 
- List "gl" as `"browser": false` in `package.json` to prevent it being bundled by latest webpack version that implements `module.require`.
- Consolidate "gl" loading into a single file.

v6.0 Mark gl import as "server only" using package.json "browser" field

---

modules/babel-plugin-inline-gl-constants/src/inline-gl-constants.js
modules/core/src/webgl/accessor.js
modules/core/src/webgl/texture.js

Now generates errors on illegal values during transpilation, instead of just leaving them in the source.

Fix babel gl inlining

---

modules/core/src/webgl/vertex-array.js

`Buffer.type` no longer exists

Fix VertexArray bug where indexType is undefined

---

website/src/components/Hero.js
website/src/components/info-panel.js
website/src/react-demo-runner.js
website/src/react-demos-require.js
website/src/styles/index.scss

This PR puts the info panel back in the luma.gl examples. 
It also streamlines the infoPanel component compared to the earlier version.

this adds the info panel component in luma.gl demos.

---

modules/loaders.gl/.babelrc
modules/loaders.gl/src/gltf-instantiator/gltf-instantiator.js
package.json
yarn.lock

For #
- Current loaders.gl code didn't transpile to `es5`  
- add `modules/loaders.gl/.babelrc`
- add a babel dev dependencies in `./package.json` to support loaders compile

add loader .babelrc to fix es5 transpile

---

modules/loaders.gl/package.json
modules/loaders.gl/src/common/loader-utils/load-uri.js
modules/loaders.gl/src/gltf-instantiator/gltf-instantiator.js

- Avoid bundling `fs` in browsers
- package.json `browser` field and conditional require

loaders.gl: Exclude `fs` in browsers

---

modules/core/src/core/transform.js
test/modules/core/core/transform.spec.js

Remove assert for existence of `sourceBuffers`. In some cases data could be sourced from uniforms or hard coded in the shader. (mostly for unit tests)
- Transform: remove assert on sourceBuffer

Transform: remove assert on sourceBuffer

---

.travis.yml
modules/core/package.json
yarn.lock

For #234 
- Dependencies can now share @babel/runtime
- Bump deps
Before and after

Bump dependencies to take advantage of @babel/runtime

---

modules/core/src/webgl-context/create-canvas.js

For # https://github.com/uber/deck.gl/issues/2312
Global cached value `isPageLoaded` is invalid by the time `Promise` is created, so calculate update `isPageLoaded`.
- AnimationLoop: fix isPageLoaded

AnimationLoop: fix isPageLoaded

---

package.json

Merged the fix of this issue https://github.com/uber/luma.gl/issues/620

[Fix] Cannot resolve 'gl' warning in webpack 4

---

docs/api-reference/core/animation-loop-proxy.md
docs/api-reference/core/animation-loop.md
examples/wip/worker/app.js
examples/wip/worker/worker.js
modules/core/src/core/animation-loop-proxy.js
modules/core/src/core/animation-loop.js

- Update outdated AnimationLoop documentation
- Add AnimationLoopProxy documentation
- Remove `animationLoop.getWorker` - This was added in previous offscreen-fixing PR, never documented or released. Removing till we have a better worker story.
- Align `AnimationLoopProxy` API with `AnimationLoop`

API audit and documentation of AnimationLoopProxy class

---

modules/core/src/core/animation-loop.js

For #755
Make `needsRedraw` flag setting behavior match with documentation.
Clear the flag after every render frame. If the flag was set by the application between the render frames, pass it to the `onRender` callback.
- Fix `needsRedraw` flag setting.

Fix needsRedraw

---

modules/core/src/shadertools/src/lib/platform-defines.js
modules/core/src/shadertools/src/utils/webgl-info.js

For #793 
Add a WA to fix shader compilation issue in IE (IE 11 and old) browsers.
- Old IE browser WA: disable adding draw_buffers extension to shader source

IE browser WA: disable adding draw_buffers extension to shader source

---

docs/api-reference/webgl/framebuffer.md
docs/api-reference/webgl/texture.md
modules/core/src/webgl/framebuffer.js
modules/core/src/webgl/texture.js

For #800
Fixes for issues found while working for #800
1. Add support for `copyTexSubImage2D` for Texture class.
2. Fix texture binding for `copyTexImage2D` (pass binding index for bind call)
3. Remove un-used `offset` argument form `copyTexImage2D`
4. Fix Framebuffer's `_unattach` method
5. Framebuffer: make attachment re-size optional during attach() , default behavior un-changed.
- Add support for copyTexSubImage2D, misc fixes

Add support for copyTexSubImage2D, misc fixes

---

modules/core/src/shadertools/src/modules/picking/picking.js

For #789
The original color of the object is replace by the auto-highlight color when the object is picked. We need to blend these two colors.
- blended the auto-highlight color with the original color of the object

blend auto-highlight color and original color when an object is picked

---

modules/core/src/webgl1/polyfill-context.js
test/modules/core/webgl1/polyfill-context.spec.js

Update polyfillContext extension initialization to handle getSupportedExtensions returning null

---

modules/core/src/core/attribute.js
test/modules/core/core/attribute.spec.js

For https://github.com/uber/deck.gl/pull/2490 - allow attributes to be constructed without a WebGLContext.
- Using attribute without a gl context
- Correctly infer attribute type when `isIndexed: true`

Attribute enhancements

---

modules/core/package.json
modules/core/src/index.js
modules/shadertools/package.json

- deck.gl depends on luma.gl exporting shadertools symbols
- (Temporarily) forward shadertools exports
- Make luma.gl depend on shadertools, not the other way around.

Forward shadertools exports (temporarily) to avoid breaking deck.gl

---

modules/shadertools/src/modules/phong-lighting/phong-lighting.glsl.js
modules/shadertools/src/modules/phong-lighting/phong-lighting.js

For #835
Need disable the lighting when there is no light source or material specified, initially thought this was handled in deck.gl, but actually the lighting is enabled all the time.
- Disable lighting when there is no light source or material

disable lighting by default

---

docs/api-reference/io/README.md
modules/core/src/index.js
modules/core/src/io/load-files.js

`Texture2D` constructor is not receiving user params when using `loadTextures`.
- `loadTextures` forward parameters properly

Fix parameter forwarding in loadTextures

---

docs/api-reference/core/animation-loop-proxy.md
docs/table-of-contents.json

to correct inconsistencies and add all orphan files
-

editing table of contents

---

examples/core/instancing/app.js
website-old/contents/demos.js

For #862 
Debug mode should be off in the website. This causes compatibility issues in older browsers.

Remove excessive debug import

---

modules/core/src/core/attribute.js
modules/core/src/webgl/classes/vertex-array.js

https://github.com/uber/luma.gl/commit/234db05a9a6a5f176401e35a1d0238fe9e627381 gives us the ability to reuse a buffer with different accessors, however the accessor.type is overridden by the buffer.accessor.

Fix `Accessor.type` to override buffer typed array

---

modules/core/package.json
modules/webgl-state-tracker/package.json
modules/webgl2-polyfill/package.json

- Submodule packages should not have cover and test scripts
- `prepublishOnly` is only needed if inline version string is used (called after lerna bumps the package version and before publishing)

Fix submodule scripts

---

modules/shadertools/src/modules/phong-lighting/phong-lighting.js

Better to wrap all the lights in the "lightSources" parameter
- use "lightSources"

use "lightSources" in module parameters

---

docs/api-reference/test-utils/snapshot-test-runner.md
modules/test-utils/src/test-runner.js
modules/webgl2-polyfill/test/polyfill-context.spec.js
package.json
test/bench/index.js
test/modules/core/webgl/features/features.spec.js
yarn.lock

- Remove usage of deprecated methods
- Remove imports from deprecated `probe.gl/test-utils` (bundles puppeteer)

Test-utils bug fixes

---

docs/upgrade-guide.md
modules/core/src/core/animation-loop.js

Per the WebGL spec (section 2.2): 
> While it is sometimes desirable to preserve the drawing buffer, it can cause significant performance loss on some platforms. Whenever possible this flag should remain false and other techniques used. 
It doesn't appear that we use the previous frame's contents for anything and @Pessimistress did some performance tests and found a non-trivial improvement.

Don't perserve the drawing buffer

---

CHANGELOG.md
docs/api-reference/core/animation-loop.md
docs/api-reference/webgl/query.md
docs/upgrade-guide.md
examples/core/dof/app.js
examples/core/instancing/app.js
examples/core/mandelbrot/app.js
modules/core/package.json
modules/core/src/core/animation-loop.js
modules/core/src/scenegraph/base-model.js
modules/core/src/scenegraph/model.js
modules/core/src/webgl/classes/query.js
modules/core/src/wip/mesh-model.js
yarn.lock

Add CPU and GPU timers to AnimationLoop.
- Add `cpuTime` and `gpuTime` properties to `AnimationLoop`. These will be updated each frame with the time spend on the cpu and gpu each frame.
- Track these times in a probe.gl `Stats` instance.
- Update `Query` to track when a query is in progress.
- Add frame time widget to Instancing, DOF and Mandelbrot examples.
Note that I'd like to move the following functionality into probe.gl:
- All tracking of times. The Stats class in probe.gl is currently tightly tied to FPS measurements.
- The TimerElement I created in the examples should be replaced with StatsWidget from probe.gl. The latter class currently only displays FPS.
- The hiResTimestamp function in AnimationLoop should be replace with the one from probe.gl once the latter is live.

Frame timers

---

modules/core/src/core/animation-loop.js
modules/core/src/webgl/classes/query.js
modules/core/src/webgl/utils/query-manager.js

Beginning a query was instantiating a Promise object whether callbacks were provided or not. This caused a performance hit as well as unnecessary memory allocations. Promises are now only created if callbacks are actually provided to the Query constructor. Improves performance of `Query.begin` on my machine from ~170us to ~50us. 
As an aside, I'm not sure associating Promises with queries is really useful, and perhaps we should consider deprecating that functionality. It seems less clear to me to have result-handling code defined at the point of query creation, rather than at the point where the results are retrieved.

Don't create no-op Promises for queries

---

modules/webgl2-polyfill/src/polyfill-context.js

Polyfills weren't setting up `queryCounter` properly because of the overlap between the WebGL 1 and 2 extension APIs. The no-op polyfill for `EXT_disjoint_timer_query` prevented the extension function available from `EXT_disjoint_timer_query_webgl2` from being used. Fix is just making sure the WebGL 2 extension is checked first.

Fix WebGL 2 timer polyfills

---

docs/api-reference/webgl/vertex-array.md
modules/core/src/webgl/classes/vertex-array.js
test/modules/core/webgl/classes/vertex-array.spec.js

add support for mat attribute types

add support for mat attribute types

---

examples/core/dof/app.js
examples/core/instancing/app.js
examples/core/mandelbrot/app.js
modules/core/src/core/animation-loop.js
modules/core/src/webgl/context/context.js
modules/core/src/webgl/context/index.js

Ensure that context polyfills always occur, even if an external context is provided. This was only happening accidentally, if `withParameters` happened to be called while rendering a scene.

Ensure that externally created contexts are polyfilled, tracked

---

modules/core/src/core/animation-loop.js

Clean up `toDataURL` based on @rolyatmax's new `waitForRender` method, and move `waitForRender` resolution into core render loop so the resolution counts toward frame time.

Move waitForRender resolve into core render loop. Use for toDataURL

---

modules/core/src/core/transform-shader-utils.js
modules/shadertools/src/lib/filters/prop-types.js
modules/shadertools/src/lib/inject-shader.js
modules/shadertools/src/utils/shader-utils.js
modules/webgl/src/webgl-utils/texture-utils.js

Remove imports of external assert

---

docs/api-reference/core/model.md
examples/core/instancing/app.js
examples/core/instancing/package.json
examples/core/mandelbrot/app.js
examples/core/mandelbrot/package.json
examples/core/transform/app.js
modules/core/src/core/geometry.js
modules/core/src/core/model-utils.js
modules/core/src/core/model.js
modules/core/src/scenegraph/nodes/model-node.js
modules/core/test/core/attribute.spec.js
modules/core/test/core/model.spec.js

Models no longer create buffers automatically. `Model.setAttributes` now passes args directly to `VertexArray.setAttributes`.

Models don't create buffers

---

docs/api-reference/core/model.md
docs/upgrade-guide.md
modules/core/src/core/base-model.js
modules/core/src/core/geometry.js
modules/core/src/core/model.js
wip/src/mesh-model.js

For #
- Per discussions today, removes redraw flag handling from luma `Model` and `Geometry`.
- replace with `Model.isAnimated()` flag
-

Remove redraw flag handling

---

modules/core/src/core/model-utils.js
modules/core/src/core/model.js
modules/core/src/geometry/geometry.js

For #
- Add back support for `Attribute` in setModel.
- Add back `vertexCount` inference from `POSITION`/`position`
- Add back `size` inference when creating Buffers (did not seem to make a difference but adding anyway to ensure we unblock).
- Add dummy `Model.geometry` object so that deck does not crash when setting `id`.

Initial round of fixes

---

modules/core/src/index.js
modules/shadertools/src/index.js
modules/shadertools/src/modules/phong-lighting/phong-lighting.js
package.json
yarn.lock

Export basic lighting for vertex shading and fragment shading
- create gouraudlighting module
- export gouraudlighting

Export gouraud lighting module

---

modules/core/src/core/model.js

Ensure buffers created by `Model.setGeometry` are deleted when a new `Geometry` is set.

Delete old buffers when auto-created in Model

---

docs/api-reference/core/animation-loop.md

There's a small typo `onInitailize` on https://luma.gl/#/documentation/api-reference/animation-loop
- Fix typo, replacing `onInitailize` with `onInitialize`.

Fix typo s/onInitailize/onInitialize

---

examples/core/dof/app.js
examples/core/dof/package.json
examples/core/instancing/app.js
examples/core/instancing/package.json
examples/core/mandelbrot/app.js
examples/core/mandelbrot/package.json
examples/core/texture-3d/app.js
examples/core/texture-3d/package.json
examples/core/transform/package.json
modules/core/package.json
modules/test-utils/package.json
modules/webgl-state-tracker/package.json
modules/webgl/package.json
modules/webgl2-polyfill/package.json
package.json
website/package.json
website/src/components/example-runner.jsx
website/src/components/hero.jsx
yarn.lock

Fix stats widget rendering in the examples. Moved all logic into the example runner, so it now renders for all examples.

Example stats widget

---

modules/addons/package.json
modules/addons/src/gltf/create-gltf-model.js
modules/addons/src/gltf/gltf-environment.js
modules/addons/src/gltf/gltf-instantiator.js
modules/addons/src/gltf/gltf-material-parser.js
modules/constants/package.json
modules/core/package.json
modules/core/src/index.js
modules/debug/package.json
modules/effects/package.json
modules/glfx/package.json
modules/gpgpu/package.json
modules/main/package.json
modules/shadertools/package.json
modules/test-utils/package.json
modules/webgl-state-tracker/package.json
modules/webgl/package.json
modules/webgl2-polyfill/package.json
package.json
yarn.lock

- Remove unused build scripts (handled by ocular-dev-tools)
- Remove unused browser fields
- Clean up dependencies:
+ For additional packages, `@luma.gl/core` should be peer dependency instead of dependency.
+ `@babel/runtime` is only explicitly included as a dependency if `@luma.gl/core` is not.
+ `@luma.gl/constants` is kept as a dependency (it is removed by custom babel plugin after transpilation)
+ `math.gl` and `probe.gl` are kept as dependencies (small enough)

Move @luma.gl/core to peerDependencies

---

modules/webgl/src/classes/program-configuration.js
modules/webgl/src/classes/vertex-array.js

Subtle bug in attribute handling introduced by the matrix attributes. `ProgramConfiguration` was assuming that locations were consecutive starting from 0, which is not the case if there are matrix attributes. Seems to only have become an issue when trying to rebind buffers to attributes manually (when VAOs aren't available).

Fix attribute handling for matrices

---

modules/core/src/core/model-utils.js
modules/core/src/core/model.js

Geometry objects are sometimes created with constant attributes (e.g. from loaders.gl). `Model.setGeometry` wasn't handling this case.

Model handles geometry with constant attributes

---

modules/shadertools/src/modules/phong-lighting/phong-lighting.js
modules/shadertools/test/modules/index.js
modules/shadertools/test/modules/phong-lighting/phong-lighting.spec.js

We shouldn't enable lighting with only checking material, the light source may not be available. For now we load lights module first which will enable lighting when lights are OK, here we only disable lighting if no material.
In the future if the module loading order is different, this logic could be broken.
- not enable lighting in phong lighting module

don't need enable lighting flag with only material

---

modules/core/test/core/transform.spec.js
modules/gpgpu/test/histopyramid.spec.js

For #1036
`histopyramid#histoPyramid_getTexCoord` was using an unset attribute. Under regular GL context this was fine as it provides a value '0', but under HeadlesGL, previously set constant attribute value is provided causing the failure. Fix the unit test and enable `WebGL#Transform run (constant Attribute)` unit test that was disabled due to this.
Changes are only to the unit tests.
- Fix Histopyramid Unit tests, eanble Transform Unit test.

Fix Histopyramid Unit tests, eanble Transform Unit test.

---

modules/core/src/geometries/cube-geometry.js
modules/core/src/geometries/ico-sphere-geometry.js
modules/core/src/geometries/plane-geometry.js
modules/core/src/geometries/sphere-geometry.js
modules/core/src/geometries/truncated-cone-geometry.js

For #
- Makes Geometries more flexible (e.g. color attribute can be added by app).
- This will allow some examples to be written more compactly (See #1039).
-

Geometries now allow attributes to added/overridden

---

modules/webgl/src/classes/accessor.js

Get rid of accessor warnings that are always triggered.

---

modules/shadertools/src/utils/webgl-info.js
modules/webgl-state-tracker/src/utils/utils.js
modules/webgl/src/context/context.js
modules/webgl/src/webgl-utils/webgl-checks.js
modules/webgl/test/context/context.spec.js
modules/webgl2-polyfill/src/polyfill-table.js
modules/webgl2-polyfill/src/polyfills/get-parameter-polyfill.js

For #1048 
Rename GL context variable to avoid constant inline replacement. This is needed to correctly verify if the context is WebGL2 or not.
- Fix isWebGL2 methods

Fix isWebGL2 methods.

---

modules/core/src/geometry/geometry.js

This was interfering with reuse of deck mesh attributes.

Don't modify input attributes

---

examples/core/dof/app.js
examples/core/texture-3d/app.js
examples/core/transform-feedback/app.js
examples/core/transform/app.js
website/contents/pages.js

For #976 
- Whether the demo is supported or not is calculated after `GL` context is created, hence default value of `isDemoSupported` should always be true to create `GL` context, so move `isDemoSupported` from global scope to instance scope.
- Mark `Texture3D` as WebGL 2 demo to match with others.
- Website: Fix WebGL demo crashes when switching

Website: Fix WebGL demo crashes when switching

---

docs/api-reference/core/animation-loop.md
docs/api-reference/core/timeline.md
docs/whats-new.md
examples/core/animation/app.js
examples/core/animation/package.json
examples/core/animation/webpack.config.js
modules/core/src/lib/animation-loop.js
modules/core/src/lib/timeline.js
modules/core/test/lib/animation-loop.spec.js

Added a `Timeline` object to animation loop to manage animation timings other than basic animation frame ticks. Basic usage:
```js
animationLoop.timeline.play(); // Animate with the render loop
animationLoop.timeline.pause(); // Stop animating with render loop
animationLoop.timeline.setTime(time); // Set the current timeline time
animationLoop.timeline.getTime(); // Get the current timeline time
animationLoop.timeline.reset(); // Set timeline time to 0
```
@Pessimistress I believe this should cover the elevate use case. The animation property `time` now comes from `timeline.getTime()` so any animations that use that value can now be controlled via the above methods.
I went a little further added a logic for managing multiple channels that move at different rates from the base timeline. It …

Animation timeline manager

---

modules/webgl/src/classes/vertex-array.js
modules/webgl/test/classes/vertex-array.spec.js

This caused an problem in deck.gl with matrix attributes, if they were set to constant and the attribute 0 buffer was auto-created (e.g. open the following in Safari to see the issue: https://observablehq.com/@pessimistress/deck-gl-lightingeffect-demo).

Fix accessor size for constant multi-column attributes

---

dev-docs/RFCs/v7.1/keyframe-rfc.md

Simple system to support animations used by the Elevate team. Allows the application to set the key frame time points, and then uses the time values from a `Timeline` object to provide two pieces of information useful in key frame animations:
- the current frame index
- the interpolation factor between them
Note that this system is completely agnostic to the type of animation being performed.

Key frame management rfc

---

modules/webgl/src/classes/framebuffer.js

Issue: https://github.com/uber/luma.gl/issues/1099
Added gl argument to _setDrawBuffers and _setReadBuffers calls that obviously was missed.

Framebuffer set buffers fix

---

modules/shadertools/src/utils/shader-utils.js

For #1112
Empty Fragment shader used to work : 
```
'void main() {}'
```
But when upgrading chromium fails all Transform related tests with this error :
```
[.WebGL-0x7fa0cf002a00]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: buffer format and fragment output variable type incompatible
```
Change in this PR fixes the problem.
- Fix for chromium GLSL compiler issue

Fix for chromium GLSL compiler issue

---

modules/addons/package.json
modules/script/package.json

Internal dependency versions in the `dependencies` field should never be edited manually.

Fix dependency versions

---

docs/api-reference/shadertools/assemble-shaders.md
examples/core/instancing/app.js
modules/core/src/index.js
modules/shadertools/src/index.js
modules/shadertools/src/lib/assemble-shaders.js
modules/shadertools/src/lib/inject-shader.js
modules/shadertools/test/lib/assemble-shaders.spec.js
modules/shadertools/test/lib/inject-shader.spec.js

A bit of a chunky update to the injection APIs to consolidate the `inject` argument hooks and the module injections. Main thing is that module injections can now inject into prebuilt injection points (e.g. `vs:#main-start`) and the `inject` argument to `assembleShaders` can inject into hook functions defined by `createShaderHook`. Also made a few minor changes to the API to make the two types of injections more consistent, e.g. using a `vs` or `fs` prefix for hook function definitions as well:
```js
createShaderHook('vs:MY_SHADER_HOOK_pickColor(inout vec4 color)');
createModuleInjection('picking', {
hook: 'vs:MY_SHADER_HOOK_pickColor',
injection: 'color = picking_setPickingColor(color);',
order: Number.POSITIVE_INFINITY
});
```

Consolidate injection APIs

---

website-gatsby/package.json
website-gatsby/src/components/animation-loop-example-page.jsx
website-gatsby/templates/core/example-cubemap.jsx
website-gatsby/templates/core/example-dof.jsx
website-gatsby/templates/core/example-fragment.jsx
website-gatsby/templates/core/example-gltf.jsx
website-gatsby/templates/core/example-instancing.jsx
website-gatsby/templates/core/example-mandelbrot.jsx
website-gatsby/templates/core/example-persistence.jsx
website-gatsby/templates/core/example-quasicrystals.jsx
website-gatsby/templates/core/example-shadowmap.jsx
website-gatsby/templates/core/example-texture-3d.jsx
website-gatsby/templates/core/example-transform-feedback.jsx
website-gatsby/templates/core/example-transform.jsx
website-gatsby/templates/lessons/example-01.jsx
website-gatsby/templates/lessons/example-02.jsx
website-gatsby/templates/lessons/example-03.jsx
website-gatsby/templates/lessons/example-04.jsx
website-gatsby/templates/lessons/example-05.jsx
website-gatsby/templates/lessons/example-06.jsx
website-gatsby/templates/lessons/example-07.jsx
website-gatsby/templates/lessons/example-08.jsx
website-gatsby/templates/lessons/example-09.jsx
website-gatsby/templates/lessons/example-10.jsx
website-gatsby/templates/lessons/example-11.jsx
website-gatsby/templates/lessons/example-12.jsx
website-gatsby/templates/lessons/example-13.jsx
website-gatsby/templates/lessons/example-14.jsx
website-gatsby/templates/lessons/example-15.jsx
website-gatsby/templates/lessons/example-16.jsx

Upgrade to ocular-gatsby alpha.35
Update gatsby website example pages to use example config from page context.
Fix styletron dev dependency conflict.
Rename AnimationLoopRunner to AnimationLoopExamplePage based on PR feedback from #1122 .

Gatsby website example page fixes

---

docs/api-reference/webgl/texture.md
modules/webgl/src/classes/texture.js
modules/webgl/test/classes/texture.spec.js

For #1147 and #1146 
- check mipmap enabled before calling generateMipmaps
- add test

Fix mipmap generation

---

modules/webgl/src/classes/texture.js

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D
- Support ImageBitmap supplied to Texture data

Support ImageBitmap in Texture

---

modules/webgl/src/classes/texture.js

Looks like this `texture.hasFloatTexture` property [used to be relied on](https://github.com/uber/luma.gl/commit/1b5bcda390d86532ca4f04c29d81132976806608), but is no longer being used in the codebase. In WebGL2,`gl.getExtension('OES_texture_float')` evaluates to `null`, which is quite misleading when debugging float textures. I vote for dropping this property altogether since it's not being used anywhere and is Just Another Piece of State To Maintain™️

remove Texture class's hasFloatTexture property

---

docs/api-reference/webgl/framebuffer.md

misc fixes to Framebuffer docs

---

docs/api-reference/webgl/texture.md
modules/webgl/src/classes/texture.js
modules/webgl/test/classes/texture.spec.js

From the [Texture docs](https://luma.gl/#/documentation/api-reference/webgl-2-classes/texture):
> Note that luma.gl deduces `format` and `type` from `internalFormat`
This seems to be working for the texture's data type, but not for its data format. This PR fixes that bug and tweaks the wording slightly here as `internalFormat` is not a supported property name (it's meant to be `format`), and `format`, here, should actually be `dataFormat`.
I think the docs are still a bit confusing, even after this update, as the term "internal format" is used quite a bit and is easily confused with "data format". I'm open to suggestions on wording tweaks to make this clearer with more consistent terminology.

fix texture2D type/dataFormat inference

---

modules/webgl/src/classes/program.js
modules/webgl/test/classes/program.spec.js

Need support binding texture and matrix array
- add uniform names for array

support uniform texture and matrix array

---

modules/core/src/index.js
modules/shadertools/src/index.js
modules/shadertools/src/lib/resolve-modules.js
modules/shadertools/src/lib/shader-module-registry.js
modules/shadertools/test/lib/resolve-modules.spec.js

we need ability to expand default modules after the default is set, create this new API to get current default modules
- new getDefaultShaderModules API
- unit tests

New getDefaultShaderModules API

---

modules/shadertools/src/modules/phong-lighting/phong-lighting.js
modules/shadertools/test/modules/phong-lighting/phong-lighting.spec.js

- Normalize `specularColor` (light colors are already normalized)
This will require `surfaceColor` passed into `lighting_getLightColor` to be normalized as well.
This is a breaking change.

Fix lighting module color format

---

modules/core/src/lib/base-model.js

For #1190 
Add back `clear` method that got removed in #1185 , it is being used in core examples.
- BaseModel: add back clear method

BaseModel: add back clear method

---

modules/constants/src/index.js

For https://github.com/uber/deck.gl/pull/3468#discussion_r315899498
Source: https://www.khronos.org/registry/OpenGL/api/GL/glcorearb.h
- Add `DOUBLE` to `@luma.gl/constants`

Add DOUBLE to gl constants

---

docs/api-reference/webgl/context/has-features.md
docs/developer-guide/extensions.md
modules/webgl/src/features/webgl-features-table.js
modules/webgl/test/features/features.spec.js

Fixes #1209
- Add `EXT_float_blend` to FEATURES table.
- `EXT_color_buffer_half_float` is an extension on WebGL1 and WebGL2, fix the table accordingly.
- Update docs
- Update unit tests
- Add EXT_float_blend to feature table

Add EXT_float_blend to feature table

---

docs/api-reference/core/resource-management/program-manager.md
modules/core/src/lib/base-model.js
modules/core/src/resource-management/program-manager.js
modules/core/test/lib/model.spec.js
modules/core/test/lib/program-manager.spec.js
modules/webgl/src/classes/program.js

- Fix useCounts when checking program updates in `BaseModel.drawGeometry`
- Allow just module name as argument in `ProgramManager.addModuleInjection`

Program manager fixes

---

modules/webgl/src/classes/framebuffer.js

- Fix `WEBGL.color_buffer_float` typo
- Fix logic (half float check would overwrite float check)
- Check `OES_texture_float` to support WebGL 1 contexts that don't report `WEBGL_color_buffer_float` (e.g. Safari)

Fix Framebuffer isSupported test

---

modules/core/src/lib/transform.js
modules/core/test/lib/transform.spec.js

Fixes #1218 
- Move all Buffer setting code to `_setBuffers`, that is used during `construction` and `update`, this allows `Transform` to be constructed without any `Buffer`s  and they be set later using `update`.
- Fix `elementCount` update, so `Transform` can be constructed without specifying it. It must be provided before calling `run`.
- Transform: Fix update of Buffers and elementCount.

Transform: Fix update of Buffers and elementCount.

---

package.json

For #
This prevents transpiling `async/await` in our es6 distributions, which enables clean single stepping through async await code in Chrome debugger.
- https://github.com/uber-web/ocular/pull/240
- Bump ocular-dev-tools

dev-tools: Bump to 0.0.28

---

docs/api-reference/core/animation-loop.md
docs/api-reference/webgl/device-pixels.md
examples/core/instancing/app.js
examples/core/instancing/package.json
examples/core/transform/app.js
examples/core/transform/package.json
modules/core/src/index.js
modules/core/src/lib/animation-loop-proxy.js
modules/webgl/src/context/context.js
modules/webgl/src/index.js
modules/webgl/src/utils/device-pixels.js
modules/webgl/src/utils/index.js
modules/webgl/test/utils/device-pixels.spec.js
modules/webgl/test/utils/index.js
website/contents/pages.js
wip/src/pick-models.js

For #1154 
- Add support to specify custom device pixel ratio, to enable applications to perform anti aliasing through down sampling. Also helps users to improve performance by setting ratio to a value less than 1
- Group all related code into a single file, add unit tests.
- This is for advanced use case, hence overloading `useDevicePixels` prop, also not documenting intentionally, in future we can make it public API.
- Notes
- When device pixel ration is high, [depending on implementation](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/drawingBufferWidth), drawing buffer size gets clamped and may not match with canvas size, hence when mapping from window to device pixels, we need to use allocated drawBufferSize, instead of what pixel ratio we used.
- When drawing …

Add support for specifying custom device pixel ratio.

---

modules/shadertools/src/lib/assemble-shaders.js
modules/shadertools/src/utils/shader-utils.js
modules/webgl/src/classes/shader.js

For #1205
@raub and I are working on some [native addons](https://github.com/trxcllnt/node-3d) to provide an OpenGL-backed WebGL context in node, so browser-based WebGL apps can run unmodified in GLFW and render via OpenGL.
Linux and Windows' GL 4.6 are working fine as-is, but MacOS's GL 4.1 is strictly enforces the shader version definition, so the luma.gl lesson examples are choking on shader compilation.
- Ensure `assembleShader` always sets the GLSL version when one isn't specified.

ensure assembleShader always sets the GLSL version

---

modules/webgl/src/classes/vertex-array-object.js
modules/webgl/src/classes/vertex-array.js

When a browser only has support for shared `VertexArrayObjects`, the `VertexArray` must bind to the shared buffer before drawing and then unbind after. During the unbind step, the `elements` buffer was cleared from the `VertexArray`. This causes subsequent draws to fail as there were no elements to draw.
* When unbinding buffers, do not clear the list of elements from the VertexArray.
* Ensure that the shared `VertexArrayObject` is still cleared during the unbind process

#1208 - Do to clear the VertexArray elements buffer when unbinding a shared VertexArrayObject.

---

modules/webgl/src/classes/vertex-array-object.js
modules/webgl/src/classes/vertex-array.js
modules/webgl/test/classes/vertex-array.spec.js

Property wasn't being properly set, was fixed in #1238 and that ended up breaking everything. This fix isn't ideal, but I believe it's the lightest touch to get things working again, essentially reverting the prior fix. This logic should be revisited in the future.

Don't set VertexArrayObject.isDefaultArray

---

website-gatsby/package.json

This will ensure the `PATH_PREFIX` option is respected.

--prefix-paths option for gatsby build

---

modules/webgl/src/classes/framebuffer.js
modules/webgl/src/features/webgl-features-table.js

For #1256 
More details in above issue.
- Update checking support for rendering to float textures

Update checking support for rendering to float textures

---

package.json

This was broken when lerna stopped bumping root package version.

Fix inlined version in published package

---

docs/api-reference/shadertools/shader-module-picking.md
modules/shadertools/src/modules/picking/picking.js
modules/shadertools/test/modules/picking/picking.spec.js

For https://github.com/uber/deck.gl/pull/3721
Move generic-purpose shader code into the picking module.
- Add `pickingAttribute` module option
- Add `picking_setPickingAttribute` vertex shader function

Add attribute picking to the picking module

---

modules/webgl/src/context/context.js
modules/webgl/test/context/context.spec.js

For # https://github.com/uber/deck.gl/issues/3728
- When custom device pixel ratio support is added, we would set canvas width/height multiple times, when device size limit is reached. Do this only once per given size and ratio.
- Cache `clientWidth`, `clientHeight` and `devicePixelRatio`,  resize canvas only when any of these prameters are changed.
- Use `Math.floor` when clamping width and height to avoid potential drawing buffer size clamping.
- DevicePixelRatio: Cache canvas size to avoid expensive setting on each frame

DevicePixelRatio: Cache canvas size to avoid expensive setting on each frame

---

modules/core/src/lib/transform/buffer-transform.js
modules/core/src/lib/transform/transform.js
modules/core/test/lib/transform.spec.js

For # https://github.com/uber/deck.gl/issues/3778
Will cherry-pick this to 7.3-release branch.
Fix: Fix element count check so it can be set to `0`
Fix: Fix feedback buffer auto creation
- Transform Fix: elementCount update, feedback buffer creation

Transform Fix: elementCount update, feedback buffer creation

---

modules/webgl/src/webgl-utils/webgl-types.js

This hack, although works in webpack, breaks usage in the browser when packaging with rollup.
Adding a `try/catch` block fixes the issue. Fixes #1265
- Surrounded hack in a `try/catch` block.

Fix usage with rollup

---

modules/core/package.json
modules/core/src/index.js
modules/shadertools/src/modules/index.js
modules/shadertools/src/modules/phong-lighting/phong-lighting.js
modules/shadertools/test/modules/phong-lighting/phong-lighting.spec.js

- Fix missing core dependency on engine
- Export `Timeline` from core
- Allow for default material parameters in phong lighting by passing `material: true`
- Fix case of `gouraudLighting` and `phongLighting` module names

Fix deps, simplify materials

---

modules/webgl/src/context/context.js
modules/webgl/src/utils/device-pixels.js
modules/webgl/test/context/context.spec.js
modules/webgl/test/utils/device-pixels.spec.js

Related to deck.gl issue 3842
- When canvas's `clientWidth` or `clientHeight` is 0 or `undefined` we are falling back to `gl.canvas.width/height`. But `gl.canvas.width/height` may have been scaled with device pixel ratio in previous frame. To avoid this continuous scaling, set `devicePixelRatio` to 1 in such cases.
- DevicePixelRatio: Handle the case when clientWidth/Height not available

DevicePixelRatio: Handle invalid client sizes and remove custom width/height support.

---

.eslintrc.js
modules/gltools/src/state-tracker/track-context-state.js
modules/gltools/src/state-tracker/unified-parameter-api.js
modules/webgl/src/classes/program.js

Three smaller optimizations:
- Track current program, only update if it changes
- Check for empty objects passed to `setParameters`
- Keep track of texture uniforms in `Program` so you don't have to loop through all uniforms to bind them (deck's tends to send a lot of uniforms, not many textures for rendering).
Total performance improvement over 7.3 on the stress test currently at:
|        |7.3  |Current|Improvement|
|--------|-----|-------|-----------|        
|CPU Time|43ms |17ms   |26ms (60%) |
|GPU Time|38ms |24ms   |14ms (37%) |

Small optimizations

---

docs/upgrade-guide.md
modules/addons/src/gltf/gltf-environment.js
modules/webgl/src/classes/texture.js

`unpackFlipY` only affects Image and Canvas data sources, and not typed arrays or `ImageBitmap`. This default behavior makes the resulting texture unpredictable when used with `@loaders.gl/images`, which automatically selects the image format at runtime.
- Remove the `unpackFlipY` option from `Texture`
- Upgrade guide

Remove unpackFlipY option from Texture

---

CHANGELOG.md
lerna.json
modules/addons/package.json
modules/constants/package.json
modules/core/package.json
modules/core/src/index.js
modules/debug/package.json
modules/engine/package.json
modules/engine/src/index.js
modules/engine/src/utils/clip-space.js
modules/gltools/package.json
modules/gltools/src/state-tracker/unified-parameter-api.js
modules/gltools/test/state-tracker/state-tracking/context-state.spec.js
modules/gltools/test/state-tracker/state-tracking/track-context-state.spec.js
modules/shadertools/package.json
modules/shadertools/src/lib/resolve-modules.js
modules/shadertools/src/modules/fp64/test/fp64-test-utils.js
modules/shadertools/test/lib/resolve-modules.spec.js
modules/test-utils/package.json
modules/webgl/package.json

Fix some breakages caused in deck.gl:
- Restore ClipSpace
- Improve getParameters API so it can be used with a single parameter
- Update resolveModules to report when a string is passed in (deprecated usage)

ClipSpace, getParameters, resolveModules fixes

---

modules/gltools/src/state-tracker/unified-parameter-api.js
modules/gltools/test/state-tracker/unified-parameter-api/set-parameters.spec.js

Ensure first arg to setParameters is a WebGL context (fails silently otherwise).

Set parameters assert

---

CHANGELOG.md
docs/upgrade-guide.md
lerna.json
modules/constants/package.json
modules/core/package.json
modules/core/src/index.js
modules/debug/package.json
modules/engine/package.json
modules/experimental/package.json
modules/gltools/package.json
modules/shadertools/package.json
modules/test-utils/package.json
modules/webgl/package.json

Begin using deck.gl usage as the metric for what should be included in core.

Reduce core to modules used by deck.gl

---

modules/shadertools/src/lib/shader-module.js
modules/shadertools/src/modules/fp64/fp64.js
modules/shadertools/src/modules/index.js

For deck.gl aggregation refactor
- Expose shader module `fp64arithmetic` for applications that do not need 64-bit trigonometry/matrix functions (drops 600+ lines of shader code from deck dependency)
- Fix invalid define generated in shader assembly (`#define MODULE_FP64-ARITHMETIC` -> `#define MODULE_FP64_ARITHMETIC`)

Export fp64-arithmetic shader module

---

package.json
yarn.lock

Version number is inlined in the `webgl` module with `babel-plugin-version-inline` so transpilation must be rerun after a version bump. This is done via the `version` script in the root package.json.
Some time during v7 this was broken, due to (supposedly) a bug in lerna that failed to execute the root command. We attempted a fix in https://github.com/uber/luma.gl/pull/1262 which was ineffective. This bug is still present in [8.0.0-beta.2](https://unpkg.com/browse/@luma.gl/webgl@8.0.0-beta.2/dist/es6/init.js#L4).
- Bump lerna
- Revert root command name change

Fix inlined version

---

modules/engine/src/lib/model.js
modules/webgl/src/classes/program.js

Texture load checking time reduced by 30-50% on a quick test with the cubemap example.

Small optimizations to texture checks and program updates

---

modules/webgl/src/classes/program.js
modules/webgl/test/classes/program.spec.js

For #1339 
Skip issuing `draw` call when vertex count is 0.
- [Chore]: Skip draw when vertex count is 0

[Chore]: Skip draw when when rendering 0 primitives

---

docs/api-reference/engine/model.md
docs/api-reference/engine/program-manager.md
docs/api-reference/shadertools/assemble-shaders.md
docs/developer-guide/shader-modules.md
modules/engine/src/lib/model.js
modules/engine/src/lib/program-manager.js
modules/engine/test/lib/model.spec.js
modules/engine/test/lib/program-manager.spec.js
modules/shadertools/src/lib/assemble-shaders.js
modules/shadertools/src/lib/shader-module.js
modules/shadertools/src/lib/transpile-shader.js
modules/shadertools/test/lib/assemble-shaders.spec.js
modules/shadertools/test/lib/transpile-shader.spec.js

- Perform transpilation on full shader rather than just shader modules in `assembleShaders`.
- Add options to `Model`, `ProgramManager` and `assembleShaders` to force transpilation to GLSL 1.0.
- Add transpilation rules to fix GLSL version declaration and fragment shader output.
Tested with a simplified version of the deck.gl GLSL 3.0 mesh layer shaders.

Full shader transpilation

---

docs/api-reference/engine/animation/timeline.md

For #
The current link for Frames navigates to https://github.com/uber/luma.gl/blob/master/docs/api-reference/engine/animation/key-frames, which gives a 404. 
Updating it to https://github.com/uber/luma.gl/blob/master/docs/api-reference/engine/animation/key-frames.md
- Update Frames link in Timeline Readme

Fix broken link

---

examples/showcase/persistence/app.js
modules/engine/src/geometries/sphere-geometry.js

- Fix index generation in sphere geometry.
- Use SphereGeometry in persistence example so it can act as a test for sphere coordinate generation.
Fixes #1349

Fix SphereGeometry indices

---

modules/webgl/src/classes/vertex-array.js

Looks like a long-standing resource leak. I suspect this was to avoid deleting the the default VAO, but that's no longer necessary with the polyfill.

Delete VAO when vertex array is deleted

---

modules/shadertools/src/lib/assemble-shaders.js
modules/shadertools/src/lib/inject-shader.js
modules/shadertools/test/lib/assemble-shaders.spec.js

Change that pulls base shader variables to the top of the assembled source so they can be accessed by hook functions. Requested for deck.gl.
Order of assembled source is now:
- Base source attributes, varyings, uniforms
- Module source
- Hook functions
- Base source functions and main.
Note: this solution assumes that base source variables are all defined before the first function.

Assemble shader variables to top of source

---

modules/engine/src/geometries/sphere-geometry.js

Use 32-bit indices in SphereGeometry if there are enough vertices

---

modules/gltools/src/context/context.js
package.json
yarn.lock

Per docs: 
> `throwOnError` (`true`) Normally the context will throw an error on failure. If `false`, it will log to console instead. 
- match `throwOnError` default with documentation
- log error to console when `throwOnError` is `false`
- pass onError callback to `createBrowserContext`.

Fix error handling in createGLContext

---

docs/api-reference/engine/animation-loop.md
modules/engine/src/lib/animation-loop.js

Right now there is no way to handle promise rejections when starting the animation loop (e.g. failed to create WebGLContext, see See https://github.com/visgl/deck.gl/issues/4006#issuecomment-565212098).
- Add `onError` prop to `AnimationLoop`

Add onError prop to AnimationLoop

---

modules/shadertools/src/modules/picking/picking.js
modules/shadertools/test/modules/picking/picking.spec.js

`setUniforms` crashes if `pickingHighlightColor` is a vec3.
- Normalize `pickingHighlightColor`
- Test

Picking module: normalize highlight color

---

website/ocular-config.js

- Fixes the org of the top-right "Github" link to point to https://github.com/visgl/luma.gl instead of https://github.com/uber/luma.gl

Update org name in website

---

examples/showcase/gltf/app.js
examples/showcase/gltf/package.json

For #
- In loaders.gl 2.2 the GLTFLoader already imports the DracoLoader dependency, the application no longer needs to deal with this.
- remove DracoLoader dependency from gltf example

examples/gltf: Remove DracoLoader import (no longer needed)

---

modules/engine/src/lib/model.js
modules/engine/test/lib/model.spec.js

There was a bug in deck.gl's`ScreenGridLayer` where aggregation models were deleted twice. This PR guards against `program.draw` error if it happens elsewhere.
- Avoid calling `programManager.release` if `model.delete` is called again
- Unit test

Fix bug when a model is deleted multiple times

---

package.json

The URL in package.json for the `yarn start` command is out of date. It will open the front page instead of the contributor guide.

Update instructions URL in package.json

---

modules/constants/package.json

src/index.js was changed to ES6 in #1403

Fix constants package.json

---

docs/api-reference/webgl/texture.md
docs/whats-new.md
modules/webgl/src/classes/program.js
modules/webgl/src/classes/texture.js

The Texture class docs claim that it continuously updates if `HTMLVideoElement` is supplied, while in fact it doesn't.
- Prevent `Texture` from initialization until `element.videoWidth` and `element.videoHeight` are loaded
- Add `texture.update` method. It re-uploads the `HTMLVideoElement` if:
a. the video timestamp has changed
b. the current frame is loaded
- `Program` updates samplers before every draw call
- Clarify update behavior in documentation

Texture supports continuous update from HTMLVideoElement

---

modules/gltools/src/context/context.js

For https://github.com/visgl/deck.gl/issues/5202
If WebGL is disabled, console shows "uncaught exception" error even if `AnimationLoop`'s `onError` prop is supplied.
This is because `createGLContext` also throws inside the canvas' `webglcontextcreationerror` event listner, which is not caught inside the `animationLoop.start()` promise.
- Avoid throwing inside `webglcontextcreationerror` event listner

Make sure animationLoop's onError catches context creation errors

---

modules/experimental/src/gpgpu/point-in-polygon/gpu-point-in-polygon.md

Small docs change. I was at first unsure where `count=6` came from.

Docs: Make clear that count is derived from the length of points array

---

modules/webgl/src/classes/texture.js

During development of example app in "loaders.gl" we faced with troubles during visualization of compressed textures.
This PR resolves the issue:
- passes `compressed` option to `setImageData` method;
- handles data format of compressed texture parsed in "loaders.gl"

webgl: texture - support compressed textures

---

docs/api-reference/gltools/context.md
docs/whats-new.md
modules/gltools/src/context/context.d.ts
modules/gltools/src/context/context.js

Added callbacks to handle onContextLost / onContextRestored events of WebGLRenderingContext
For #1440

feat (Context) Callbacks for onContextLost / onContextRestored events

---

modules/webgl/src/classes/texture.js

Fix `Uncaught TypeError: Cannot add property _video, object is not extensible` error with asynchronously loaded video
- Add `_video` member before the instance is sealed

Fix video texture error when video is still loading

---

docs/table-of-contents.json

Adds `program-manager.md` to the website's table of contents. The page already exists on the website, but isn't in the sidebar.
Additionally
```
/docs/api-reference/engine/transform/buffer-transform.md
/docs/api-reference/engine/transform/texture-transform.md
```
aren't in the table of contents, and I can't tell if that's intentional.
---
When I build the website locally, I have to add an `index: 1` to `ADDITIONAL_LINKS` in the Gatsby config in order to build the site with current ocular. 
Though when I do build, the site doesn't match the public website:

Add Program Manager to website table of contents

---

modules/webgl/src/classes/texture.js

`texImage2D` fails if the video has not loaded its first frame.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#events
- Wait till the first frame is loaded

Fix occasional error when using video texture

---

modules/shadertools/src/lib/shader-module.js
modules/shadertools/test/lib/assemble-shaders.spec.js

For https://github.com/visgl/deck.gl/issues/5436
When normalizing a shader module, `injection.order` is not populated, breaking the injection sorting here:
https://github.com/visgl/luma.gl/blob/784b4def3ba0ad375991481d092cf324e22e0aa3/modules/shadertools/src/lib/assemble-shaders.js#L233
- Assign default injection order
- Tests

Fix shader module injection order

---

modules/shadertools/src/lib/platform-defines.js
modules/shadertools/src/lib/transpile-shader.js
modules/shadertools/test/lib/transpile-shader-cases.js
modules/shadertools/test/lib/transpile-shader.spec.js

Fixes #1450
- Transpile shader replacement rules for GLSL functions did not cover all cases.
- Presumably, the stricter GLSL prologue in 8.4 triggered a new code path in the PBR module.
- Improve `transpileShader`

feat(shadertools): GLSL transpilation improvements

---

docs/api-reference/engine/animation-loop.md
modules/engine/src/lib/animation-loop.d.ts
modules/engine/src/lib/animation-loop.js
modules/engine/test/lib/animation-loop.spec.js

For [visgl/deck.gl#5399](https://github.com/visgl/deck.gl/pull/5399)
Required to add better context lost state handling.
- added isContextLost to AnimationLoop which returns the current state of the used WebGL context
- AnimationLoop.redraw function exits early in case of a lost context

Exposed isContextLost from animation loop

---

modules/gltools/src/utils/webgl-checks.js
modules/shadertools/src/utils/webgl-info.js

Currently, the following code throws error `Invalid WebGLRenderingContext`:
```js
const gl = canvas.getContext('webgl2');
const texture = new Texture2D(gl, {});
```
Because `isWebGL` does not recognize `WebGL2RenderingContext` that is not instrumented by luma.
- `isWebGL` should recognize `WebGL2RenderingContext`

Fix isWebGL check on non-instrumented context

---

modules/experimental/src/index.d.ts
modules/experimental/src/index.js

- we need it in SimpleMeshLayer to support materials in I3S.
- export GLTFMaterialParser.

gltf: export GLTFMaterialParser

---

modules/experimental/src/gltf/gltf-material-parser.js

- To use PBR Material in SimpleMeshLayer
- Support compressed textures in PBR Material

gltf: support compressed textures

---

modules/shadertools/src/lib/transpile-shader.js
modules/shadertools/test/lib/assemble-shaders.spec.js
modules/shadertools/test/lib/transpile-shader-cases.js
modules/shadertools/test/lib/transpile-shader.spec.js

Usecase: when subclassing a deck.gl layer, support injecting GLSL 3.00 features into GLSL 1.00 shaders
transpileShader 1.00 -> 3.00 needs to inject a new output variable to replace `gl_FragColor`
This PR implements a TODO mentioning this missing feature:
https://github.com/visgl/luma.gl/blob/d5bd93ef6bd0a0ff4af7880424286bda269e29a8/modules/shadertools/test/lib/transpile-shader.spec.js#L39-L44
- transpile-shader.js replaces all occurences of `gl_FragColor` with detected output name. If there is no output name detected, default `fragmentColor` name is used, and a new output variable is injected before the main.
- transpile-shader.spec.js checks all transpilation directions

Transpile gl_FragColor in fragment shader from GLSL 1.00 to 3.00

---

modules/shadertools/src/lib/transpile-shader.js
modules/shadertools/test/lib/minify-shader.js
modules/shadertools/test/lib/transpile-shader-compress.js
modules/shadertools/test/lib/transpile-shader.spec.js

Fixes #1481
Changes:
- multiline regexes `/^[ \t]*…/m` replaced with `/\b…/`, to match on word boundaries on a single line in a minified shader
- ES100 replacement `in[ \t]+` -> `varying ` replaced with `in[ \t]+(.+;)` -> `varying $1`, to match shader varyings only, skip function arguments

Fix transpiling minified shader

---

modules/shadertools/src/lib/transpile-shader.js
modules/shadertools/test/lib/transpile-shader-cases.js

Follow up of #1482
The current RegExp does not match [array variables](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Arrays) e.g. `in vec4 positions[2];`
@zakjan

Fix transpilation of array variables

---

modules/shadertools/src/lib/platform-defines.js
modules/shadertools/src/utils/webgl-info.js

iPhone/Apple M1 have been using the custom tan_fp32 function meant for integrated intel GPUs. This PR removes the flag and we can add it back on a more targeted basis if necessary.

Remove overly broad platform defines

---

modules/engine/src/lib/animation-loop.js

* only schedule animation frames if the loop is running
* return the id from `_requestAnimationFrame` so it can be canceled later
* add `_cancelAnimationFrame` method so the party that scheduled the frame also cancels it

Fix animation frame scheduling and cancellation

---

modules/engine/src/lib/animation-loop.js

`AnimationLoop` has grown rather complicated. The first of a few of cleanup PRs adopts async/await in AnimationLoop.start.

chore(engine): animation loop light refactor

---

modules/core/src/index.ts
modules/gltools/src/lib/deprecated/context-api.ts

For #1525 
- Deprecate importing webgl and shadertools re-exports through core module
- Add back deprecated gltools re-exports

chore(core): export cleanup

---

modules/constants/src/constants-enum.ts
modules/webgl/src/adapter/converters/texture-formats.ts

For #1525
- Add [EXT_texture_norm16](https://www.khronos.org/registry/webgl/extensions/EXT_texture_norm16/) constants to texture format table
-

feat(webgl): Add normalized 16-bit texture formats

---

modules/experimental/src/gltf/gltf-material-parser.ts

We should be able to explicitly destroy created textures.
It will be used in deck.gl and also improve Texture statistics calculation.

chore(gltf-material-parser): add cleanup method

---

modules/engine/package.json
modules/gltools/package.json
yarn.lock

TypeScript lib check complains that `OffscreenCanvas` is not defined.
- Add `@types/offscreencanvas` dependency

Fix OffscreenCanvas type error

---

modules/webgl/src/classes/resource.js

Fix an issue with adding new fields to `gl` context object in firefox and mobile safari.

chore(webgl): separate mem stats another way

---

.github/workflows/test.yml

- Align CI with current LTS Node releases, drop Node 12
- Drop Node 12
- Previously the node install wasn't using the node version in the test matrix which caused e.g. `gl` upgrade to fail.
- Can add 18 in separate PR

chore: drop Node 12 from CI. Use current node version for Node setup

---

modules/engine/test/transform/transform.spec.js
modules/experimental/test/gpgpu/histopyramid.spec.js

- Tests for the largely unused WebGL1 texture fallback case of Transform started failing on CI some time ago
- Disable these tests for now.

chore: Disable texture transform tests failing on CI

---

.github/workflows/test.yml
package.json
yarn.lock

- Increasing build failures on various systems. Let's make sure we use latest deps
- Bump headless gl from 4.x to 6.x

chore: bump headless-gl

---

package.json
yarn.lock

For #
- gl v6 seems to have some flakiness initializing.
- puppeteer is timing out
- change gl to latest v5 
- pin probe.gl to v3.5 or higher since that version disables the 30s timeout

chore: revert gl to v5, pin probe to >3.5

---

modules/api/src/adapter/resources/render-pipeline.ts
modules/api/src/adapter/types/parameters.ts
modules/api/src/adapter/types/parameters.ts.disabled
modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts

For #
- triangle-fan and line-loop were not included since WebGPU doesn't support them.
- Add them back to unblock initial luma porting
-

fix(api): Support more topologies for WebGL

---

modules/api/src/adapter/device.ts
modules/shadertools/src/lib/shader-assembler/platform-defines.ts
modules/shadertools/test/index.ts
modules/shadertools/test/modules/fp64/fp64-arithmetic-transform.spec.ts
modules/shadertools/test/modules/fp64/fp64-test-utils-transform.ts
modules/shadertools/test/modules/index.ts
modules/webgl/src/adapter/device-helpers/get-device-info.ts

For #
- Looks like Apple GPUs have [floating point precision issues](https://eclecticlight.co/2021/04/22/can-you-trust-floating-point-arithmetic-on-apple-silicon/) (much like other GPUs), and unfortunately they are not fixed by activating any of our current workarounds.
- Avoid running fp64 precision tests on apple GPUs
- Add `software` GPU type for the swiftshader that is used in headless browser mode.

chore(shadertools): restore fp64 tests

---

docs/api-reference/test-utils/api-reference/snapshot-test-runner.md
docs/api-reference/test-utils/snapshot-test-runner.md
docs/developer-guide/debugging.md
docs/developer-guide/testing.md
modules/core/src/index.ts
modules/debug/src/index.ts
modules/debug/src/webgl-api-tracing/webgl-debug-context.ts
modules/experimental/test/scenegraph/model-node.spec.js
modules/shadertools/test/gpu-test-utils.js
modules/test-utils/src/test-runner.ts
modules/webgl-legacy/test/classic/transform-feedback.spec.js
modules/webgl-legacy/test/engine/animation-loop.spec.js
test/apps/tree-shaking/app.js
test/bench/shaders.bench.js
test/bench/uniforms.bench.js
test/render/gltf-test-cases.js.disabled
test/size/import-nothing.js
website-gatsby/src/components/animation-loop-example-page.jsx

For #
- luma.gl v9 API is WebGL independent, so core shouldn't re-export the WebGL module.
-

chore: Remove WebGL specific exports from core

---

docs/api-reference/experimental/scenegraph/scenegraph-node.md
modules/experimental/src/gltf/gltf-instantiator.ts
modules/experimental/src/scenegraph/group-node.ts
modules/experimental/src/scenegraph/model-node.ts
modules/experimental/src/scenegraph/scenegraph-node.ts
modules/experimental/test/scenegraph/group-node.spec.js
modules/experimental/test/scenegraph/model-node.spec.js

To support Tile3DLayer + TerrainExtension in deck.gl
- Implement getBounds() in `ModelNode` and `GroupNode`
- Assign node bounds from gltf primitives
- Tests
- Documentation

Add getBounds() to ScenegraphNode

---

modules/gltools/src/utils/device-pixels.js

If `autoResizeFramebuffer` is disabled then `luma.canvasSizeInfo` cache is never populated.
- Fallback to `canvas.clientWidth` if cache is not available

Fix cssToDeviceRatio when auto resize is disabled

---

modules/webgl/src/adapter/resources/webgl-texture.ts

Modify to call "setImageData3D" method even if "2d-array" in addition to "3d"
For #1760
- If the value of 'dimension' is '2d-array', the phenomenon that was incorrectly initialized by performing a basic initialization without initializing using the 'setImageData3D' method
- If the value of 'dimension' is '3d' or '2d-array', call the 'setImageData3D' method and modify it to perform initialization.

fix #1760 - the phenomenon that data is not properly initialize

---

modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

The change involves replacing the logical OR operator (`||`) with the nullish coalescing operator (`??`) in the `_applyUniforms()` method. This modification addresses a specific issue where 0 or false values were not being correctly assigned. By using the nullish coalescing operator, the code ensures that if the value of `this.uniforms[name]` is either 0 or false, it will be properly assigned as the value for `value`. This change enhances the accuracy and reliability of the code by handling these specific cases effectively.
✅ Closes: #1741
For #1741
The issue with the original code was that it did not handle 0 and false values correctly when assigning them to uniforms. This resulted in unexpected behavior when attempting to set these values. The change to use the nullish coalescing …

fix: 🐛 Fix issue with setting 0 or false values

---

modules/webgl/src/adapter/webgl-device.ts
modules/webgl/src/classic/buffer-with-accessor.ts
modules/webgl/src/classic/copy-and-blit.ts
modules/webgl/src/index.ts

For #
- The legacy buffer class with the accessor is much too complicated and needs to be streamlined to allow WebGPU support.
- But the impact on applications will be too high, so keep the class for now and export it from the webgl module (instead of api).
-

feat(webgl): Export legacy BufferWithAccessor

---

examples/showcase/instancing/app.ts
modules/core/src/adapter/utils/decode-vertex-format.ts
modules/shadertools/src/modules/picking/picking.ts
modules/webgl/src/adapter/helpers/set-uniform.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

For #
- Fix refactored uniform setters.
- Correct handling of `false` valued uniforms.
- Avoid setting `integer` flag on an attribute info just because the provided data is in non-normalized integer form (since this mapping works on WebGL).
- Undo random change in picking module that was compensating for the broken uniform setter.

fix(coew): boolean uniform fix

---

modules/shadertools/src/lib/shader-assembly/platform-defines.ts

#1496 is reverted on 8.5-release but not on master.
This is breaking render test because headless Chrome's tan function has precision issues.
- Restore platform defines for unknown GPU

Restore fallback platform defines deleted in #1496

---

modules/engine/src/model/model.ts

- Merge with `geometry.bufferLayout` if geometry is set
- Upon calling `model.setBufferLayout`, recreate the pipeline and vertexArray. Pipeline recreation cannot be deferred to `model.draw` because `setAttribute`/`setConstantAttribute` directly operates on the vertexArray.

Fix model.setBufferLayout

---

modules/engine/src/model/model.ts

Modules set textures as well as uniforms as their properties, this extracts WebGLTextures&WebGLFramebuffers (admitedly in a hacky manner) and applies them to the bindings rather than the uniforms list. With this change, I can get the shadow effect working in deck.gl & it is a step forward to fixing the broken extensions. 
It is worth discussing how to do this more cleanly, ideas:
- Filter for specific types to support WebGPU&WebGL rather than `includes('WEBGL')`
- Include an explicit `getBindings()` method in the `ShaderModule`
- Extract WebGL resources and apply to bindings, rather than uniforms

Extract bindings from shader module props

---

modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

The `WebGLRenderPipeline` has no support for framebuffers. This PR adds minimal support for handling the basic use case of binding the first color attachment of a framebuffer to a texture slot (in effect treating it as if were a texture). This change fixes the `CollisionFilterExtension` in deck.gl
- Allow for `WEBGLFramebuffer` in `WebGLRenderPipeline`
- Unpack first color attachment and use as source for texture

Bind framebuffer color attachment in render pipeline

---

modules/engine/src/model/model.ts

Followup to https://github.com/visgl/luma.gl/pull/1826
https://github.com/visgl/luma.gl/pull/1826 doesn't work after minification as the constructor name changes. Use better filter, as [suggested here](https://github.com/visgl/luma.gl/pull/1826#discussion_r1378298432)
- Filter out uniforms rather than hacky string match

Improve filter for texture bindings

---

modules/engine/src/model/model.ts

Followup to https://github.com/visgl/luma.gl/pull/1831
- Also filter out TypedArrays (to support deck Fp64Extension which uses them)

Handle TypedArrays when extracting bindings

---

examples/tutorials/lighting/app.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

For #
- Address comments
- Allow uniform blocks named `xyzUniforms` to be reference as `xyz` from JS.

feat(webgl): Unify shader block naming in JS

---

docs/api-reference/core/shader-layout.md
examples/showcase/persistence/app.ts
examples/tutorials/hello-cube/app.ts
examples/tutorials/shader-modules/app.ts
modules/webgl/src/adapter/resources/webgl-render-pass.ts

For #
- Persistence example broken
- Align persistence example and a few remaining examples with the new uniform block naming conventions
- Fix a bug in renderpass that doesn't reset framebuffer when renderpass.end() is called

fix(examples): Fix persistence example (uniform buffers)

---

modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

Restores `texture.update()` call for video textures in WebGL render pipeline.  Removes unused `_textureUniforms` and `_textureIndexCounter` properties on WEBGLRenderPipeline class.
Context:
- https://github.com/visgl/deck.gl/issues/8315

fix(webgl): Update video texture bindings before draw

---

.github/workflows/test.yml
.github/workflows/website.yml

Fixes warnings in CI:
- related https://github.com/visgl/deck.gl/pull/8331

chore(ci): Update CI dependencies

---

modules/shadertools/src/lib/shader-module/shader-module.ts
modules/shadertools/src/modules/engine/picking/picking.ts

Follow up to https://github.com/visgl/luma.gl/pull/1856
- Differentiate types between input settings & uniforms in picking module
- Remove `Required` for type `uniforms` inference helper

Differentiate between settings/uniforms in picking

---

modules/core-tests/test/adapter/resources/command-buffer.spec.ts
modules/webgl/src/adapter/resources/webgl-command-buffer.ts

A few small but important fixes for CommandBuffer#copyTextureToBuffer, and restoring unit tests on that function. This PR is currently based on #1864, I'll hold it open until that is merged.

[core] Restore tests for CommandBuffer#copyTextureToBuffer

---

modules/webgpu/src/adapter/webgpu-device.ts
website/src/react-luma/components/device-tabs.tsx
website/src/react-luma/store/device-store.tsx

For #1501
- DeviceTabs creates hidden container for canvases used to create temporary devices
- DeviceTabs is browser only (enabled static build)
- WebGPUDevice to pass height, width and container to WebGPUCanvasContext context

website: device-store to create hidden canvases for device

---

docs/api-reference/core/resources/transform-feedback.md
modules/engine/src/model/model.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
modules/webgl/src/adapter/resources/webgl-transform-feedback.ts
modules/webgl/test/adapter/resources/webgl-transform-feedback.spec.ts

Updates the `TransformFeedback` API document to follow changes for v9 in https://github.com/visgl/luma.gl/pull/1858.

Update TransformFeedback API document

---

modules/gltf/src/gltf/gltf-instantiator.ts

The `gltfPrimitive` sometimes has the number of components specified by `size`, and sometimes by `components`, due to postprocessing done in loaders.gl https://github.com/visgl/loaders.gl/blob/master/modules/gltf/src/lib/api/post-process-gltf.ts#L397
It would be nice to tidy this up, for now this PR makes the code support both
- Support `size/components` when creating GLTF geometry

feat(gltf) Support both size & components in GLTF attributes

---

modules/engine/src/transform/transform.ts
modules/shadertools/src/modules-webgl1/math/fp64/fp64-arithmetic.glsl.ts
modules/shadertools/test/modules-webgl1/fp64/fp64-arithmetic-transform.spec.ts
modules/shadertools/test/modules-webgl1/fp64/fp64-test-utils-transform.ts

Restores FP64 arithmetic tests, which previously bailed out with `TransformFeedback.isSupported()` hard-coded to `false` during v9 API development. With TransformFeedback working, and a minimum Transform implementation in #1879, we can run the FP64 tests again and they'll pass in CI (Linux, Vulkan, unknown GPU).
Many tests still fail on Apple GPUs, and the `invariant` workaround unfortunately hasn't solved that issue, on my machine at least. For now I've enabled FP64 tests for Apple devices on the cases that do pass.

Restore FP64 arithmetic tests

---

modules/core/src/adapter/resources/transform-feedback.ts
modules/core/src/index.ts
modules/engine/src/transform/transform.ts
modules/engine/test/index.ts
modules/engine/test/transform/transform.spec.ts
modules/shadertools/src/modules-webgl1/math/fp64/fp64-arithmetic.glsl.ts
modules/shadertools/test/modules-webgl1/fp64/fp64-arithmetic-transform.spec.ts
modules/shadertools/test/modules-webgl1/fp64/fp64-test-utils-transform.ts
modules/shadertools/test/modules/engine/picking.spec.ts
modules/webgl/src/adapter/resources/webgl-transform-feedback.ts
modules/webgpu/src/adapter/helpers/get-vertex-buffer-layout.ts

As we've discussed recently, an API redesign is planned for the Transform class. This PR does not integrate any of the (still TBD) redesign changes. But because there are a number of areas in Deck.gl and Luma.gl that I'm not yet able to test without the Transform class, I felt it would be helpful to have a working 'minimum' Transform implementation against the v9 API as soon as possible.
Currently this implementation uses Transform Feedback to write to buffers only, and does not attempt to fall back on framebuffers. Basic tests pass.
~~No particular need to merge this, I'm just opening the branch and draft PR for reference.~~
Related:
- https://github.com/visgl/luma.gl/blob/master/docs/api-reference/core/resources/transform-feedback.md
- https://github.com/visgl/luma.gl/issues/1501

[engine] Minimum Transform implementation

---

modules/shadertools/test/modules-webgl1/fp64/fp64-arithmetic-transform.spec.ts
modules/shadertools/test/modules-webgl1/fp64/fp64-test-utils-transform.ts

Related:
- #1764 
On my laptop (Apple M2 Pro), adding the `invariant` specifier fixes these tests in Chrome, _if and only if_ I select the "OpenGL" ANGLE backend. That result doesn't make much sense to me, especially given the last response from Kimmo Kinnunen at https://bugs.webkit.org/show_bug.cgi?id=237434:
> Chrome is sometimes using OpenGL ES "backend" sometimes, sometimes Metal backend. The invariant fix is implemented only for Metal. Firefox is using OpenGL ES.
> 
> The OpenGL ES drivers do not have the invariance feature and have different kinds of optimizations. Thus the solution does not work on these implementations, unfortunately.
> 
> The better fix could be to ensure the values of the intermediate computations stay within the 32-bit float value domain.
I would have expected …

fix(shadertools): Add 'invariant' to fp64 varyings, partially fix issue on Apple GPUs

---

modules/core-tests/test/adapter/resources/command-buffer.spec.ts

Enables tests for `CommandBuffer#copyTextureToBuffer` where the source is a Framebuffer. I've removed references to the "bufferCreation" option, which doesn't appear to be implemented or perhaps necessary. Is it safe to say the destination buffer can be required when using this function?
Related:
- https://github.com/visgl/luma.gl/issues/1501
- "CommandEncoder: encapsulate webgl readPixel()"

Enable tests for copyTextureToBuffer with Framebuffer input

---

modules/core/src/adapter/type-utils/decode-attribute-type.ts
modules/core/src/adapter/type-utils/vertex-format-from-attribute.ts
modules/core/src/index.ts
modules/core/test/adapter/type-utils/vertex-format-from-attribute.spec.ts
modules/core/test/index.ts
modules/engine/src/geometry/gpu-geometry.ts
modules/webgl/src/classic/typed-array-utils.ts

`GPUGeometry` assumed that the buffer layout for attributes passed would always be using `float32`. This is wrong, for example when passing a `Uint8Array` for colors
- Add `getVertexFormatFromAttribute` util funtion
- Update `GPUGeometry`
- Tests

feat(engine) Support all vertex format types in GPUGeometry

---

modules/engine/src/model/model.ts
modules/shadertools/test/modules-webgl1/fp64/fp64-arithmetic-transform.spec.ts
modules/shadertools/test/modules-webgl1/fp64/fp64-test-utils-transform.ts
yarn.lock

For #
- I am working on a PR that drops support for GLSL 1.00 as the **source** language for luma.gl shaders. I will motivate this more fully in that PR, but basically to support WebGPU we need to embrace uniform buffers, which in WebGL requires GLSL 3.00, so we might as well write all our shader code in GLSL 3.00.
- As I was porting GLSL 1.00 shaders and fragments in our source to GLSL 3.00, I came across the fp64 tests.
- After I ported them, I got 5 new failures, just for subtractions.
- Hoping this could be a clue for someone (GLSL 1.00 and GLSL 3.00 do something differently, different backends etc.)
- Modify fp64 test shader
- ignore the new failing test cases.

chore(shadertools): Port fp64 tests to GLSL 3.00

---

examples/tutorials/hello-gltf/app.ts

Loading in large models led to a black screen as they were positioned outside viewport.
- Position camera vantage, taking into account world matrix
- Auto calculate near/far based on model size

feat(gltf) Improve model positioning by considering worldMatrix

---

modules/core/src/adapter/type-utils/vertex-format-from-attribute.ts
modules/core/test/adapter/type-utils/vertex-format-from-attribute.spec.ts
modules/engine/src/geometry/gpu-geometry.ts

For https://github.com/visgl/luma.gl/issues/1847, followup to https://github.com/visgl/luma.gl/pull/1884
- Add `normalized` parameter to `getVertexFormatFromAttribute()`

feat(engine) Support normalized attributes in GPUGeometry

---

modules/engine/src/animation-loop/animation-loop.ts

Remove the redundant `_running` check in `AnimationLoop.start`

refactor(engine): AnimationLoop start

---

modules/engine/src/model/model.ts
modules/webgl/src/adapter/resources/webgl-vertex-array.ts

Model creation was crashing when passed non-indexed `geometry` prop, e.g. https://github.com/visgl/deck.gl/blob/master/examples/website/orthographic/app.tsx#L24-L29
- Allow passing `null` to `setIndexBuffer` in `WEBGLVertexArray`

feat(webgl) Allow passing null to setIndexBuffer

---

modules/core-tests/test/adapter/resources/framebuffer.spec.ts
modules/core/src/adapter/canvas-context.ts
modules/core/src/lib/uniforms/uniform-buffer-layout.ts
modules/core/src/lib/utils/load-file.ts
modules/engine/src/animation-loop/animation-loop.ts
modules/engine/src/model/model.ts
modules/engine/src/shader-inputs.ts
modules/engine/test/shader-inputs.spec.ts
modules/shadertools/src/lib/shader-module/shader-module-instance.ts
modules/shadertools/src/modules/lighting/lights/lighting-uniforms.ts
modules/webgl/src/adapter/converters/sampler-parameters.ts
modules/webgl/src/adapter/converters/texture-formats.ts
modules/webgl/src/adapter/resources/webgl-framebuffer.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
modules/webgl/src/adapter/resources/webgl-sampler.ts
modules/webgl/src/adapter/resources/webgl-texture.ts
modules/webgl/src/classic/accessor.ts
modules/webgl/test/adapter/webgl-canvas-context.spec.ts
modules/webgpu/src/adapter/helpers/generate-mipmaps.ts
modules/webgpu/src/adapter/helpers/get-vertex-buffer-layout.ts

Should be no functional changes here, just making `yarn lint` happy.
There were a few cases like this...
```javascript
console.log(`Error because of ${object}`);
```
... which I tried to resolve reasonably, but the error message might appear a little different. I also removed a few debug logs in the shader input code.

chore(lint): Fix lint errors

---

modules/shadertools/src/modules/engine/picking/picking.ts

The order of uniforms in the `uniformTypes` must match that used in the shader. This was not the case in the picking module, which led to the incorrect layout being generated
with the positions of `useFloatColors` and `isHighlightActive` being swapped
- Correct order of uniforms in picking module

fix(shadertools): Correct order of uniforms in picking module

---

modules/engine/src/shader-inputs.ts
modules/engine/test/shader-inputs.spec.ts
modules/shadertools/src/modules/engine/picking/picking.ts
modules/shadertools/test/modules/engine/picking.spec.ts

deck.gl doesn't update all of the props for picking in one place, for example the `highlightColor` is set once when the layer is created. In contrast the `isActive` is changed very frequently, depending on whether a screen or picking pass is being rendered. In order to save the application (deck) from having to keep track of the state this change:
- Modifies `picking.getUniforms` to only return uniforms which are relevant to the passed in props
- Removes all knowledge of `picking.defaultUniforms` from `picking.getUniforms`
- Moves the responsibility for reading `defaultUniforms` into the `ShaderInputs` constructor
- Merges old uniforms with new uniforms in `ShaderInputs`
This design allows the `ShaderModule` to remain stateless, and only specify how props are translated into uniforms, …

feat(engine) Partial prop updates in ShaderInputs.setProps

---

modules/core/src/adapter/resources/shader.ts

When running unit tests, it isn't possible to `scrollIntoView()`:
```
(_a = document.getElementsByClassName("luma-compiler-log-error")[0]) == null ? void 0 : _a.scrollIntoView();
^
TypeError: _a.scrollIntoView is not a function
at WEBGLShader._displayShaderLog (/Users/carto/git/visgl/deck.gl/node_modules/@luma.gl/core/dist/index.cjs:1042:96)
at WEBGLShader.debugShader (/Users/carto/git/visgl/deck.gl/node_modules/@luma.gl/core/dist/index.cjs:1017:10)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

fix(core) Prevent crash when scrollIntoView unavailable

---

modules/engine/src/shader-inputs.ts

Applications may want to globally update props for modules (e.g. picking in deck) across many models, without having to worry about which models actually support the modules.

feat(engine) Ignore props for unregistered modules in ShaderInputs

---

modules/engine/src/model/model.ts

`BufferLayout` can specify multiple attributes in `bufferLayout.attributes`, for example deck.gl uses this to supply 64bit `instancePositions` via `instancePositions` and `instancePositionsLow64`. `setAttributes` was only inspecting `bufferLayout.name` when matching to a passes attribute, leading to warnings:
- Consider all attribute names when matching to buffer name

feat(engine) Model.setAttributes handle interleaved attributes

---

modules/engine/src/model/model.ts

I found `attribute.toString()` throwing an error in deck
- Handle null/undefined in attribute debug

bug(engine) Handle null/undefined in attribute debug

---

examples/showcase/persistence/app.ts
modules/core/src/adapter/device.ts
modules/engine/src/debug/copy-texture-to-image.ts
modules/engine/src/debug/debug-framebuffer.ts
modules/engine/src/debug/pixel-data-utils.ts
modules/engine/src/model/model.ts
modules/webgl/src/adapter/webgl-device.ts
modules/webgl/src/classic/copy-and-blit.ts

For #
- Adds optional ability to display framebuffer contents in mini-window.
- Based on similar code in deck.gl
- Renders all framebuffers however only one canvas and no handling for offsets etc, so only final fbo is shown, handing that is for future PRs.
- Added `copyTextureToImage` helper from v8 but didn't get it to work in this PR.
- Add temporary methods for `readPixels...()` to Device so apps don't have to import `@luma.gl/webgl` directly
- Add framebuffer debug support

feat(engine): Visual framebuffer debugger

---

modules/shadertools/src/lib/glsl-utils/get-shader-info.ts
modules/shadertools/test/lib/glsl-utils/get-shader-info.spec.ts

Fixes #1923
Some adjustments have been made to getShaderName in this PR
1. Allow SHADER_NAME Multiple spaces before and after the name
2. Mismatched line breaks, such as
```glsl
uniform float floaty;
#define SHADER_NAME
name-of-shader
main() {}
```

fix(shadertools): Standardize the matching of getShaderName

---

modules/core/src/adapter/canvas-context.ts
modules/webgl/src/adapter/webgl-canvas-context.ts
modules/webgl/src/adapter/webgl-device.ts

When attaching to an existing WebGL context `WebGLDevice.attach()` doesn't pass through the canvas, leading to `new WebGLDevice()` to create another canvas, even if the WebGL context already has one (as is commonly the case). For example affects: https://github.com/visgl/deck.gl/pull/8442
- Pass through `canvas` in `WebGLDevice.attach()`
- Handle resizing of external canvas

feat(webgl): Pass through canvas in WebGLDevice.attach()

---

docs/api-reference/core/bindings.md
docs/api-reference/core/canvas-context.md
docs/api-reference/core/device-features.mdx
docs/api-reference/core/parameters.md
docs/api-reference/core/resources/shader.md
docs/api-reference/core/resources/texture.md
docs/api-reference/core/shader-layout.md
docs/api-reference/core/texture-formats.mdx
docs/api-reference/engine/animation-loop.md
docs/api-reference/engine/transform/buffer-transform.md
docs/sidebar.json
docs/upgrade-guide/README.md

Formatting, broken link, and typo corrections made by me. Whitespace changes made by Prettier.

fix(docs): Fix table layouts, broken links, and typos in v9 docs

---

examples/showcase/instancing/app.ts
modules/core-tests/test/adapter/device-helpers/set-device-parameters.spec.ts
modules/core/src/adapter/device.ts
modules/webgl/src/adapter/webgl-device.ts
modules/webgl/src/index.ts
modules/webgl/test/adapter/device-helpers/set-device-parameters.spec.ts
modules/webgl/test/context/state-tracker/context-state.spec.ts
modules/webgl/test/context/state-tracker/data/sample-enum-settings.ts
modules/webgl/test/context/state-tracker/data/sample-function-settings.ts

For #1501 
- deck.gl still uses some webgl module methods, which forces it to import the webgl module
- Expose the required methods on the Device (for now)
- `device.setGLParameters(), `device.withGLParameters()`, `device.clear()`

chore: expose webgl-only functions on device

---

modules/engine/src/lib/pipeline-factory.ts
modules/engine/src/model/model.ts
modules/engine/test/lib/pipeline-factory.spec.ts

Related to https://github.com/visgl/deck.gl/issues/8458. Uses a PipelineFactory when models create new render pipelines. On its own this PR does not address the performance issue in deckgl, but should be done anyway. Further changes in #1950 and/or #1952 will address the performance.

feat(engine): Use PipelineFactory in Model

---

docs/whats-new.md
examples/tutorials/hello-cube/app.ts
modules/core-tests/test/adapter/resources/shader.spec.ts
modules/core/src/adapter/resources/render-pipeline.ts
modules/core/src/adapter/resources/shader.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
modules/webgl/src/adapter/resources/webgl-shader.ts

For #
- Proof of concept of using async shader compilation (i.e. status polling) using WebGL extension 
- Add async path in WEBGLShader
- Disable shader checking if not luma.log.level hasn't been set.
- Add async path in WEBGLRenderPipeline
- Check shader compilation status if pipeline linking fails
- Documentation updates (whats-new)
- Cache shader check status
- Show link error log in browser window (similar to shader.debugShader).
- Add tests? Strategy TBD

feat(webgl): async shader compilation

---

docs/api-reference/core/resources/shader.md
docs/api-reference/engine/model.md
docs/developer-guide/debugging.md
docs/whats-new.md
examples/glfx/package.json
modules/core/src/adapter/resources/shader.ts
modules/engine/src/model/model.ts
modules/webgl/src/adapter/resources/webgl-shader.ts

For #
- Noticed that Chrome supports the `WEBGL_debug_shaders`, can be instructive to see the native (translated) shader source.
- New method `Shader.getTranslatedSource()`
- Add translated source to `Shader.debugShader()` window
- New option `Model.props.debugShaders` (to force debug windows, translated source is only available when compilation succeeds)
- Documentation updates

feat(webgl): Show translated shader source

---

.prettierignore
docs/api-reference/engine/pipeline-factory.md
docs/api-reference/engine/shader-factory.md
docs/sidebar.json
docs/whats-new.md
modules/engine/src/index.ts
modules/engine/src/lib/shader-factory.ts
modules/engine/src/model/model.ts
modules/engine/test/index.ts
modules/engine/test/lib/shader-factory.spec.ts

Adds a `ShaderFactory` utility, similar to PipelineFactory, for caching and reusing Shader instances. Upstream in DeckGL, each tile currently creates a model, and each model creates a RenderPipeline and two Shader instances. With these changes, the models reuse cached RenderPipeline and Shader instances where possible.
The before/after images below show performance profiles running while animating the map from point A to point B.
- Fixes https://github.com/visgl/deck.gl/issues/8458#issuecomment-1955087738

feat(engine): Add ShaderFactory utility and caching

---

docs/api-reference/core/resources/texture-view.md
modules/core/src/adapter/resources/framebuffer.ts
modules/core/src/adapter/resources/texture-view.ts
modules/core/src/adapter/types/shader-layout.ts
modules/core/src/index.ts
modules/webgl/src/adapter/resources/webgl-command-buffer.ts
modules/webgl/src/adapter/resources/webgl-framebuffer.ts
modules/webgl/src/adapter/resources/webgl-texture-view.ts
modules/webgpu/src/adapter/resources/webgpu-texture-view.ts

For #1860 
- A `GPUTextureView` style class fills a gap in the luma.gl API, as it provides more fine grained control over texture usage in WebGL and will allow us to expose the full capabilities of WebGPU.
- Add abstract class, WebGL and WebGPU implementations
- update Framebuffer and Bindings to accept Tesxture Views.
- reference page for TextureView class.
- `Texture.createTextureView()` will be implemented once Texture refactor is landed.

chore: TextureView  plumbing

---

.eslintrc.cjs
examples/api/cubemap/app.ts
examples/api/texture-3d/app.ts
examples/tutorials/hello-cube/app.ts
examples/tutorials/lighting/app.ts
modules/constants/src/index.ts
modules/constants/src/webgl-types.ts
modules/core-tests/test/adapter/device.spec.ts
modules/core-tests/test/adapter/resources/texture.spec.ts
modules/core-tests/test/adapter/texture-formats.spec.ts
modules/core-tests/test/index.ts
modules/core/src/adapter/device.ts
modules/core/src/adapter/type-utils/decode-texture-format.ts
modules/core/src/utils/load-file.ts
modules/webgpu/src/adapter/webgpu-canvas-context.ts

For #1860
- The texture refactor is growing large and will be hard to review. This PR lands a number of trivial changes to reduce the delta.
-

chore: Prep for Texture refactor

---

modules/engine/src/model/model.ts
modules/engine/test/index.ts
modules/engine/test/lib/model.spec.ts

Restore most unit tests on the Model class. For some tests (getModuleUniforms, getBuffersFromGeometry) it was not obvious what the equivalent v9 behavior was, and I've removed those tests here. A couple more tests remain commented-out in `model.spec.ts`.

chore(engine): Restore tests for Model class

---

docs/api-reference/shadertools/shader-assembler.md
docs/whats-new.md
modules/engine/src/model/model.ts
modules/shadertools/src/index.ts
modules/shadertools/src/lib/shader-assembler.ts
modules/shadertools/src/lib/shader-assembly/assemble-shaders.ts
modules/shadertools/src/lib/shader-assembly/select-shaders.ts
modules/shadertools/test/lib/shader-assembler.spec.ts
modules/shadertools/test/lib/shader-assembly/assemble-shaders.spec.ts
modules/shadertools/test/lib/shader-assembly/inject-shader.spec.ts

…rPair
For #
- WGSL compute shaders and unified shaders have only a single shader.
- New assembleSingleShader() and assembleShaderPair() methods on ShaderAssembler.

feat(shadertools): ShaderAssembler support single compute/unified shader

---

modules/constants/package.json
package.json
tsconfig.module.json
yarn.lock

- Bump ocular-dev-tools
- Use `inline-webgl-constants` transformer
- Use `remove-glsl-comments` transformer

chore(build): size optimization

---

docs/api-reference/engine/computation.md
docs/sidebar.json
docs/whats-new.md
modules/core-tests/test/adapter/resources/compute-pipeline.spec.ts
modules/core/src/adapter/resources/compute-pipeline.ts
modules/engine/src/computation.ts
modules/engine/src/index.ts
modules/engine/src/model/model.ts
modules/engine/test/computation.spec.ts
modules/engine/test/index.ts
modules/shadertools/src/lib/shader-assembly/select-shaders.ts
yarn.lock

For #
- Similar to `Model`, `Transform`, it is convenient to have a high level class that manages Compute shader setup and invocation.
- Add new `Computation` class.
- Naming (`ComputeModel`, `ComputeTransform` ...)

chore(engine): Add Computation class

---

modules/gltf/src/gltf/gltf-instantiator.ts
modules/webgl/src/adapter/converters/device-parameters.ts
modules/webgl/src/adapter/objects/webgl-resource.ts
modules/webgl/src/adapter/resources/webgl-external-texture.ts
modules/webgl/src/adapter/resources/webgl-render-pass.ts
modules/webgl/src/adapter/webgl-device.ts
modules/webgl/src/classic/clear.ts
modules/webgl/src/context/parameters/unified-parameter-api.ts
modules/webgl/src/context/state-tracker/with-parameters.ts
modules/webgl/src/index.ts
modules/webgl/test/adapter/device-helpers/set-device-parameters.spec.ts
modules/webgl/test/adapter/objects/webgl-renderbuffer.spec.ts
modules/webgl/test/context/state-tracker/context-state.spec.ts
modules/webgl/test/context/state-tracker/set-parameters.spec.ts

For #
- Early on a number of WebGL functions was modified to accept both WebGL context and Device. 
- This no longer makes sense, and stricter typing helps reduce errors and clarify the status and scope of each function.
- Parameter functions no longer accept device, just context
- Stop attaching WebGL devices.

chore(webgl): Clean parameters

---

modules/core/src/lib/uniforms/uniform-store.ts
modules/engine/src/geometry/gpu-geometry.ts
modules/engine/src/model/model.ts

`Model.destroy` does not remove all resources
- Fix `UniformStore.destroy`
- Fix `GPUGeometry.destroy`
- Call `GPUGeometry.destroy` from `Model.setGeometry`
- Call `GPUGeometry.destroy` from `Model.destroy`

Fix Model memory leak

---

modules/test-utils/src/index.ts
modules/test-utils/src/null-device/null-canvas-context.ts
modules/test-utils/src/null-device/null-device-features.ts
modules/test-utils/src/null-device/null-device-info.ts
modules/test-utils/src/null-device/null-device.ts
modules/test-utils/src/null-device/resources/null-buffer.ts
modules/test-utils/src/null-device/resources/null-command-buffer.ts
modules/test-utils/src/null-device/resources/null-framebuffer.ts
modules/test-utils/src/null-device/resources/null-query-set.ts
modules/test-utils/src/null-device/resources/null-render-pass.ts
modules/test-utils/src/null-device/resources/null-render-pipeline.ts
modules/test-utils/src/null-device/resources/null-sampler.ts
modules/test-utils/src/null-device/resources/null-shader.ts
modules/test-utils/src/null-device/resources/null-texture-view.ts
modules/test-utils/src/null-device/resources/null-texture.ts
modules/test-utils/src/null-device/resources/null-transform-feedback.ts
modules/test-utils/src/null-device/resources/null-vertex-array.ts

A minimal, do-nothing implementation of the Device API for testing in environments without WebGL support.
- Add NullDevice to test-utils

feat(test-utils): add NullDevice

---

modules/engine/src/model/model.ts

Revert breaking change made in #1992
`vertexArray` and attributes are updated in `setBufferLayout` based on the new pipeline.
- Call `_setPipelineNeedsUpdate` before `_updatePipeline`

Unbreak Model.setBufferLayout

---

docs/api-reference/core/luma.md
docs/whats-new.md
modules/core/src/adapter/luma.ts
modules/core/test/adapter/luma.spec.ts
modules/core/test/index.ts
modules/test-utils/src/null-device/null-device-info.ts
modules/test-utils/src/null-device/null-device.ts
yarn.lock

For #
- useful to be able to attach WebGL contexts without importing webgl module
- luma.attachDevice
- docs
- tests

feat(core): luma.attachDevice()

---

modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

Causing a number of `'No texture'` crashes in deck, because `value.colorAttachments[0] instanceof WEBGLTexture` should never be true
- Check for `WEBGLTextureView`, not `WEBGLTexture`

webgl: Check for WEBGLTextureView, not WEBGLTexture

---

modules/core/src/adapter/resources/framebuffer.ts
modules/test-utils/src/null-device/resources/null-framebuffer.ts
modules/webgl/src/adapter/resources/webgl-command-buffer.ts
modules/webgl/src/adapter/resources/webgl-framebuffer.ts
modules/webgl/src/classic/copy-and-blit.ts
modules/webgpu/src/adapter/resources/webgpu-framebuffer.ts
modules/webgpu/src/adapter/resources/webgpu-render-pass.ts

For #2014
- A couple of bugs have been patched around incorrect usage of colorAttachments, as delayed effect of TextureView adoption.
- Abstract framebuiffer attachment props can now be properly typed in sub classes, removing need for potentially "error hiding" type casts in code that access them.

chore: Strengthen Framebuffer.attachment typings

---

docs/api-guide/gpu/gpu-buffers.md
docs/tutorials/hello-instancing.mdx
docs/tutorials/hello-triangle.mdx
docs/tutorials/lighting.mdx
docs/tutorials/shader-hooks.mdx
docs/tutorials/shader-modules.mdx
website/content/examples/api/animation.mdx
website/content/examples/showcase/persistence.mdx
website/content/examples/tutorials/hello-gltf.mdx
website/content/examples/tutorials/hello-instancing.mdx
website/content/examples/tutorials/lighting.mdx
website/content/examples/tutorials/shader-hooks.mdx
website/content/examples/tutorials/shader-modules.mdx
website/src/react-luma/components/device-tabs.tsx

Some features of Luma v9 do not yet work in WebGPU. To avoid having `<DeviceTabs />` crash when WebGPU is selected on these examples, this PR adds a prop so that individual examples can opt out of WebGPU support until we're able to implement that.

feat(website): Add 'devices' prop to DeviceTabs component

---

.gitignore
modules/core/src/adapter/device.ts
modules/engine/src/lib/pipeline-factory.ts
modules/engine/src/lib/shader-factory.ts

For #
- We have implemented caching via the Pipeline and Shader Factory classes.
- This means that if the app is creating several identical such objects at the same time, we will only create one copy.
- However we destroy cached elements as soon as they are no longer referenced.
- An app that repeatedly creates and destroys an object (perhaps a temporary layer or transform) won't benefit.
- While the perfect model would probably be a system that held on to only a certain number of released objects on an LRU-basis, that would require more book-keeping.
- This. PR adds an experimental `Device` option `_factoryDestroyPolicy: 'never'` that simply stops destroying unused objects and keeps them in the cache.
- Intended to allow us to test whether longer life of cached items has sufficient …

feat(core): Add factory destroy policy 'never' (9.1)

---

docs/api-reference/core/resources/render-pipeline.md
docs/api-reference/core/resources/transform-feedback.md
docs/upgrade-guide.md
docs/whats-new.md
modules/core/src/adapter/types/parameters.ts
modules/engine/src/geometry/geometry.ts
modules/engine/src/geometry/gpu-geometry.ts
modules/gltf/src/gltf/gl-utils.ts
modules/webgl/src/adapter/helpers/webgl-topology-utils.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts

For #
- WebGPU is more restrictive than WebGL in which topologies (WebGL draw modes) it supports.
- Warnings have been present announcing that the two WebGL-only topologies (`triangle-fan-webgl` and `line-loop-webgl` ) will be removed in 9.1
- deck.gl 9.1 is going to have to update its triangle-fan geometries to run on WebGPU anyways, so there is not much point in keeping these around.
- Remove support for `triangle-fan-webgl` and `line-loop-webgl` topologies.

chore(core): Remove webgl-only topologies (9.1)

---

modules/webgl/src/adapter/resources/webgl-vertex-array.ts

Fixes:
- https://felixpalmer.github.io/deck.gl/examples/tile-layer
- https://felixpalmer.github.io/deck.gl/examples/tile-layer-non-geospatial
It's not obvious to me that we should be able to bind the index buffer only once... if not, we need to bind on every frame.
Related:
- https://github.com/visgl/deck.gl/issues/8582

fix(webgl): Pair calls to bind/unbind VAO

---

modules/webgl/src/adapter/device-helpers/webgl-device-features.ts

For #
- Start addressing console warnings.
- One warning comes from luma.gl initializing extensions at initialization, before we use them (which we temporarily reverted to since the v9 on-demand approach caused some deck.gl regression). 
- This PR avoids initializing the extension in question.

chore(webgl): Avoid WEBGL_polygon_mode extension warning

---

modules/core/src/adapter/resources/render-pipeline.ts
modules/engine/src/lib/pipeline-factory.ts
modules/engine/src/model/model.ts
modules/engine/test/lib/model.spec.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

For discussion.
- Make sure we don't create more copies of a Program in WebGL than we need. Before this PR, we create one pipeline for every parameter configuration (just as we must in WebGPU).
- Renderpipeline.draw() now accepts optional `parameters` and `topology`.
- These are ignored on WebGPU but on WebGL these are used instead of `RenderPipeline.parameters/topology` if provided.
- PipelineFactor no longer includes topology and parameters in hash on WebGL
- 4 parameters can be changed in WebGPU should they be handled by this mechanism in parallel with existing mechanism?
There is a balance between completely pushing this type of logic down into `core` and keeping `core` as a thin GPU API mapping layer. 
I have given this quite a bit of thought. By handling some small amounts of device …

fix: Support sharing cached Pipelines with different parameters/topology in WebGL

---

modules/core/src/adapter/resources/command-encoder.ts
modules/webgl/src/adapter/resources/webgl-command-buffer.ts
modules/webgl/src/adapter/resources/webgl-framebuffer.ts

- `WEBGLFramebuffer` constructor resets framebuffer binding to previous handle instead of null
- `WEBGLCommandBuffer` copy-texture-to-buffer resets framebuffer binding to previous handle instead of null
- Fix `WEBGLCommandBuffer` copy-texture-to-texture

fix(webgl) texture to texture copy; framebuffer state leak

---

modules/core/src/adapter/device.ts
modules/webgl/src/adapter/webgl-device.ts

When debugging issues with interleaved layers ([example](https://github.com/visgl/deck.gl/issues/8602)) it can be helpful to have some way of resetting WebGL state, to isolate whether state is leaking between applications. I realize this method is one we'd probably want to avoid in production code, but perhaps with providing on the device API during v9.0 and v9.1 development? Thanks!

feat(webgl): Add device.resetWebGL() for debugging

---

modules/webgl/src/adapter/webgl-device.ts

This is breaking some test cases in deck.gl.
- `Device.withParametersWebGL` should return value from `func`

fix(webgl): withParametersWebGL return value

---

modules/webgl/src/adapter/resources/webgl-render-pass.ts

This is causing a regression in deck.gl's picking and collision filter. Calling `device.beginRenderPass()` or `renderPass.setParameters()` will always set `scissorTest` to `false`.
It could be argued that `beginRenderPass` is expected to reset the state (questionable because it doesn't do this to any other parameter), however `setParameters()` as a public method should never affect a value not present in the argument.
Alternatively we can allow `scissorRect` to accept `null` on which we disable scissor test.
- Only sets `scissorTest` if `scissorRect` is present

Do not reset scissorTest in WEBGLRenderPass

---

modules/webgl/src/adapter/resources/webgl-shader.ts

Already on master as part of #1860
- show shader debug message before throwing

fix(webgl): show shader debug message on compilation error

---

modules/core/src/adapter/types/parameters.ts
modules/webgl/src/adapter/resources/webgl-render-pass.ts

For https://github.com/visgl/deck.gl/pull/8636
When a WebGLRenderPass is created it [immediately does a clear()](https://github.com/visgl/luma.gl/blob/master/modules/webgl/src/adapter/resources/webgl-render-pass.ts#L36). deck.gl was previously setting a `colorMask` using `withParametersWebGL`, but now with this removed there is no way to set the `colorMask` before the clear operation. Doing it in `Pass.getLayerParameters()` is too late, as by then the `clear` operation has happened
- Support colorMask in RenderPass

webgl: Support colorMask in RenderPass

---

modules/engine/src/model/model.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

- Model: use `this.props.disableWarnings` as fallback not override
- WEBGLRenderPipeline: correctly respects disableWarnings

fix(webgl): disableWarnings option

---

modules/engine/src/model/model.ts

Until `Model.shaderInputs.setProps` supports bindings, `Model.updateModuleSettings` is still necessary.
- Disable inaccurate warning

Disable warning about updateModuleSettings

---

modules/webgl/src/adapter/converters/device-parameters.ts

#2029 is not enough
- Do not call `webglDevice.getExtension` unless needed

Avoid querying WebGL extension unless needed

---

modules/core/src/adapter/resources/render-pass.ts
modules/core/src/adapter/type-utils/vertex-format-from-attribute.ts
modules/shadertools/src/modules-webgl1/project/project.ts
modules/webgl/src/adapter/resources/webgl-vertex-array.ts

For https://github.com/visgl/deck.gl/issues/8711
- Broken '../..'  import, probably injected by vscode.
- Fix the import
- There seem to be two more cases on the release branch that have already been fixed on master, will make a separate PR for those.

fix(shadertools): Fix ../.. imports

---

modules/webgl/src/adapter/resources/webgl-render-pass.ts

- WEBGLRenderPass.end(): `popContextState` already restores framebuffer binding to what it was before `beginRenderPass()`. Should not mutate global state.
- `WEBGLRenderPass.setParameters()`: partially modify, not replace, `glParameters`

fix(webgl): Render pass parameter handling

---

modules/webgl/src/adapter/converters/device-parameters.ts

`gl.polygonOffset()` is only effective if `POLYGON_OFFSET_FILL` is enabled.
- Enable `POLYGON_OFFSET_FILL` when using `gl.polygonOffset()`

fix(webgl): enable polygon offset with depthBias

---

modules/webgl/src/adapter/resources/webgl-render-pipeline.ts

- Correct typo
Overall I am not sure what this code path is supposed to do. According to 
https://github.com/visgl/luma.gl/blob/0d1f1d9f402dd40c5339f24fa2cf47ed7409b8d0/modules/webgl/src/adapter/resources/webgl-shader.ts#L71-L74
If `log.level = 0`, then `compilationStatus` will never be `'error'`
If `log.level = 1`, then the shader instance would have called `debugShader()` already.

fix(webgl): shader debug

---

.ocularrc.js
docs/api-reference/core/luma.md
modules/core/src/adapter/luma.ts
modules/core/test/adapter/luma.spec.ts

Use enforceWebGL2 when a library is creating its own WebGL1 context privately, in order to create a WebGL2 context that is compatible with luma.gl.
- Adds enforceWebGL2

add(core) enforceWebGL2

---

examples/showcase/instancing/index.html
modules/core/src/adapter/resources/render-pipeline.ts
modules/engine/src/model/model.ts
modules/test-utils/src/null-device/resources/null-render-pipeline.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
test/apps/tree-shaking/app.js

For #https://github.com/visgl/deck.gl/issues/8776
- Setting instanceCount to 0 makes the model draw in non-instanced mode, instead of nothing.
- Add Model.props.isInstanced, Model.setInstanced and RenderPipeline.draw({isInstanced})
- Set isInstanced if instanceCount>0

fix(webgl): Support instanceCount=0 in draw()

---

modules/engine/src/model/model.ts

Follow up of #2070
`this.isInstanced` should be assigned if `props.isInstanced` is `false`.
- Fix prop presence check

fix(engine) Model handling props.isInstanced: false

---

docs/sidebar.json

Core functions are documented, but aren't discoverable unless they're in the TOC.
- Add luma.md to the sidebar

Add luma namespace to docs

---

modules/engine/src/shader-inputs.ts
modules/engine/test/shader-inputs.spec.ts
modules/shadertools/src/lib/shader-assembly/resolve-modules.ts

For https://github.com/visgl/deck.gl/pull/8782 implemented on 9.0 branch and tested against deck. Works for `project/project32` pair. Also tested with `luma.gl/examples/showcase/instancing` which uses a [non-ShaderModule input](https://github.com/visgl/luma.gl/blob/master/examples/showcase/instancing/app.ts#L240)
- Obtain module dependencies when constructing `ShaderInputs`
- Uncouple `getDependencyGraph` from `ShaderModuleInstance` type
- Test

shadertools: Resolve dependencies in ShaderInputs

---

modules/core/src/adapter/device.ts
modules/engine/src/animation-loop/make-animation-loop.ts
modules/webgl/src/adapter/webgl-adapter.ts
modules/webgl/src/adapter/webgl-device.ts
modules/webgl/src/context/debug/spector-types.ts
modules/webgl/src/context/debug/spector.ts
modules/webgl/src/index.ts
modules/webgl/src/utils/uid.ts
modules/webgl/test/context/state-tracker/webgl-state-tracker.spec.ts

Fixes #2080 
- spector doesn't initialize right
- change CDN, seems the babylon CDN is inactive/flaky (though this didn't seem to be the root cause)
- Add types for SpectorJS
- Change to initialize spector JS on context, not canvas
- Streamline spectorjs props handling

fix(webgl): Fix spectorjs

---

.github/workflows/website.yml
CHANGELOG.md
CODE_OF_CONDUCT.md
dev-docs/roadmaps/scenegraph-loaders-roadmap.md
docs/api-reference/core/luma.md
docs/api-reference/core/parameters.md
docs/upgrade-guide.md
docs/whats-new.md
lerna.json
modules/core/src/adapter/luma.ts
modules/core/src/adapter/types/parameters.ts
modules/core/test/adapter/luma.spec.ts
modules/engine/test/transform/texture-transform.spec.ts
modules/test-utils/tsconfig.json
modules/webgl/src/adapter/converters/device-parameters.ts
modules/webgl/src/adapter/webgl-adapter.ts
modules/webgl/src/context/polyfills/polyfill-webgl1-extensions.ts

Allow WebGL render pass to explicitly disable blending
Since WebGPU render pass has blending disabled by default this value will be safely ignored?
- Add blend: false which disables blending in WebGL

Add blend parameter

---

examples/api/animation/index.html
examples/api/cubemap/index.html
examples/api/texture-3d/index.html
examples/script/webgl/transform-feedback/index.html
examples/showcase/instancing/index.html
examples/showcase/persistence/index.html
examples/tutorials/hello-cube/index.html
examples/tutorials/hello-gltf/index.html
examples/tutorials/hello-instanced-cubes/index.html
examples/tutorials/hello-instancing/index.html
examples/tutorials/hello-triangle-geometry/index.html
examples/tutorials/hello-triangle/index.html
examples/tutorials/hello-two-cubes/index.html
examples/tutorials/lighting/index.html
examples/tutorials/shader-hooks/index.html
examples/tutorials/shader-modules/index.html
examples/webgpu/textured-cube/index.html

For #2101
- Fix typos in examples
- Fix a few cases where registerDevices() was changed to registerAdapters() but the arguments was not changed

Example typo fixes

---

modules/engine/src/model/model.ts
modules/engine/src/shader-inputs.ts
modules/engine/test/shader-inputs.spec.ts
modules/shadertools/src/lib/shader-module/shader-module.ts

`ShaderModule` has no support for bindings, which are needed to complete the port over to UBOs. If this approach looks OK I can make a PR on master, but doing this on v9 in order to test against deck.gl
- Add `getBindings` to `ShaderModule` type
- Support in `ShaderInputs` & `Model` classes
- Tests

feat(engine): ShaderModule.getBindings()

---

modules/test-utils/src/null-device/null-device.ts
modules/webgl/src/adapter/webgl-device.ts

For #
- Not sure why we have .getSize method on just two devices. I feel it is confusing as the mental model in luma v9 is that size is managed by a canvasContext (which has several getSize() methods for more detailed control over what size is intended).
- E.g. `device.getCanvasContext().getDrawingBufferSize()`
- Remove WebGLDevice.getSize() and NullDevice.getSize()

chore: Remove spurios device.getSize()

---

modules/core/src/adapter/resources/texture.ts
modules/core/src/gpu-type-utils/decode-texture-format.ts
modules/core/test/adapter/resources/texture.spec.ts
modules/core/test/gpu-type-utils/decode-texture-format.spec.ts
modules/webgpu/src/adapter/resources/webgpu-texture.ts

For #
- Texture initialization from data (rather than images) is more complicated in WebGPU as we need to work with buffers and command queues.
- For now creating `ImageData` objects for 8 bit data inputs enables test cases.
- Keep improving `decodeVertexFormat` to help identify which formats can be supported.

chore(webgpu): Fix webgpu texture creation for 8 bit data inputs

---

modules/engine/src/model/model.ts
modules/engine/src/shader-inputs.ts
modules/engine/test/shader-inputs.spec.ts
modules/shadertools/src/lib/shader-module/shader-module.ts
modules/shadertools/test/modules/engine/picking.spec.ts

Missing types for https://github.com/visgl/luma.gl/pull/2121
- Add `BindingValue` as possible return value from `getUniforms`

types: Add BindingValue to getUniforms return type

---

modules/engine/src/lib/animation-loop.d.ts

For #1656 
Seeing error `error TS2304: Cannot find name 'OffscreenCanvas'.` when building projects with this library.
PR https://github.com/visgl/luma.gl/pull/1649 added the `@types/offscreencanvas` dependency, but it is not currently being imported in `modules/engine/src/lib/animation-loop.d.ts`.
- Add missing import to `modules/engine/src/lib/animation-loop.d.ts` to fix missing Typescript reference

fix(engine): Cannot find name 'OffscreenCanvas'

---

modules/core/src/adapter/types/types.ts
modules/core/src/lib/uniforms/uniform-store.ts
modules/core/test/lib/utils/uniform.spec.ts
modules/engine/src/index.ts
modules/engine/src/shader-inputs.ts
modules/engine/test/shader-inputs.spec.ts
modules/shadertools/src/lib/shader-module/shader-module.ts
modules/shadertools/src/lib/shader-module/shader-pass.ts
modules/shadertools/src/lib/utils/uniform-types.ts
modules/shadertools/src/modules-webgl1/project/project.ts
modules/shadertools/src/modules/engine/picking/picking.ts
modules/shadertools/src/modules/engine/project/project.ts
modules/shadertools/src/modules/lighting/lights/lighting-uniforms.ts
modules/shadertools/src/modules/lighting/no-material/dirlight.ts
modules/shadertools/src/modules/lighting/pbr-material/pbr-material.ts
modules/shadertools/src/modules/postprocessing/image-blur-filters/tiltshift.ts
modules/shadertools/src/modules/postprocessing/image-blur-filters/triangleblur.ts
modules/shadertools/src/modules/postprocessing/image-blur-filters/zoomblur.ts
modules/shadertools/src/modules/postprocessing/image-fun-filters/colorhalftone.ts
modules/shadertools/src/modules/postprocessing/image-fun-filters/dotscreen.ts
modules/shadertools/src/modules/postprocessing/image-fun-filters/hexagonalpixelate.ts
modules/shadertools/src/modules/postprocessing/image-fun-filters/magnify.ts
modules/shadertools/src/modules/postprocessing/image-warp-filters/bulgepinch.ts
modules/shadertools/test/modules-webgl1/lights/lights.spec.ts
modules/shadertools/test/modules/engine/picking.spec.ts
modules/shadertools/test/modules/lighting/gouraud-material.spec.ts

Implements changes described https://github.com/visgl/deck.gl/pull/9044
- Improve `ShaderModule` type to deduce `UniformsT` & `BindingsT` from `PropsT`
- Remove `ShaderModuleInputs` (it is so close to `ShaderModule` I'm not sure I see the value in keeping it)
- Add `UniformTypes` helper from deck
- Fix types & tests

ShaderModule type improvement (v9)

---

docs/api-reference/core/resources/texture.md
docs/upgrade-guide.md
docs/whats-new.md
modules/core/src/adapter/resources/texture.ts
modules/core/src/index.ts
modules/core/test/adapter/resources/sampler.spec.ts
modules/core/test/adapter/resources/texture.spec.ts
modules/engine/src/model/split-uniforms-and-bindings.ts
modules/test-utils/src/null-device/resources/null-texture.ts
modules/webgl/src/adapter/resources/webgl-texture.ts
modules/webgl/src/utils/split-uniforms-and-bindings.ts
modules/webgpu/src/adapter/resources/webgpu-command-encoder.ts
modules/webgpu/src/adapter/resources/webgpu-texture.ts

For #
- WebGPU has one texture setting function that doesn't require CommandBuffers and working through GPU buffers.
- Expose `Texture.copyExternalImage()` function.

feat: Add Texture.copyExternalImage() function

---

modules/core/test/adapter/resources/texture.spec.ts
modules/webgl/src/adapter/helpers/webgl-texture-utils.ts
modules/webgl/src/adapter/resources/webgl-texture.ts

For #
- Fixes breakage found in deck.gl v9.1 testing
-

fix(webgl): Fix texture.copyExternalImage() with offsets

---

examples/api/animation/app.ts
examples/api/animation/index.html
examples/api/animation/package.json
modules/shadertools/src/lib/shader-assembly/assemble-shaders.ts
modules/shadertools/src/modules/lighting/no-material/dirlight.ts
website/content/examples/api/animation.mdx

For #
- Continue porting examples to WebGPU, this time its the animation example (which also uses the `dirlight` module.
- Implement WGSL shader in animation/app.ts
- Implement WGSL shader in dirlight shader module.
- Find workarounds for severe WGSL limitations around modularizing module parameter passing.

fix(webgpu): animation example, dirlight module

---

modules/shadertools/src/modules/lighting/gouraud-material/gouraud-material.ts
modules/shadertools/src/modules/lighting/gouraud-material/gouraud-shaders-glsl.ts
modules/shadertools/src/modules/lighting/lights/lighting-uniforms-glsl.ts
modules/shadertools/src/modules/lighting/lights/lighting-uniforms.ts
modules/shadertools/src/modules/lighting/phong-material/phong-material.ts
modules/shadertools/src/modules/lighting/phong-material/phong-shaders-glsl.ts

For https://github.com/visgl/deck.gl/pull/9074
- Rename modules to fit convention & UBO blocks
- Consistent use of early returns in shaders
- Correct order of props in `uniformTypes`
- Swap `GOURAUD_VS` and `GOURAUD_FS`

shadertools: lighting module fixes

---

examples/showcase/instancing/app.ts
modules/core/src/adapter/resources/framebuffer.ts
modules/test-utils/src/null-device/resources/null-framebuffer.ts
modules/webgl/src/adapter/resources/webgl-framebuffer.ts
modules/webgpu/src/adapter/resources/webgpu-framebuffer.ts

For #
- Fixes picking
- Update framebuffer bindings after framebuffer.resize
- 9.1 aligns with WebGPU and uses WebGL readonly textures, meaning that textures need to be destroyed and recreated on resize.
- After a new texture handle is created, the framebuffer attachment points were not updated.

fix: Framebuffer resize

---

modules/shadertools/src/modules/lighting/gouraud-material/gouraud-material.ts
modules/shadertools/src/modules/lighting/phong-material/phong-material.ts

Fix typo in https://github.com/visgl/luma.gl/pull/2169
- Actually normalize `specularColor`

shadertools: Normalize specularColor

---

modules/core/src/adapter/resources/framebuffer.ts
modules/webgl/src/adapter/resources/webgl-framebuffer.ts

For #
- In luma v8, textures autocreated by framebuffers have linear filtering
-

fix: luma8 sampler param compatibility

---

examples/api/texture-3d/app.ts
examples/api/texture-3d/index.html
modules/webgl/src/adapter/resources/webgl-texture.ts

For #2115 
In `webgl-texture.ts`, `setImageData` was being called with `format: glFormat` which in the `'3d'` case would cause a problem.
There were also a couple of other changes that seemed to be necessary to get the example to work.

Tex3d patch

---

docs/api-guide/gpu/gpu-initialization.md
docs/api-reference/core/README.md
docs/api-reference/core/canvas-context.md
docs/api-reference/core/device.md
docs/api-reference/core/luma.md
docs/api-reference/webgl/README.md
docs/api-reference/webgpu/README.md
docs/developer-guide/installing.md
docs/upgrade-guide.md
examples/showcase/instancing/app.ts
examples/showcase/instancing/index.html
modules/core/src/adapter/canvas-context.ts
modules/core/src/adapter/device.ts
modules/core/src/adapter/luma.ts
modules/engine/src/animation-loop/make-animation-loop.ts
modules/test-utils/src/create-test-device.ts
modules/test-utils/src/null-device/null-adapter.ts
modules/test-utils/src/null-device/null-device.ts
modules/webgl/src/adapter/webgl-adapter.ts
modules/webgl/src/adapter/webgl-device.ts
modules/webgl/test/adapter/webgl-device.spec.ts
modules/webgpu/src/adapter/webgpu-adapter.ts
modules/webgpu/src/adapter/webgpu-device.ts
website/src/examples/templates.tsx
website/src/react-luma/components/luma-example.tsx
website/src/react-luma/store/device-store.tsx

For #
- Felt that the new `DeviceProps.canvasContext` prop was not clear enough.
- Clean up the new DeviceProps.canvasContext prop to DeviceProps.createCanvasContext
- Accept `true` as a value
- Move page load synchronization to luma.create/attachDevice to deduplicate logic from the 3 device implementations

chore(core): DeviceProps.createCanvasContext: CanvasContextProps | true

---

docs/api-guide/gpu/gpu-textures.mdx
docs/api-reference/core/resources/sampler.md
docs/upgrade-guide.md
docs/whats-new.md
modules/core/src/adapter/resources/sampler.ts
modules/webgl/src/adapter/converters/sampler-parameters.ts
modules/webgpu/src/adapter/resources/webgpu-sampler.ts

For #
- deck.gl tests on 9.1 branch seem to fail due to texture filtering being better than in 9.0.
- One possibility is that we now use mipmap filtering whereas we did not in 9.0 (based on quick code search, pretty sure we did not in 8.x).
- mipmapFiltering default changed from `'nearest'` to `'none'`

fix(webgl): Do not enable mipmap filtering by default

---

modules/core/src/gpu-type-utils/vertex-format-from-attribute.ts

For https://github.com/visgl/deck.gl/discussions/8815#discussioncomment-10405194
- Relax restriction on vertex formats temporarily to unblock 3D Tiles.
- Allow webgl 1,3 component unorm8 attributes

fix(core): Allow webgl 1,3 component unorm8 attributes

---

modules/core/src/adapter/type-utils/vertex-format-from-attribute.ts

For #
- temporarily restore support for webgl only vertex attributes
-

fix(core): Allow webgl 1,3 component unorm8 attributes (#2196)

---

modules/engine/src/animation-loop/animation-loop.ts
modules/engine/src/animation-loop/request-animation-frame.ts
modules/engine/src/index.ts
modules/test-utils/src/deprecated/classic-animation-loop.ts
modules/test-utils/src/test-runner.ts

Fixes ##2111
- In the script, the polyfill overwrites window.requestAnimationFrame and ends up calling itself ad infinitum.
- Rename the polyfills to avoid collision

fix(engine): Prevent infinite recursion in RAF polyfills

---

modules/shadertools/src/modules/engine/picking/picking.ts

For https://github.com/visgl/luma.gl/commit/4f333003ff391018391fa7d29a870b58d10a72d6#r145602362 fixes crash in deck

shadertools: Reinstate old picking shader

---

modules/core/src/gpu-type-utils/decode-texture-format.ts
modules/core/src/gpu-type-utils/texture-features.ts
modules/core/src/gpu-type-utils/texture-format-info.ts
modules/core/src/gpu-type-utils/texture-format-table.ts
modules/core/src/gpu-type-utils/texture-formats.ts
modules/core/test/gpu-type-utils/decode-attribute-type.spec.ts
modules/core/test/gpu-type-utils/decode-texture-format.spec.ts
modules/core/test/gpu-type-utils/decode-vertex-format.spec.ts
modules/core/test/gpu-type-utils/vertex-format-from-attribute.spec.ts
modules/core/test/portable/uniform-buffer-layout.spec.ts

For #
- Encountering cases where we need more information about textures. E.g. mipmaps can only be generated for renderable and filterable texture formats.
- Copy common information from the WebGL specific texture format table into core.
- Add support for bits-per-channel array (suggested by @donmccurdy).
- Improve texture capability query functions to take advantage of the common table.
- Remove duplicate information from the WebGL specific table.

chore: Refactor core texture info table 

---

docs/api-reference/core/device.md
docs/api-reference/core/luma.md
modules/core/src/adapter/device.ts
modules/core/src/adapter/resources/render-pass.ts
modules/core/src/adapter/resources/sampler.ts
modules/core/src/adapter/resources/texture.ts
modules/core/test/adapter/resources/texture.spec.ts
modules/test-utils/src/null-device/resources/null-texture.ts
modules/webgl/src/adapter/converters/texture-formats.ts
modules/webgl/src/adapter/resources/webgl-external-texture.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
modules/webgl/src/adapter/resources/webgl-texture.ts
modules/webgpu/src/adapter/resources/webgpu-texture.ts

For #
- Reduce amount of unused code
- Reduce amount of unused / legacy code
- Fix props.data access errors
- Add device option to override texture default props (enable deck.gl to set mipmaps to default to true).
- Handle mipmap generation failure for unsupported formats

chore(webgl): Clean up WebGLTexture implementation

---

.github/workflows/test.yml
package.json

For #
- tests often fail because yarn.lock in website directory has not been updated.
- the logs are confusing since this step is added to normal tests
- mark website build as separate CI step

chore: Separate out website build step in CI test workflow

---

modules/core/test/adapter/resources/texture.spec.ts
modules/webgl/src/adapter/resources/webgl-texture.ts

For https://github.com/visgl/deck.gl/pull/8833
- Clip width/height based on texture (not image) size
- Test

webgl: clip image write based on texture size

---

examples/tutorials/hello-triangle-geometry/app.ts
examples/tutorials/hello-triangle-geometry/index.html
examples/tutorials/hello-two-cubes/app.ts
modules/core/src/adapter/canvas-context.ts
modules/core/src/adapter/device.ts
modules/core/src/adapter/resources/vertex-array.ts
modules/core/test/adapter/canvas-context.spec.ts
modules/core/test/adapter/resources/buffer.spec.ts
modules/core/test/adapter/resources/compute-pipeline.spec.ts
modules/core/test/adapter/resources/vertex-array.spec.ts
modules/engine/src/compute/texture-transform.ts
modules/engine/src/factories/pipeline-factory.ts
modules/engine/src/model/model.ts
modules/engine/test/compute/buffer-transform.spec.ts
modules/engine/test/compute/computation.spec.ts
modules/engine/test/lib/model.spec.ts
modules/shadertools/src/lib/shader-assembly/assemble-shaders.ts
modules/test-utils/src/null-device/null-canvas-context.ts
modules/test-utils/src/null-device/null-device.ts
modules/webgl/src/adapter/resources/webgl-render-pass.ts
modules/webgl/src/adapter/resources/webgl-render-pipeline.ts
modules/webgl/src/adapter/webgl-canvas-context.ts
modules/webgl/src/adapter/webgl-device.ts
modules/webgl/test/adapter/resources/webgl-buffer.spec.ts
modules/webgl/test/adapter/resources/webgl-transform-feedback.spec.ts
modules/webgl/test/adapter/resources/webgl-vertex-array.spec.ts
modules/webgpu/src/adapter/helpers/get-bind-group.ts
modules/webgpu/src/adapter/helpers/get-vertex-buffer-layout.ts
modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts
modules/webgpu/src/adapter/webgpu-canvas-context.ts

For #
- The CanvasContext drawing buffer support implementation was built on the old device pixel handling code which had grown hard to maintain and was known to fail in edge cases and had a lot of WebGL specifics left in it.
- Turns out there is a new better way to track drawing buffer sizes, that works for both WebGPU and WebGL, namely `devicePixelContentBox`
-   https://web.dev/articles/device-pixel-content-box
- https://webgpufundamentals.org/webgpu/lessons/webgpu-resizing-the-canvas.html
- This brings WebGPU examples to full DPR resolution
- Adopt the new `devicePixelContentBox` browser API.
- Streamline WebGL and WebGPU implementation
- Also includes some minor fixes to WebGPU examples.
- Implement useDevicePixels props (currently doesn't disable device pixel multiplier in …

chore: Modernize CanvasContext size tracking

---

modules/core/src/gpu-type-utils/decode-texture-format.ts
modules/core/src/gpu-type-utils/texture-format-capabilities.ts
modules/core/src/gpu-type-utils/texture-format-table.ts
modules/core/src/index.ts
modules/core/test/adapter/resources/texture.spec.ts

chore: Restore minification optimized texture table

---

modules/engine/src/compute/computation.ts
modules/engine/src/model/model.ts
modules/gltf/src/pbr/parse-pbr-material.ts
modules/shadertools/src/lib/shader-assembly/assemble-shaders.ts
modules/shadertools/src/lib/shader-module/shader-module.ts
modules/shadertools/src/modules-webgl1/lighting/lights/lights.ts
modules/shadertools/src/modules-webgl1/lighting/pbr/pbr.ts
modules/shadertools/src/modules/lighting/gouraud-material/gouraud-material.ts
modules/shadertools/src/modules/lighting/lights/lighting.ts
modules/shadertools/src/modules/lighting/pbr-material/pbr-material.ts
modules/shadertools/src/modules/lighting/phong-material/phong-material.ts
modules/shadertools/test/lib/shader-assembler.spec.ts

For #
- Proposal for luma.gl API change, `defines: Record<string, number, boolean>` => `defines: Record<string, boolean>`
- See discussion in https://github.com/visgl/luma.gl/pull/2173#discussion_r1721704919
- WGSL doesn't have a preprocessor, we have a simple `#ifdef/#endif` processor in shadertools, but no interest in making it more full featured (e.g. support text replacement, `#if defined(...)` etc.
- WGSL has `@override` constants for scalar values, that can be set at Pipeline creation "modifying" an already compiled shader. Suggest we add a new `constants` or `overrides` section for numeric values that takes advantage of this on WebGPU.
- For string valued defines, we already have an injection system, let's rely on that.
- `defines` can only have boolean values.

chore(shadertools): Support boolean shader defines only (v9.2)

---

modules/shadertools/src/index.ts
modules/shadertools/src/modules/math/fp64/fp64-arithmetic-glsl.ts
modules/shadertools/src/modules/math/fp64/fp64-functions-glsl.ts
modules/shadertools/src/modules/math/fp64/fp64.ts
modules/shadertools/test/index.ts
modules/shadertools/test/modules/math/fp64-arithmetic-transform.spec.ts
modules/shadertools/test/modules/math/fp64-test-utils-transform.ts

For https://github.com/visgl/deck.gl/issues/8997, once merged will also apply to `9.1-release` to unblock https://github.com/visgl/deck.gl/pull/9160
- Copy across webgl1 implementation
- Add UBO block
- Use `defaultUniforms` instead of `getUniforms`
- Types
- Re-instate tests

Port fp64 module to UBO

---

docs/api-reference/core/luma.md
modules/core/src/adapter/adapter.ts
modules/core/src/adapter/luma.ts
modules/core/test/adapter/luma.spec.ts
modules/test-utils/src/null-device/null-adapter.ts
modules/webgl/src/adapter/converters/webgl-shadertypes.ts
modules/webgl/src/adapter/webgl-adapter.ts
modules/webgpu/src/adapter/webgpu-adapter.ts
modules/webgpu/src/adapter/webgpu-canvas-context.ts

For #
- Implement dynamic import in webgl and webgpu modules
- Breaking change `luma.registerDevices()` backwards compatibility was no longer feasible, apps must now update to `luma.registerAdapters()`.
- webgpu and webgl index.ts should no longer export anything except the adapter and pure types?
- How to measure bundle size impact?

feat: Dynamically load backends

---

modules/webgl/src/adapter/webgl-canvas-context.ts

Follow-up to https://github.com/visgl/luma.gl/pull/2237 which breaks canvas handling in deck.
@ibgreen I'm going to try and integrate this into deck to see if we can update luma9.1 there and move forward. I don't think it is worth trying to update deck to the new APIs in luma now, as there is still a lot of cleanup needed on the luma side (many TODOs & deprecated in the `canvas-context.ts` & `webgl-canvas-context.ts`)
- Re-instate old behavior where `WebGLCanvasContext.resize()` calls  `_setDevicePixelRatio()`

webgl: Canvas resizing minimal back-compatibility fix

---

modules/core/src/adapter/canvas-context.ts
modules/core/src/utils/promise-utils.ts
modules/core/test/adapter/canvas-context.spec.ts
modules/core/test/adapter/device-helpers/device-features.spec.ts
modules/core/test/adapter/device-helpers/device-info.spec.ts
modules/core/test/adapter/device-helpers/device-limits.spec.ts
modules/core/test/adapter/device.spec.ts
modules/core/test/adapter/texture-formats.spec.ts
modules/core/test/index.ts
modules/engine/src/animation-loop/animation-loop.ts
modules/engine/src/modules/picking/legacy-picking-manager.ts
modules/engine/src/modules/picking/picking-manager.ts
modules/test-utils/src/null-device/null-canvas-context.ts
modules/webgl/src/adapter/webgl-canvas-context.ts
modules/webgl/test/adapter/webgl-canvas-context.spec.ts
modules/webgpu/src/adapter/webgpu-canvas-context.ts
yarn.lock

For #
- CanvasContext API is still inheriting excessive complexity and causing issues in deck.gl upgrades.
- Keep simplifying, cutting unnecessary code/features.

chore(core): Simplify canvas contexts

---

modules/gltf/src/gltf/gltf-instantiator.ts

Fixes regression introduced in https://github.com/visgl/luma.gl/pull/2203
`deepCopy` has no handling for `ImageBitmap`, which means it attempts to clone it as a standard JS object. Later this leads to [isExternalImage](https://github.com/visgl/luma.gl/blob/master/modules/core/src/image-utils/image-types.ts#L29) erroneously returning false. The end result is that all image loading fails for GLTF models, breaking many things in deck: `ScenegraphLayer`, `Google 3D tiles` etc 
Will create PR for 9.2 once fix merged & confirmed in deck.gl
- Do not clone `ImageBitmap`

fix(gltf): Copy across ImageBitmap in deepCopy

---

modules/engine/src/model/model.ts

For #
- deck.gl raised concerns that removal of `model.setUniforms()` will break custom layers.
- Add back `model.setUniforms()`.

chore(engine): Add back Model.setUniforms()

---

modules/webgpu/src/adapter/webgpu-device.ts

For #2292
See ticket
- Check optionally for both adapter.info and getAdapterInfo()

fix(webgpu): Chrome has removed requestAdapterInfo (v9.0)

---

modules/core/src/adapter/canvas-context.ts
modules/webgl/src/adapter/webgl-device.ts

For #2295
- Disable `autoResize` when using an external WebGL context
- `cssToDeviceRatio()` fallback to canvas clientWidth when dimension cache is unavailable (this happens when resize() is never called)

fix(webgl): Prevent auto resizing when using external gl context (9.0-release)

---

modules/core/src/adapter/canvas-context.ts
modules/webgl/src/adapter/webgl-adapter.ts
modules/webgl/src/adapter/webgl-device.ts

For #2295
- Disable `autoResize` when using an external WebGL context
- `cssToDeviceRatio()` fallback to canvas clientWidth when dimension cache is unavailable (this happens when resize() is never called)

fix(webgl): Prevent auto resizing when using external gl context (9.1-release)

---

modules/webgl/src/adapter/webgl-adapter.ts
modules/webgl/src/adapter/webgl-device.ts

For https://github.com/visgl/luma.gl/issues/2295
- https://github.com/visgl/deck.gl/pull/9285
- Looks like the code path to attach to existing context had been lost during succession of refactors.
- Also added CanvasContext creation and autoResize prevention.

fix(webgl): Fix webglAdapter.attach()

---

modules/engine/src/model/model.ts
modules/engine/src/shader-inputs.ts

For #
- deck.gl gets excessive warnings for intentional usage
- disableWarnings flag on ShaderInputs, pass down from Model
- Somehow the typings are starting to act up, didn't have time to dig in, changed some expect-errors to ignore

fix(engine): Disable warnings in ShaderInputs

---

.github/workflows/release.yml
.github/workflows/website.yml

Follow up to https://github.com/visgl/luma.gl/pull/2309/files to enable releases
- Use `ubuntu-20.04` in all workflows

chore: pin ubuntu version in Github CI

---

modules/engine/src/shader-inputs.ts

Fix issue introduced by https://github.com/visgl/luma.gl/pull/2301
- Reinstate old behavior, when hiding the warning we still need to `continue` otherwise we crash

fix(engine): ShaderInputs ignore props with disableWarnings (9.1)

---

modules/core/src/adapter/device.ts
modules/test-utils/src/null-device/null-device.ts
modules/webgl/src/adapter/webgl-adapter.ts
modules/webgl/src/adapter/webgl-device.ts
modules/webgpu/src/adapter/webgpu-device.ts

For #9379
- Looks like deck.gl/react strict mode initializes and destroys a device two times on the same canvas == WewbGL context.
- Add a new option that returns the already attached device instead of creating a new device when creating two devices against the same canvas.
- Cherry pick to 9.1-release

fix(webgl): Add DeviceProps._reuseDevices to support deck.gl React StrictMode

---

package.json
yarn.lock

The pre-push hook is currently unused and is in conflict with the website publish task.
If you would rather keep it, I can alternatively add a removal step to the website CI flow.

Remove pre-push

---

docs/api-guide/gpu/gpu-attributes.md
docs/api-guide/gpu/gpu-rendering.md
docs/api-guide/gpu/gpu-storage-buffers.md
docs/api-reference/core/texture-formats.mdx
docs/api-reference/core/vertex-formats.mdx
docs/table-of-contents.json
docs/upgrade-guide.md
docs/whats-new.md
modules/core/src/adapter/device.ts
modules/core/src/shadertypes/utils/decode-vertex-format.ts
modules/core/src/shadertypes/vertex-formats.ts
modules/webgl/src/adapter/converters/webgl-shadertypes.ts
modules/webgl/src/adapter/converters/webgl-vertex-formats.ts
modules/webgl/src/adapter/webgl-device.ts
modules/webgpu/src/adapter/webgpu-device.ts
website/src/react-luma/components/device-info.tsx
website/src/react-luma/index.ts

For #
- WebGPU now supports single component 8 and 16 bit attributes, starting with Chrome 133.
- However 3 component attributes are still not supported, so this doesn't bring WebGL parity.

feat: Support new vertex formats in Chrome 133

---

modules/shadertools/src/index.ts

For https://github.com/visgl/deck.gl/issues/9416
Source:
```ts
export const picking = {...} as const satisfies ShaderModule<PickingProps, PickingUniforms, PickingBindings>;
```
Compiled (before):
```ts
export declare const pickingUniforms: {
readonly props: PickingProps;
readonly uniforms: PickingUniforms;
readonly uniformTypes: Required<import("modules/shadertools/dist/lib/utils/uniform-types").UniformTypes<PickingUniforms>>;
...
}
```
Compiled (after):
```ts
export declare const pickingUniforms: {
readonly props: PickingProps;
readonly uniforms: PickingUniforms;
readonly uniformTypes: Required<import("@luma.gl/shadertools").UniformTypes<PickingUniforms>>;
...
}
```
- Explicitly export `UniformTypes` from `@luma.gl/shadertools`

Explicitly export UniformTypes

---

modules/webgl/src/adapter/resources/webgl-render-pass.ts

The google-maps-overlay in deck sets `WebGLFramebuffer` as `Deck._framebuffer` in order to render into it: https://github.com/visgl/deck.gl/blob/master/modules/google-maps/src/google-maps-overlay.ts#L263-L268
This was working in luma 9.0, but 9.1 crashes as the `WebGLRenderPass` expects a luma.gl `WEBGLFramebuffer` object here: https://github.com/visgl/luma.gl/blob/master/modules/webgl/src/adapter/resources/webgl-render-pass.ts#L48-L50
This fix simply skips the `this.device.gl.drawBuffers()` calls when the passed `this.props.framebuffer` is not of the right type

fix(webgl): Do not set drawBuffers for external Framebuffer

---

modules/shadertools/package.json
modules/shadertools/src/modules/lighting/gouraud-material/gouraud-material.ts
modules/shadertools/src/modules/lighting/lights/lighting-wgsl.ts
modules/shadertools/src/modules/lighting/phong-material/phong-shaders-wgsl.ts
modules/webgpu/src/adapter/helpers/get-bind-group.ts
yarn.lock

Needed for https://github.com/visgl/deck.gl/pull/9531 in order to port point-cloud-layer to WebGPU.
- Add missing WGSL source for gouraud material
- Fix a typo in the lighting WGSL shader
- Fix uniform bindings not being found when a uniform is named in camelCase (e.g. `pointCloud`)
- Updated `wgsl_reflect` as the version being used crashes when encoutering a switch statement with multiple comma-separated `case`s when one case is `default`.

fix: lighting WebGPU shaders

---

modules/core/src/adapter/resources/pipeline-layout.ts
modules/core/src/adapter/types/shader-layout.ts
modules/core/src/index.ts
modules/webgpu/src/adapter/resources/webgpu-pipeline-layout.ts
modules/webgpu/src/adapter/resources/webgpu-render-pipeline.ts
modules/webgpu/src/adapter/webgpu-device.ts

Solves an issue raised in: https://github.com/visgl/deck.gl/pull/9531
Unused uniforms are stripped from WebGPU shaders by the compiler as they are not part of the shader's resource interface ([as per spec](https://www.w3.org/TR/WGSL/#example-aee0565d))
When shader source injection is performed as a result of using `modules` in `getShaders`, if the bindings injected by that call (such as lighting) go unused, the automatic layout generated by WebGPU will not contain these unused bindings.
Attempting to create the `BindGroupLayout` in this case will result in `luma` attempting to pass a binding for each uniform it's aware of from our WGSL introspection library. Ideally, we want to avoid this mismatch as it makes for a poor developer experience as commenting out lines of code to debug shaders …

feat: Use explicit pipeline layouts from shaderLayout

---

modules/webgpu/src/adapter/resources/webgpu-render-pass.ts

WebGPU requires 6 coordinates instead of 4, automatically fill depth with default values if they are not provided.
There's a separate issue I've noticed in deck where on the initial render the viewport is calculated incorrectly when a viewport (e.g. WebMercator) is calculated off the current canvas size but the canvas ResizeObserver has not triggered yet so `getGLViewport` uses a stale canvas size and produces a viewport with negative values. Those don't cause errors in WebGL, meaning the second render works as intended but WebGPU rejects this and prevents the app from rendering further.
For example, on my machine:
I'm not sure we should be silently adjusting values to avoid WebGPU errors in luma so the above should probably be fixed in deck as part of the WebGPU enablement.
-

chore: Fill viewport depth for webgpu if not provided

---

modules/webgpu/src/adapter/helpers/get-vertex-buffer-layout.ts
modules/webgpu/test/adapter/helpers/get-vertex-buffer-layout.spec.ts

For [deck.gl tracker](https://github.com/visgl/deck.gl/issues/9504), and to fix issue raised in https://github.com/visgl/deck.gl/pull/9531
When I originally ported the pointcloud layer, the attribute struct had been set up like the following:
```wgsl
struct Attributes {
@builtin(instance_index) instanceIndex : u32,
@builtin(vertex_index) vertexIndex : u32,
@location(0) positions: vec3<f32>,
@location(1) instanceNormals: vec3<f32>,
@location(2) instanceColors: vec4<f32>,
@location(3) instancePositions: vec3<f32>,
@location(4) instancePositions64Low: vec3<f32>,
@location(5) instancePickingColors: vec3<f32>
};
```
which results, perhaps confusingly, in the following error, as `instanceColors` are provided as a `unorm8x4` and should have stride 4, not 24.
If, instead, that struct is ordered …

fix: Ensure VertexBufferLayout matches parsed WGSL shader @location layout

---

modules/core/src/adapter-utils/buffer-layout-helper.ts
modules/core/src/adapter-utils/buffer-layout-order.ts
modules/core/src/index.ts
modules/core/test/adapter-utils/buffer-layout-order.spec.ts
modules/core/test/index.ts
modules/engine/src/model/model.ts

Similar to https://github.com/visgl/luma.gl/pull/2363, keep the shader as the single source of truth for vertex attribute binding order. The previous PR ensured the pipeline is created with the same order, but I then discovered the buffers could be bound at the wrong indices if an interleaved attribute existed (ie a buffer that is shared by two or more attributes).
In WebGPU, the binding location of a vertex buffer needs to match the buffer in the pipeline, not the `@location` reference in the shader. This meant that before some buffers were being bound in the wrong order leading to the wrong values being read in the shader.
With this and the previous PR, all attributes should be bound in a deterministic order which is derived from the shader source order which should make for a less …

fix: Vertex buffer locations set in the same order as pipeline, derived from shader source

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/website.yml

CI is [failing](https://github.com/visgl/luma.gl/actions/runs/14474031623/job/40595097807) with node v20

chore: Bump node version in workflows to 22.04

---

modules/gltf/package.json
modules/gltf/src/pbr/convert-webgl.ts
modules/gltf/src/pbr/parse-pbr-material.ts
modules/gltf/test/index.ts
modules/gltf/test/pbr/convert-webgl.spec.ts
modules/gltf/test/pbr/pbr.spec.ts
modules/webgl/src/adapter/converters/sampler-parameters.ts
yarn.lock

When switching from WebGL to WebGL/WebGPU some logic was abstracted so we have to make the glTF generate the sampler logic using the abstracted props.
- Logic to create sampler props from glTF
- Unit tests

gltf: fix samplers parsing for textures

---

modules/shadertools/src/modules/lighting/lights/lighting.ts
modules/shadertools/src/modules/lighting/phong-material/phong-shaders-glsl.ts

For https://github.com/visgl/deck.gl/pull/9241
https://github.com/visgl/luma.gl/pull/2190/files#diff-a9db84520c6b1bac02c1add1e117b9b1fbe19df69521554b26129f0cdc44ddf6 changed the default number of `MAX_LIGHTS` in the lighting module to 1. The default deck.gl `LightingEffect` uses 2 so this change makes the lighting look very different
- Default back to 3 max lights
- Consistent naming of `ambientColor` between TS and GLSL

fix(lighting): Default to 3 MAX_LIGHTS

---

modules/core/src/adapter/canvas-context.ts

For https://github.com/visgl/deck.gl/pull/9241
deck.gl expects to be able to pass a number for `useDevicePixels`. Without this it is impossible to force HD rendering on a low def screen (or in tests). 
Repro of `'scatterplot-smoothedge'` test case in browser with DPR configured to 1:
I would argue that `getDevicePixelRatio()` should be removed - it is not currently used and I think trying to add it in the code block where I made the change makes the code harder to read
- Manually set DPR when `useDevicePixels` is a number

fix(core): Support number for useDevicePixels

---

dev-modules/babel-plugin-inline-webgl-constants/package.json
modules/core/src/adapter/resources/command-buffer.ts
modules/core/src/adapter/resources/command-encoder.ts
modules/core/src/adapter/resources/resource.ts
modules/core/src/adapter/resources/texture.ts
modules/core/src/index.ts
modules/core/src/shadertypes/textures/texture-format-decoder.ts
modules/core/src/shadertypes/textures/texture-formats.ts
modules/core/src/shadertypes/textures/texture-layout.ts
modules/core/test/adapter/resources/texture.spec.ts
modules/core/test/index.ts
modules/core/test/shadertypes/textures/decode-texture-format.spec.ts
modules/core/test/shadertypes/textures/texture-layout.spec.ts
modules/effects/package.json
modules/engine/package.json
modules/gltf/package.json
modules/shadertools/package.json
modules/shadertools/test/index.ts
modules/test-utils/package.json
modules/test-utils/src/null-device/resources/null-texture.ts
modules/webgl/package.json
modules/webgl/src/adapter/resources/webgl-texture.ts
modules/webgpu/package.json
modules/webgpu/src/adapter/resources/webgpu-texture.ts
yarn.lock

For #
- Primary goal is to get WebGPU picking working in deck.gl
- This adds new methods so is safe to land, it does not break existing coe.
- Add new read/write methods to the Texture class hierarchy.
- These methods will be refined in upcoming PRs, with better tests etc.

feat(webgpu): Read pixels

---

examples/api/cubemap/app.ts
examples/api/cubemap/package.json
modules/webgpu/src/wgsl/get-shader-layout-wgsl.ts
modules/webgpu/test/wgsl/get-shader-layout-wgsl.spec.ts
yarn.lock

For #
- cube texture example threw exception under WebGPU since the texture dimension wasn't provided when setting up the bind group.
- extract the required params from wgsl_reflect data
- test

fix(webgpu): Extract texture dim,sampleType,multisample from WGSL declarations

---

docs/upgrade-guide.md
modules/core/src/adapter/canvas-context.ts
modules/core/test/adapter/canvas-context.spec.ts
modules/gltf/src/parsers/parse-gltf-lights.ts
modules/test-utils/src/null-device/null-canvas-context.ts
modules/webgl/src/adapter/webgl-canvas-context.ts
modules/webgpu/src/adapter/webgpu-canvas-context.ts

For #
- The advanced pixel perfect canvas size tracking in 9.2 caused a regression in the form of flicker on resize.
- This is because a drawing buffer resize clears the canvas, and also WebGPU reconfigures the context.
- The fix here is to defer the resize until the updated framebuffer is requested, which is typically done in the render loop.
- Add a needsResize flag
- Defer update to getCurrentFramebuffer
- Add "missing" TSDoc comments to CanvasContext fields and methods.

feat(core): Fix flicker when resizing CanvasContext
